### ISSUE TITLE
QR scanning

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#100]
This is one of the most complex parts we have of MVP and the last thing we need to complete in terms of features before preparing the app for production.

## Flow

We created a flowchart to visualize the whole flow of the process:
![QR scanning workflow drawio(1)](https://user-images.githubusercontent.com/7840007/235961744-46a039d5-6d83-45ef-8255-c0e684c56809.png)

## Views

@hunar1312, I would like you to help me with some of the views we have to design. 

Views that need front-end dev:

- [x] QR not found - https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?node-id=6276-340367&t=t2Ff3H4Te9yhR6fM-0 - Route: https://github.com/Shelf-nu/shelf.nu/blob/100-qr-scanning/app/routes/qr%2B/not-found.tsx

---

- [x] Item scanned | Not logged in - https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?node-id=6277-344806&t=t2Ff3H4Te9yhR6fM-0 - Route: https://github.com/Shelf-nu/shelf.nu/blob/100-qr-scanning/app/routes/qr%2B/not-logged-in.tsx
- [ ] ~Item scanned | Logged In | NOT owner of asset - https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?node-id=6288-355531&t=t2Ff3H4Te9yhR6fM-0 - Route: https://github.com/Shelf-nu/shelf.nu/blob/100-qr-scanning/app/routes/qr%2B/logged-in-not-owner.tsx~
- [x] Contact owner - https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?node-id=6277-344844&t=Yfl1XZNTY96G2gI0-0 + success note (https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?node-id=6277-344859&t=Yfl1XZNTY96G2gI0-0) - Route: https://github.com/Shelf-nu/shelf.nu/blob/100-qr-scanning/app/routes/qr%2B/contact-owner.tsx

---

- [x] Unlinked QR | Linked to user | Belongs to user- https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?node-id=6288-355382&t=t2Ff3H4Te9yhR6fM-0 - Route: https://github.com/Shelf-nu/shelf.nu/blob/100-qr-scanning/app/routes/qr%2B/unlinked-qr-belongs-to-user.tsx
- [ ] ~Unlinked QR | Doesn't belong to any user  - https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?node-id=6291-343760&t=t2Ff3H4Te9yhR6fM-0 - Route: https://github.com/Shelf-nu/shelf.nu/blob/100-qr-scanning/app/routes/qr%2B/unlinked-qr-orphaned.tsx~

@hunar They are all very simple views, mobile first. What I will do is create a branch where I will create all the files for each view and I will update this description so you know in which file to work.

**Comment by DonKoko** [comment]
Updated the flowchart. Found a more efficient way to go through the process.

**Comment by DonKoko** [comment]
@hunar1312 removed some elements from the list as I dont think they are needed.

**Comment by DonKoko** [comment]
Note to self. 

Some of the pages related to that are public so we need to handle some extra stuff and we shouldn't forget the:
- [ ] meta
- [ ] Title
- [ ] block robots?

**Comment by carlosvirreira** [comment]
> Note to self.
> 
> Some of the pages related to that are public so we need to handle some extra stuff and we shouldn't forget the:
> 
> * [ ]  meta
> * [ ]  Title
> * [ ]  block robots?

I think the page should be blocked by Robots - so it should not be indexed. We can add a simple title and description just to not have it empty but it is not per-se needed.
