### ISSUE TITLE
[Feature request]: Batch edit

### ISSUE THREAD

**Issue by edobez** [Shelf-nu/shelf.nu#1004]
### Contact Details

coolman3@gmail.com

### Is your feature request related to a problem? Please describe?

I'm typically creating an asset from the phone, either from scratch or using a unclaimed label.
At this point I'm not filling much information as it's easier and faster to do it from a computer.
This means that I have a bunch of semi-created items that needs some further editing. Most of the times I would like to apply the same location to a bunch of items, but now the process is very tedious, since you need to open the asset, click on Actions, then Edit, then provide the location - for each item.

Of course this doesn't just apply to location, but can be extended to tags, category, etc.

### Describe the solution you'd like

Possibility to select multiple items and batch apply an edit, such as location, tags, category and custom field.

**Comment by carlosvirreira** [comment]
@jurrejansen can you attach some exports of the UX we had in mind / for mobile so we can get @edobez to share opinions? (Whenever you can - I know you are busy with Alerts).

**Comment by jurrejansen** [comment]
@carlosvirreira Sure, I'll add some screenshots and the WIP scenario. However, I used an updated version of the index (page header + table header) which I was told not to use recently. So I'll have to make something work with the old design.

     ↳ [WIP] Performing bulk action
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=1201-19098

![Screenshot 2024-05-30 at 12 24 28](https://github.com/Shelf-nu/shelf.nu/assets/76112272/d59c1931-7ae4-4227-b87a-6c34b5ae9cc5)
![Screenshot 2024-05-30 at 12 24 37](https://github.com/Shelf-nu/shelf.nu/assets/76112272/96672935-0bb3-4938-a338-383d7ff20113)

**Comment by carlosvirreira** [comment]
Thoughts @edobez ?

**Comment by edobez** [comment]
Looks very promising! I think this fulfils the use case very well.

**Comment by DonKoko** [comment]
Bulk actions for assets are being released today. Will be also implemented on other entities as well in the future.
