### ISSUE TITLE
[Feature request]: Generate a QR code for a Kit

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1019]
### Is your feature request related to a problem? Please describe?

I have added all my assets to a kit (box) - I want to see quickly what Is supposed to be in the box for inspection.

### Describe the solution you'd like

Ideally I can scan a code and see the assets inside this kit

SCENARIOS

**Inspecting a QR code that is attached to a kit**
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=3828-60195

**Scanning a code that is linked to a kit**
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=5253-40227

**Scanning orphaned code and link to an existing kit**
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=6646-6360

**Comment by evonloch** [comment]
@carlosvirreira I would like to work on this issue. Can I get assigned to this issue?

**Comment by carlosvirreira** [comment]
Thank you for your interest in picking this up @evonloch

**Comment by carlosvirreira** [comment]
<img width="771" alt="Screenshot 2024-06-17 at 21 41 54" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/3f4ee430-fbc8-454f-8a59-85f06c9ce278">

@evonloch I think a placement like where I show it should be fine.

**Comment by carlosvirreira** [comment]
Figured out it needs much more back-end-logic than initially intended. Unassigning and re-thinking approach.

**Comment by DonKoko** [comment]
Also it requires a lot of front-end design.

**Comment by evonloch** [comment]
Got it! @DonKoko @carlosvirreira
