### ISSUE TITLE
[Improvement request]: Changes to bookings and integration of kits

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#1022]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

A few changes to improve UX and logic related to bookings and kits.

### Describe the solution you'd like

- [ ] When admins are managing assets for a booking, assets that are marked "Unavailable for bookings" should show when selection screen is filtered on "All asset"

- [ ] Admin should be able to add an asset that is marked as "Unavailable for bookings" to a Draft or Reserved booking. However, they'll be unable to perform the Check-out action

For Self-service users assets that are marked as "Unavailable for bookings" should not show up at all even when filtered on "All assets"

---

- [ ] When admins are managing kits for a booking, kits that include one or more assets that are marked "Unavailable for bookings" should show when selection screen is filtered on "All kits"

- [ ] Admin should be able to add a kit that includes one or more assets that are marked as "Unavailable for bookings" to a Draft or Reserved booking. However, they'll be unable to perform the Check-out action

For Self-service users kits that include one or more assets that are marked as "Unavailable for bookings" should not show up at all even when filtered on "All kits"

---

When managing assets for a booking, assets that are part of a kit won't show when selection screen is filtered on "Hide unavailable". However, when they filter on "All assets" assets that are part of a kit will show with a warning label. To improve UX we should show a badge showing the kit the asset is a part of.

- [ ] When managing assets for a booking show a badge displaying the kit of which an asset is part

https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=5519-54986

**Comment by DonKoko** [comment]
Okey Carlos shared with me what you guys discussed and I have thought about it quite a bit on how I want this to work for now. Of course we can change it in the future. I will close this issue and move the relevant info to the PR we have open.
