### ISSUE TITLE
[Bug]: User are displayed only with first name and lower capital letters

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#1028]
### What happened?

Custodian badges are not showing full name of user when asset status is In custody.

![Screenshot 2024-06-06 at 15 22 34](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a2b956d7-79be-471d-b451-6b41cbbb48a3)
![Screenshot 2024-06-06 at 14 45 30](https://github.com/Shelf-nu/shelf.nu/assets/76112272/9c69c369-16a1-42a7-9695-234d3eba4d20)
![Screenshot 2024-06-06 at 14 44 51](https://github.com/Shelf-nu/shelf.nu/assets/76112272/0a2ea8d1-4248-4e04-b93b-a245e915c153)

### What is the expected behaviour?

The users should be displayed with both First name and Last name

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by carlosvirreira** [comment]
ty for reporting @jurrejansen

**Comment by DonKoko** [comment]
@jurrejansen I cannot re-create either the dropdown nor the table issue. Please invite me to the workspace where this happens so I can check it out in detail. I have a suspicion what the reason could be but I need more info so I can search for it in the DB.
Thanks for reporting.

**Comment by jurrejansen** [comment]
Hi @DonKoko I am now experiencing blank menu items when checking out. Down below are 2 screenrecordings both recorded on the app.shelf. In the demo workspace it seems that the user that is appearing is blank is your user that was invited to investigate this issue.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/ccea5e02-d872-43c3-a1ac-474e9061300f
https://github.com/Shelf-nu/shelf.nu/assets/76112272/4e07f38f-e9d6-433a-97de-33ac52ba7c33

![Screenshot 2024-06-11 at 13 08 11](https://github.com/Shelf-nu/shelf.nu/assets/76112272/2a4f90b4-d966-4c16-9f1d-ea31f352cdff)
![Screenshot 2024-06-11 at 13 08 27](https://github.com/Shelf-nu/shelf.nu/assets/76112272/01d585f0-cabf-4a93-b13e-dbdf752865d5)

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira released a fix to live with lots of improvements.
This issue opened a can of worms but ended up being amazing improvement. Please re-open if you notice any issues.

**Comment by DonKoko** [comment]
OKey we still have some places that need adjustment, namely Notes:
![image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/bf45183a-ccd8-40c4-8eff-266b04b240f3)
![image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/23556b53-356d-49da-9deb-407c3f30de10)

**Comment by DonKoko** [comment]
@carlosvirreira this has been resolved. I had missed a few places. Also fixing this helped us find some other bugs related to NRM and bookings and custodians. Those are fixed as well.
