### ISSUE TITLE
[Feature request]: When an asset is ‘checked out’ you do not see to whom or how on the asset page. 

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1051]
### Is your feature request related to a problem? Please describe?

When an asset is ‘checked out’ you do not see to whom or how on the asset page. 

### Describe the solution you'd like

Idea: Use same block as custodian but for bookings?
<img width="729" alt="Screenshot 2024-06-12 at 12 30 01" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/c69b5e77-18bc-49a0-8766-a2ee8742717d">

### Describe alternatives you've considered

Wait for the addition of bookings tab. Can also help here. However, I think that the custodian shown on index and not on asset page is confusing.

**Comment by DonKoko** [comment]
@carlosvirreira this is done and release. LMK if there is any feedback.
