### ISSUE TITLE
[Feature request]:  I can see the face of one of my team members on the asset index. But not on the asset page?

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1052]
### Is your feature request related to a problem? Please describe?

 I can see the face of one of my team members on the asset index. But not on the asset page?

<img width="726" alt="Screenshot 2024-06-12 at 12 31 32" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/ff73fd70-1fbb-4c30-8f30-caf058cd667c">

### Describe the solution you'd like

Render the profile image on the widget.
<img width="508" alt="Screenshot 2024-06-12 at 12 33 46" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/47dfec8e-fd2e-4825-87c0-59cd58280978">

**Comment by DonKoko** [comment]
@carlosvirreira fixed and deployed.
