### ISSUE TITLE
[Feature request]: Bookings tab on asset page

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#1058]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

Currently if you see an asset is checked out its super hard to know from which booking.

### Describe the solution you'd like

Adding a Bookings tab on the asset page. This will show a booking index that exclusively shows bookings that includes the asset in question.

- The index will not show bookings that are in Draft status
- Administrators will see all bookings in which the asset is included
- Self-service user will only see bookings in which asset is included and of which they're the custodian

https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=6182-57241

![Screenshot 2024-06-13 at 15 09 30](https://github.com/Shelf-nu/shelf.nu/assets/76112272/c838c4e4-1fb8-4b85-9e4b-4341d27242e9)

**Comment by jurrejansen** [comment]
@carlosvirreira @DonKoko anything you'd like to add?

**Comment by DonKoko** [comment]
I think we should show drafts. If the admin wants to reserve a booking and access it via the asset, that wont be possible? not sure why not.
The rest I think is good and clear.

**Comment by carlosvirreira** [comment]
> I think we should show drafts. If the admin wants to reserve a booking and access it via the asset, that wont be possible? not sure why not. The rest I think is good and clear.

Does this mean that @jurrejansen has to design this or will the written spec be enough? Not sure if there is a task here or not.

**Comment by DonKoko** [comment]
This has been implemented and releasing to live app.
