### ISSUE TITLE
[Feature request]: add quantities of items for certain assets (Via Power User) 

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1060]
### Is your feature request related to a problem? Please describe?

For example, we have maybe 10 of the exact same type of battery.

### Describe the solution you'd like

On the asset index page I would want to see a total quantity and then a total quantity available for a specific type of asset. It wouldn’t be an umbrella asset for every battery we have but rather just save total number of assets inputed.  For example: “Sony NP-FZ100” as the asset name with total quantity set to 12 and as we check out those batteries the available quantity would decrease. This would allow us to reference how many we should have total and how many are available to use at that moment as well as check out and create bookings more efficiently.  At the moment if you wanted to take all 12 batteries you would have to select each battery individually.

For use on the kit page, it would be that one asset “Sony NP-FZ100” with the quantity set to 4. When that kit is checked out the total quantity of Sony NP-FZ100 batteries would decrease by 4.
Yes, if we add an item that has quantity to a kit we would specify how many of that item belongs with that kit. These kits/quantities align with equipment packages that we charge clients.
I would like to see a total number of that asset and a total number available to be checked out. So if someone needs batteries they could still check some out, while also seeing how many batteries they could take.

**Comment by DonKoko** [comment]
We already have 2 existing issues for this:
https://github.com/Shelf-nu/shelf.nu/issues/912
https://github.com/Shelf-nu/shelf.nu/issues/992

**Comment by jurrejansen** [comment]
Closing this and adding the most updated scenarios in https://github.com/Shelf-nu/shelf.nu/issues/912
