### ISSUE TITLE
[Bug]: Possible to create blank NRMs due to button not being disabled / Name field not being required

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#1061]
### Contact Details

jurre@shelf.nu

### What happened?

While adding NRM just click Add team member without filling the "required" name field

https://github.com/Shelf-nu/shelf.nu/assets/76112272/70de76f6-f261-4c5f-b76e-f58a67c7a0d6

### What is the expected behaviour?

Name field should be required and clicking the Add team member button should return a field error

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
@jurrejansen fix is being deployed. Thanks for report.
