### ISSUE TITLE
[Feature request]: Asset index - store searchParams 

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#1065]
### Is your feature request related to a problem? Please describe?

When I have some filters active on the asset asset and then I navigate to a different page, I want those filters to persist when I come back to the asset index.

### Describe the solution you'd like

Store the searchParams in a localStorage, the question is how do we make this smooth. The reason I ask is because localStorage is only accessible on the client, so it will be a very ugly flickr if we trigger the loader and once we get localStorage params it will reload basically.

**Comment by DonKoko** [comment]
hey @rphlmr. I know you used that a lot so I wanted to hear your opinion. Could we maybe use the `clientLoader` to prevent this issue from happening when we are storing this data on the client?

**Comment by DonKoko** [comment]
@rphlmr yeah I think we might have to go the cookie way. I like the idea of scoping it based on the path of the assets index so we don't send it with each request but only for that url.

@rajeshj11 is this an issue you might want to work on?

**Comment by rajeshj11** [comment]
> @rphlmr yeah I think we might have to go the cookie way. I like the idea of scoping it based on the path of the assets index so we don't send it with each request but only for that url.
> 
> @rajeshj11 is this an issue you might want to work on?

yeah, i would like to give it a try.

**Comment by rajeshj11** [comment]
@DonKoko please assign it to me. I will also check other approaches and will let you know about them before start the development

**Comment by DonKoko** [comment]
Thanks @rajeshj11 . I think the cookie approach is still the best as we can handle it on the server this way. Let me know and lets get started on this.

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira this is deployed to staging and ready to be tested. Needs to be tested carefully as it might break some filters.
Some things to note:
- it is scoped per org, so changing orgs is something to test
- All filters need to be tested

PLS let me know if all is good and we can release it.

**Comment by jurrejansen** [comment]
@DonKoko seems to work smoothly, tested all filters (present on asset index). I did notice if you switch through different accounts (logging out / in) that have access to the same workspace the filter config gets stored as well. This is expected I guess cause it works with cookies and not really a realistic case.

Anyways, didn't come across any issues

**Comment by carlosvirreira** [comment]
Happy to release @DonKoko
