### ISSUE TITLE
Pre-generate codes for production of Pre-printed codes

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#107]
Amount is unknown but it would be cool to look already at making a plan of approach for this.

**Comment by carlosvirreira** [comment]
@DonKoko I have decided:

Each sheet is 9 stickers (pre-cut)
We have a minimum order quantity to get started of 100 packs of boxes for packaging so I will need at a minimum (9x100)

So on the lower end 900 / on the crazy scenario we have demand for the larger SKU I will need more. 

I would like to test the following products (SKU) on marketplace:

* 9 Units
* 18 Units
* 27 Units
* 36 Units
* 45 Units
* 54 Units
* 63 Units
* 72 Units

I am curious about the demand curve for the different 'amount' of asset stickers.

**Comment by jurrejansen** [comment]
Being tracked in https://github.com/Shelf-nu/shelf.nu/issues/240
