### ISSUE TITLE
[Improvement request]: Adjustments to Team area within Settings

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#1071]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

Currently the user and NRM index are not suited for a large amount entries. This is because they user simplified tables and have not pagination.

### Describe the solution you'd like

Divide the Team area within setting into Users and Non-registered members by using tabs. Also, we'll be using the default table component that have filter capabilities and they'll be using the full width of the screen.

https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=6219-8696

**User index**
- Admin can filter based on Status using the dropdown that says "All". States are Active and Pending
- Admin can use search field to search for Name (and Role maybe?)

![Screenshot 2024-06-18 at 17 13 54](https://github.com/Shelf-nu/shelf.nu/assets/76112272/721160d3-7abd-451a-8675-1d1c3cacb092)

NRM index
- Admin can use search field to search for Name

![Screenshot 2024-06-18 at 17 14 02](https://github.com/Shelf-nu/shelf.nu/assets/76112272/bcbeaf66-ffc4-4afd-9b92-da6e3583e96c)

**Comment by jurrejansen** [comment]
@DonKoko let me know if something is unclear

**Comment by DonKoko** [comment]
This is done and released.
