### ISSUE TITLE
[Bug]: (To check if bug) Time Zone issues with Date picker field

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1073]
### What happened?

Used it a few times, and noticed the stored date is one day displayed prior to the entered date.  Time zone issue?  (But if I use EDIT, 01.01.2000 appears as entered.)

![image 2](https://github.com/Shelf-nu/shelf.nu/assets/12449255/c29737f3-b7b4-4ef4-9ccd-9f0f57d0da67)

### What is the expected behaviour?

Display the date I intent OR show me close to the field some info to hint me on how to format my data

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
@carlosvirreira I have adjusted this. Indeed the date was not being formatted based on the user's timezone as well as it was showing time which is irrelevant as the field we have when editing an asset is just Date not Datetime.
