### ISSUE TITLE
[Feature request]: Option to filter asset index on 'Uncategorized' assets

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#1074]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

A user commented that they would like the option of filtering the index on 'Uncategorized' assets. This basically means they want to have a filtered state of the asset index that shows all the assets that currently don't have a category assigned. 
 

### Describe the solution you'd like

Adding a 'No category' or 'Without category' option in the Category filter. I have created a separation between the normal entries within the dropdown list and the 'No category' option

![Screenshot 2024-06-19 at 13 09 41](https://github.com/Shelf-nu/shelf.nu/assets/76112272/08e7490e-1f55-4893-a8d7-a9d72a943097)

If selected only assets that have no category assigned will show. This UX is inspired by the ability to filter on time entries that have no project assigned within a Clockify environment.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/841195bd-2505-4037-9e31-82c4e1828d17

You can find the artboards needed here:
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=6244-36394

### OPTIONAL

Also implement a 'Select all' option so a user can select all categories and easily filter out categories they don't want to see.

![Screenshot 2024-06-19 at 12 55 05](https://github.com/Shelf-nu/shelf.nu/assets/76112272/1a0b9f70-ef0f-4152-9792-00d91243f6b4)

https://github.com/Shelf-nu/shelf.nu/assets/76112272/bf6e7ab5-6d32-4f48-aa18-10fadfa10982

Additionally, we could go the extra mile and also implement this for Tags, Location and Custodian.

![Screenshot 2024-06-19 at 13 05 23](https://github.com/Shelf-nu/shelf.nu/assets/76112272/9059aece-c2ba-4817-9a94-4b5536312f03)

![Screenshot 2024-06-19 at 13 05 23](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a26c3e22-fe59-4767-b588-4a60afe1243f)

**Comment by jurrejansen** [comment]
Hi @DonKoko let me know if you would like me to spend time on an actual scenario for this

**Comment by DonKoko** [comment]
@jurrejansen thanks man. I don't have time to review it today but will do as soon as I can and will let you know.

**Comment by DonKoko** [comment]
@rockingrohit9639 yeah I think thats fine as we need it only on the indecies where the `DynamicDropdown` is used for filtering. We also have to consider the visuals and that it has this little extra space below.

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira this is released to live. 
I am however not convinced about the "Select all" thing. Is it something requested by our users? I get the use case but I think its so super edge and unless its been requested by our users, I wouldnt give it such high value real estate. 
LMK what you think.
