### ISSUE TITLE
[Feature request]: Markdown/HTML in multi-line custom field

### ISSUE THREAD

**Issue by DroneProf** [Shelf-nu/shelf.nu#1093]
### Contact Details

rose196@purdue.edu

### Is your feature request related to a problem? Please describe?

Inputting html tags (i.e. \<img> or \<a href>) into the Description box does not render as an image or link. Tags in multi-line custom fields resolve to a shelf.nu link (i.e. https://app.shelf.nu/assets/clxpfnu5b018qzmtiwjt0p2qj/overview/%3Ca%20href=%22https://gitlab.com/purdue-uas/dispatch/public/-/raw/master/docs/resources/uasreg/DJI_Mavic2_AA.pdf%22%20target=%22_parent%22%3Etest%3C/a%3E?ref=shelf-webapp). 

### Describe the solution you'd like

In addition to allowing image fields as in #1005 it would be good to allow markdown in Asset/Kit description or multi-line custom field.

### Additional context

I store ephemeral data on gitlab, so it's ideal to build assets that link out to gitlab resources. Here is an example of an asset (in LibraryCat) that links to external data (FAA Registration): https://www.librarycat.org/lib/Purdue_UAS_Dispatch/item/215460287

**Comment by DonKoko** [comment]
hey @DroneProf . I just talked to @carlosvirreira and he mentioned about the discussion you had on your call.

So for the markdown, I think we can implement that quite straight forward. We already have markdown functionality we just need to implement it for the multiline fields. 

As for simply placing links in them multiline fields, you can already do that. We even detect if they are links and transform them to links in the UI:
![image](https://github.com/user-attachments/assets/a22df69e-b786-46f3-baa7-5c5f16913ebe)

As for the images, for now we might allow linking to external images in markdown but that will be limited to just a set of domains, as we are worried about security. 

Last but not least, I have added this to our roadmap so it should be picked up in the short term.

**Comment by carlosvirreira** [comment]
Is the latest version pushed to testapp @DonKoko ?

**Comment by carlosvirreira** [comment]
https://www.librarycat.org/lib/Purdue_UAS_Dispatch/item/215460288https://www.librarycat.org/lib/Purdue_UAS_Dispatch/item/215460287?ref=shelf-webapp



![Image](https://github.com/user-attachments/assets/dc77cd41-0ad3-4ee8-8d03-dbf93dfae42e)



![Image](https://github.com/user-attachments/assets/5c602369-7ba7-40a9-a731-807f6068dfd8)

**Comment by DonKoko** [comment]
It is merged already and live in production since yesterday.
