### ISSUE TITLE
font inconsistency

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#110]
https://testapp.shelf.nu/items/new

<img width="362" alt="Screenshot 2023-05-11 at 17 37 28" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/9a0b2f50-4cce-4ec0-8cd7-2072130d3140">

**Comment by DonKoko** [comment]
This is solved. Its being deployed right now.

**Comment by carlosvirreira** [comment]
Thank you - approved. Thanks!
