### ISSUE TITLE
Uploaded images (main image)

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#112]
Can we find a way to support HEIC? Perhaps we can change its file type to JPG or something pre-upload?

**Comment by DonKoko** [comment]
@carlosvirreira Can you explain how you test it.
I did it on my phone:
1. Opened an existing asset
2. Clicked Edit
3. Clicked choose photo
4. Took a picture with phone camera
5. Edited asset successfully

---

1. Opened an existing asset
2. Clicked Edit
3. Clicked choose photo
4. Chose a picture from library
5. Edited asset successfully

Same works for creating new asset. So for me it works as expected.

**Comment by carlosvirreira** [comment]
This works now on Safari. Actually it seems to make it into a PNG. This is great. A JPG could also work. For me this issue can be closed @DonKoko

**Comment by DonKoko** [comment]
@carlosvirreira yeah I am not doing anything to handle this. The iphone does it automatically. Thanks for confirming.
