### ISSUE TITLE
[Feature request]: Remaining bulk actions

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#1120]
We should add bulk actions to the other models. Lets start 1 by one so we can progressively release them. We can make PR per model, but keep track of the whole scope here.

## Kits

- [x] Delete
- [x] Assign custody
- [x] Release custody

## Category

- [x] Delete - we need to double check that the relations get cleaned up on delete. Should be in the schema

## Tags

- [x] Delete -  - we need to double check that the relations get cleaned up on delete. Should be in the schema

## Locations
- [x] Delete - we need to double check that the relations get cleaned up on delete. Should be in the schema

## Bookings

- [x] Delete - - we need to double check that the relations get cleaned up on delete. Should be in the schema
- [x] Archive
- [x] Cancel

## Custom fields

- [x] Activate/Deactivate - needs to consider tier when activating and we have to handle the errors

## NRM

- [x] Delete

**Comment by jurrejansen** [comment]
@DonKoko 

- [ ] When asset is part of a kit and custody has been assigned individually (not via related Kit) I am unable to Release custody via Bulk Action. When I go to asset page I am able to Release custody. This should only not be possible when an asset is In custody because the entire kit was assigned custody if I am not mistaken
https://github.com/Shelf-nu/shelf.nu/assets/76112272/9fddef0e-33f2-44ef-bc55-5af1cd91ef49

- [ ] I am unable to Assign custody to assets that are part of kit via Bulk select / actions.
https://github.com/Shelf-nu/shelf.nu/assets/76112272/15257dd7-9a4f-4c95-a47a-7cdd302ed3d7

Next one is kind of an edge case I think. I imported assets with kit and custodian resulting in 20 assets being part of a kit and having In custody status. However, all assets are In custody individually and not because the kit was assigned custody and assets inheriting the status. This can also happen without an import.

- [ ] When selecting the 20 assets that are in a kit and that have In custody status, Release custody action is blocked. For some reason when I go to next page (pagination) the action is possible
https://github.com/Shelf-nu/shelf.nu/assets/76112272/0c60cbf6-fe46-43b2-b34f-690c04e2dd2c

**Comment by DonKoko** [comment]
> Next one is kind of an edge case I think. I imported assets with kit and custodian resulting in 20 assets being part of a kit and having In custody status. However, all assets are In custody individually and not because the kit was assigned custody and assets inheriting the status. This can also happen without an import.

Yeah i know of this but tbh quite complex to solve. We ignore it for now. Also this is more related to imports.

@rockingrohit9639 can you address the other points please?

**Comment by DonKoko** [comment]
Okey so everything is resolved and released except this: 
>  When selecting the 20 assets that are in a kit and that have In custody status, Release custody action is blocked. For some reason when I go to next page (pagination) the action is possible

It is quite important we fix this. As far as I understand this happens because we only have the ids and when you are on page 2 we don't have the remaining data. What I would recommend is to update the data structure. We currently store an array of ids.
We can do it in 2 ways:

1. Array of objects -  just store all the objects. Arrays can get a bit slow when they get huge so i am a bit skeptical about this
2. Object of objects - Have an object where inside are objects with the key being the `item.id` and the value being the `item`. This is a pattern I have seen some frameworks use because its way more performant to access the data via the key, than having to use `.find` or `.filter` inside the array. This is my preferred option on how to handle it.  The type of the collection will be something like this: 
```ts
type Item = Asset | Kit | TeamMember | ....
type ItemsCollection = Record<Item['id'], Item>
``` 

I am curious to hear your opinion.

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira this is all implemented and release. 
@jurrejansen can you please test the feedback points you gave and if there is any problem please re-open this issue.

**Comment by jurrejansen** [comment]
@DonKoko I was running through these to do quick tests. And I experienced an issue with bulk cancelling bookings. After loading for quite a while...

- [ ] I tried cancelling 2 Reserved bookings which resulted in an error. However I do receive automated emails saying the bookings were cancelled
![Screenshot 2024-07-15 at 11 06 35](https://github.com/user-attachments/assets/6483c76a-6f62-4b0b-9983-322455d062ed)
![Screenshot 2024-07-15 at 11 08 41](https://github.com/user-attachments/assets/928bc8ec-4cb4-48ef-98cf-d96511982f6e)

After checking out 1 of the bookings and trying again to bulk cancel it worked
https://github.com/user-attachments/assets/8b7c7856-66f7-4592-b7d1-c389058ec404

**Comment by DonKoko** [comment]
@jurrejansen was this in production or on staging? Do I understand correctly that you received the email for both bookings but only the status of 1 of them got changed?

**Comment by jurrejansen** [comment]
@DonKoko this was on app.shelf
> Bulk selected 2 bookings with Rerserved status
> Performed Cancel bulk action
> Got error but received automated mail for both booking saying they were cancelled
> Refreshed page
> Checked out 1 of 2 bookings
> Bulk selected both bookings
> Performed cancel bulk actions
> Both bookings got cancelled and received automated mails saying they were cancelled again

**Comment by DonKoko** [comment]
@rockingrohit9639 I also found an issue:
I have filtered by in-custody and I have 2 pages. When I click select all the button is disabled, but that is not correct because actually all assets are in custody


![Image](https://github.com/user-attachments/assets/8b53f2fb-e774-48fd-ac9b-d690048961fc)

**Comment by carlosvirreira** [comment]
Things to consider / add:

- Batch updating GPS location (Can be handy if you batch selected assets and moved them to a new location) then you might want to do 1 mass GPS update for the selection 
- Batch updating GPS location could be included on a location level / kit / and batch selection of assets
