### ISSUE TITLE
[Feature request]: Store last logged in on our user table

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1121]
### Is your feature request related to a problem? Please describe?

This way I can know (for mailings) to segment to our most active users. 

### Describe the solution you'd like

We can use this to also send mails to users that are inactive to log to their workspaces or we close their accounts. Keeps us more on the ball and not looking at vanity metrics or sending mails to mails that will bounce.

**Comment by DonKoko** [comment]
Hey @carlosvirreira. We already have that info, however its not in the users table. I will call u to give you more info.
