### ISSUE TITLE
[Feature request]: Improve Activity (Changes) automatic logging

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1135]
### Is your feature request related to a problem? Please describe?

I have given custody of one asset to my colleague by assigning him a whole kit. 

When I go to the audit/activity tab I see an entry that reflects the action, but does not reflect the method which I used. 

'User has given User custody over Asset' 

<img width="2419" alt="Screenshot 2024-07-05 at 14 05 39" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/199b9c6c-4750-4dcb-bbf5-aa3e3fb0c6f4">

### Describe the solution you'd like

'User has given User custody ver Asset via Kit Assignment (Kit name).'

Much better. I can click the Kit and see it too.

**Comment by DonKoko** [comment]
@carlosvirreira this is merged. Works both for singular and bulk actions. Both for assign and release custody.
