### ISSUE TITLE
Get app production ready

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#114]
To launch v1 we need to get the app production ready. Here is a list we need to go through. 

## Server
- [x] setup production server
- [x] Setup production DB
- [x] Setup mail verification for users registering
- [ ] Emails adjustments
- [x] Setup DB backups
- [x] Custom smtp on supabase

# App
- [x] Error handling - #37 
- [x] Rename 'items' to 'assets'
- [x] add clarity
- [x] add metronome.sh

**Comment by DonKoko** [comment]
Custom SMTP mailer on production supabase is added, so emails for passwords and registering will now come from no-reply@shelf.nu

**Comment by DonKoko** [comment]
We need to decide weather we want to adjust the auth emails from supabase further than I have. I already changed them a bit but maybe you guys have suggestions how to make them better.

## Confirm signup 

```html
<h2>Confirm your signup</h2>
<p> We're thrilled to have you on the Shelf ecosystem.</p>
<br>
<p></p><p>Follow this link to confirm your user:</p>
<p><a href="{{ .ConfirmationURL }}">Confirm your mail</a></p>
```


## Magic link 

```html
<h2>Magic Link</h2>
<br>
<p>Follow this link to login to Shelf:</p>
<p><a href="{{ .ConfirmationURL }}">Log In</a></p>
```


## Reset password
```html
<h2>Reset Password</h2>
<p>You've made a password reset request.</p>
<br>
<p>Follow this link to reset the password for your user:</p>
<p><a href="{{ .ConfirmationURL }}">Reset Password</a></p>
```

For the DB backups, I will set them up once we go live as we need to upgrade to paid plan before we do it.
As for the email confirmation, I am working on something now. Will let you know if

**Comment by jurrejansen** [comment]
@DonKoko regarding the 'Mail adjustments'. I reviewed the texts in the designs and made some adjustments. They should work like this. Let me know if there's anything that doesn't check out.

https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?type=design&node-id=5511-341179

**Comment by carlosvirreira** [comment]
Can this issue be closed @DonKoko ?
