### ISSUE TITLE
Too many buttons on asset page

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#115]
Okey, so I am having this thing, that I feel like we are having too many buttons here
<img width="1354" alt="Screenshot 2023-05-15 at 17 09 05" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/ed130932-a292-401e-b494-b21d301d74ce">

My suggestion would be to just leave the QR button visible and put the edit/delete in a dropdown. What do you think?

**Comment by carlosvirreira** [comment]
@jurrejansen I really like it. However, I think that the QR code it might not be as clear for us as for other less savvy people. Could you please add 'View QR Code' or 'QR Code' I think then it will be 100% clear.

**Comment by DonKoko** [comment]
This is ready for testing @carlosvirreira @jurrejansen

**Comment by jurrejansen** [comment]
works fine on my end, closing
