### ISSUE TITLE
Style Toast on mobile

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#116]
We have a component called Toast that shows notifications.
On mobile it is not placed in the correct place. @hunar1312 could you please solve it?

**Comment by hunar1312** [comment]
Okay @DonKoko. Will work on this first.

**Comment by DonKoko** [comment]
@hunar1312 thanks man.

**Comment by hunar1312** [comment]
#120 will solve your issue @DonKoko 

Also, I've fixed some more UI breaks on mobile that I noticed.
