### ISSUE TITLE
[Improvement request]: Improve front-end of Asset page

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#1175]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

The improved asset page is working nicely but the front-end of a bunch of elements could use some work.

### Fields

- [x] The tables used for Default fields and Custom field have an unnecessary bottom border probably caused by the bottom border of the bottom row
![Screenshot 2024-07-16 at 15 09 09](https://github.com/user-attachments/assets/136ddb1e-8764-4fb7-abd4-3ecf38e25c83)

- [x] Value can be presented in Text instead of a Badge
![Screenshot 2024-07-16 at 15 13 27](https://github.com/user-attachments/assets/7fe6f828-698d-4483-b462-f06d3d378bed)

- [x] Unnecessary padding inside the Value row
![Screenshot 2024-07-16 at 15 13 05](https://github.com/user-attachments/assets/54372e84-3ed3-4446-a2b4-84891a0bc3e7)

- [x] [Mobile] Table element that contains the fields should be full width of the screen
- [x] [Mobile] Field labels and values should be vertically stacked
- [x] [Mobile] Field labels should be font-size 12px
![Screenshot 2024-07-16 at 15 14 56](https://github.com/user-attachments/assets/dbcb7fc2-b351-42ce-a225-5f3dadc7ffc2)

### QR 

- [x] Contain QR code and Buttons inside a single element. Background-color of parent element should be White
![Screenshot 2024-07-16 at 15 19 26](https://github.com/user-attachments/assets/a1020974-911e-4c89-abad-4c708f670aa9)

### Map

- [x] Improve front-end "Unscanned" state of Map element
![Screenshot 2024-07-16 at 15 21 04](https://github.com/user-attachments/assets/8be05986-2664-414b-a934-fdf1dc78bae5)

- [x] Improve front-end "scanned" state of Map element
![Screenshot 2024-07-16 at 15 21 54](https://github.com/user-attachments/assets/f3531a53-00a8-4c69-a634-2c6a94ae4975)

**Comment by DonKoko** [comment]
@jurrejansen good improvements. Only thing is that I don't want to use the google maps icon. Can we pick another one? Also you need to provide the image file.
I can then make a bounty for this issue.

**Comment by Bhavyajain21** [comment]
@DonKoko , Can I be assigned on this?

**Comment by DonKoko** [comment]
@Bhavyajain21 assigned and added to Roadmap project. Please move it to in-progress column when you start working on it.

**Comment by Bhavyajain21** [comment]
Sure @DonKoko

**Comment by jurrejansen** [comment]
Hi @Bhavyajain21 @DonKoko here's the alternative icon that can be used for the empty map element.

![map-02](https://github.com/user-attachments/assets/a2241a5e-8cb6-4609-afed-5558cdd1db6e)
![map-02](https://github.com/user-attachments/assets/d85527a3-175a-4cf8-b7c5-658740206f39)

**Comment by jurrejansen** [comment]
Hi @Bhavyajain21 thanks for all the improvements. I have a few points of feedback that you could look into.

- [ ] I am using a 16px left / right and 12px top / bottom padding logic for most of the UI elements and containers. Would be great if you can implement that logic for the UI element down below.

![Screenshot 2024-07-22 at 10 16 57](https://github.com/user-attachments/assets/95f52b4b-77c7-467b-a590-28219e7ec4c3)

- [ ] Could you apply these font styling to the text used in the map UI element. Also for the container of the button use the 16px left / right and 12px top / bottom padding. #101828 #475467

![Screenshot 2024-07-22 at 10 19 44](https://github.com/user-attachments/assets/d27cc39b-a2ad-4695-8f61-ff1279fd4742)

**Comment by Bhavyajain21** [comment]
Sure @jurrejansen , will work on these changes.

**Comment by jurrejansen** [comment]
@Bhavyajain21 Thanks, spotted another thing

- [ ] Custody UI element doesn't have a border
![Screenshot 2024-07-23 at 09 59 07](https://github.com/user-attachments/assets/88dba917-0a2b-463a-b6e3-fdb3770a301b)
![Screenshot 2024-07-23 at 09 58 21](https://github.com/user-attachments/assets/08da841b-c734-4a81-890f-f7a1024c9fe3)

**Comment by DonKoko** [comment]
@jurrejansen thanks man. I have resolved those and am deploying it now: https://github.com/Shelf-nu/shelf.nu/actions/runs/10056071951
