### ISSUE TITLE
[Bug]: I've set up a custom field of type Date, and when viewing an asset with this field set, it always shows one day earlier than I entered. 

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1184]
### What happened?

I've set up a custom field of type Date, and when viewing an asset with this field set, it always shows one day earlier than I entered. When re-entering Edit mode, the original correct date still shows there.

![wrong-date-view-mode](https://github.com/user-attachments/assets/e8236447-b4d8-4849-95a6-0760c39f73bf)

![wrong-date-edit-mode](https://github.com/user-attachments/assets/efcf63b1-c60c-49c1-a463-3eb113f4b190)

### What is the expected behaviour?

Show correct date

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
Can you take a look please @rockingrohit9639 .
It is something with timezones. I think either of the dates is not using them correctly. Make sure they both use the hints with timezone.

**Comment by rajeshj11** [comment]
@DonKoko I would like to work on this. can you please assign it to me
