### ISSUE TITLE
[Feature request]: Activity event when manually updating a GPS coordinate

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1200]
### Is your feature request related to a problem? Please describe?

I notice someone updated the GPS coordinate to the wrong place. I want to see who did that action and how.

### Describe the solution you'd like

IF manually updated or via scan add an entry in the asset activity including the user who performed the action.

**Comment by DonKoko** [comment]
Message for manual update: `${name} manually updated the GPS coordinates to ${gpsCoords}`

Message after scan: `${user} performed a scan of the asset QR code`

I am thinking of something like this in terms of messages. What do you think @carlosvirreira

**Comment by DonKoko** [comment]
@carlosvirreira this is being currently deployed.

**Comment by carlosvirreira** [comment]
Cool, can go to newsletter.
