### ISSUE TITLE
[Feature request]: Add PLN to list of currencies

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1201]
### Is your feature request related to a problem? Please describe?

Want to track inventory in PLN I have to pick another currency selector now

### Describe the solution you'd like

Use PLN to calculate my inventory value

**Comment by DonKoko** [comment]
@carlosvirreira this is being released. https://github.com/Shelf-nu/shelf.nu/actions/runs/10093294806

**Comment by carlosvirreira** [comment]
Thank you I inform the requester.
