### ISSUE TITLE
[Bug]: Search Persistent Filters

### ISSUE THREAD

**Issue by McMurdo42** [Shelf-nu/shelf.nu#1225]
### Contact Details

real.davidcoleman@gmail.com

### What happened?

Is most notable on phones.
Search for an asset then press the 'x' to clear the search bar. Only the assets from the last search will be shown. This is the same if any filter is applied.

### What is the expected behaviour?

When the search bar and all filters are cleared all assets should be visible.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by DonKoko** [comment]
Hi @McMurdo42. Thanks for reporting the issue. It will be looked at asap.

**Comment by DonKoko** [comment]
hello @McMurdo42 , the issue has been resolved. Thank you for reporting.
