### ISSUE TITLE
Feature: Add assets to existing booking from asset page

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#1245]
Currently its only possible to create a new booking via the asset page. 
We should allow users to add to existing booking as well.

**Comment by DonKoko** [comment]
@carlosvirreira can we make a design for this. I have already thought about it and have some ideas:

1. Button - i think it would be nice to add a button with multiple options on it. Similar to how github does it. 
![image](https://github.com/user-attachments/assets/10af6d43-4bc0-495b-b39f-aaf08dcdf6ff)
In this case the options would be: `Create new booking`  or  `Add to existing`
2. If you select add to existing, we need a modal where the user can select the booking and confirm. It can be a select and it should show only bookings that are in Draft or Reserved state, as those are the only states that allow adding an asset.

**Comment by carlosvirreira** [comment]
> @carlosvirreira can we make a design for this. I have already thought about it and have some ideas:
> 
> 1. Button - i think it would be nice to add a button with multiple options on it. Similar to how github does it.
>    ![image](https://private-user-images.githubusercontent.com/7840007/377030027-10af6d43-4bc0-495b-b39f-aaf08dcdf6ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODY0NDcsIm5iZiI6MTcyOTA4NjE0NywicGF0aCI6Ii83ODQwMDA3LzM3NzAzMDAyNy0xMGFmNmQ0My00YmMwLTQ5NWItYjM5Zi1hYWYwOGRjZGY2ZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTZUMTM0MjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGM4MTRkZjUzYzE4YmJkNjlkOGVkMWQwY2U0N2YzNDgxMzhlOTkwZjkyYjE4MGE2MzJiYTc0ZTE0ZTI1NWRhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Wxjw9gYO-3tZ6yB_nLDih-IPawYFlO8lcjqf9EERz5Q)
>    In this case the options would be: `Create new booking`  or  `Add to existing`
> 2. If you select add to existing, we need a modal where the user can select the booking and confirm. It can be a select and it should show only bookings that are in Draft or Reserved state, as those are the only states that allow adding an asset.

This is awesome. Of course we should have it. Let me make a component.

**Comment by carlosvirreira** [comment]
@DonKoko design suggestions. 

Modify the book assets into a combo button with a dropdown. The 'Book asset' just goes to the normal step (create new booking) > dropdown reveals the other option. 

If I mis-interpreted your intention let me know. I am not sure if you were looking for this. 

![Screenshot 2024-10-16 at 18 16 15](https://github.com/user-attachments/assets/32896b2b-8841-4494-a4de-9a792ff91a7c)

Then, expanded dropdown to reveal the booking name and details (start date/time and end date/time)


If you select on 'Add to existing booking' we can show this modified pop-up component we have incorporating the elements. 

![Screenshot 2024-10-16 at 18 18 43](https://github.com/user-attachments/assets/a1990e2b-bf8b-41ab-ab0d-ea7ac52a12e1)

**Comment by DonKoko** [comment]
@carlosvirreira yes, i think the designs are good. Thanks for taking care of it.

@rajeshj11 can you check the designs. Is it clear what the flow is? Keep in mind we dont have support for the button with the multiple possible actions. We have a few components that can be combined to do it. If you decide to take this issue we can discuss on discord how exactly to build it.

**Comment by rajeshj11** [comment]
@DonKoko I got it what needs to be done for this issue? please ping me the details.

I believe the designs mentioned above are sufficient to begin work. However, one design is missing—the post-confirmation process isn't included. I assume we should display bookings similarly to how assets are shown when we click "Manage Assets" in the booking section.
