### ISSUE TITLE
'Questions / Feedback' element in expanded sidebar

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#125]
@carlosvirreira how do you imagine this? Will a lil chat open up in bottom right corner like on marketing site, or will a new tab open in Crisp environment. Got a few options:

OPTION I

![Index _ Default](https://github.com/Shelf-nu/shelf.nu/assets/76112272/c4c77944-bcdf-422f-8f69-c6afeb0721fa)

OPTION II

![Index _ Default](https://github.com/Shelf-nu/shelf.nu/assets/76112272/7e44b09d-a690-44d4-a821-7c3f7f858f98)

OPTION III
We could also just go with the Crisp icon in bottom right corner. Instead of the designs above.

---

- [ ] Find a better image

**Comment by DonKoko** [comment]
I actually like both. I think we can use the first one by default and once its dismissed, just show the menu item.
We specifically decided we dont want to have a crisp icon in the footer as it just clutters the view and we dont need it to follow you there all the time.

**Comment by carlosvirreira** [comment]
If we do not further iterate this @DonKoko can we assign this to @hunar1312 ?

**Comment by DonKoko** [comment]
@carlosvirreira at the moment he is busy with kh-client-area so I will just add it myself. Can you send me the login to crisp via email so I can check their docs and get the code I need to add this. Thanks

**Comment by carlosvirreira** [comment]
hi @DonKoko you should have mail about this

![Screenshot 2023-05-24 at 14 10 38](https://github.com/Shelf-nu/shelf.nu/assets/12449255/fc73a951-6e18-4c53-b239-0feb76606690)

**Comment by DonKoko** [comment]
This is deployed and ready for testing.

**Comment by jurrejansen** [comment]
Seems to work fine, I sent a chat. So if that comes in we should be good @carlosvirreira

**Comment by DonKoko** [comment]
thanks @jurrejansen. I can also confirm it comes in. Closing this issue.
