### ISSUE TITLE
[Bug]: Plus plan (yearly) not showing on pricing tables (in app)

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1280]
### What happened?

User wanted to sign up (yearly - plus) but could not find the place to do so. Only monthly is available. Sent a payment link for it manually.

### What is the expected behaviour?

Show the tier on pricing page.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by DonKoko** [comment]
@carlosvirreira Resolved. Thanks for reporting.

**Comment by carlosvirreira** [comment]
👍🏿
