### ISSUE TITLE
[Bug]: Custodies shown on team tab behaviour

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1281]
### What happened?

![Screenshot 2024-08-27 at 11 41 57](https://github.com/user-attachments/assets/beaa4ded-ade1-4940-94e9-07b791cf2a54)

In the screenshot above. Jurre shows 24 assets under custody. However, when opening the profile you see 0.

I believe that our count is also considering other custody statuses that are not clear.

### What is the expected behaviour?

Show all active asset custodies per user

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by DonKoko** [comment]
@carlosvirreira resolved. Deploying now. Was a wrong query.
