### ISSUE TITLE
Implement tailwind theme

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#13]
To ensure a consistent style around the website, we need to implement a out tailwind theming based on the figma designs.
We will start with some basic elements that are required for building the UI and build on top of that.

- [x] Colors - including all variations. Follow untitled UI
- [x] Buttons
- [x] Spacing
- [x] Typography
- [x] Shadows

**Comment by DonKoko** [comment]
Based on our discussion yesterday I have implemented the following sizes for headings:

```
Display 2xl = H1
Display xl = H2
Display lg = H3
Display md = H4
Display sm = H5
Display xs = H6
```

This however seems inconsistent with the design of the app. 
If I look at the biggest heading on the page, based on basic HTML semantics and structure that should be an H1. However when I look at it it uses `display-sm` which above is defined for H5. 

![Image](https://user-images.githubusercontent.com/7840007/224270777-640d6241-3281-447d-8987-566a0a6e0c87.png)

At this point I am confused what to do. I will override the default styles we defined, however I am concerned that in the future that will cause a domino effect when updating the UI.

**Comment by DonKoko** [comment]
@carlosvirreira I have implemented the primary button color based on the new design you made on friday. What I am missing or I simply dont know how to see are hover/focus states of the buttons.
Also it would be good to know what the transitions are on the hover states.

**Comment by carlosvirreira** [comment]
Hi @DonKoko 

Our buttons have 4 states.

1) Default 
2) Hover 
3) Focused 
4) Disabled

![Screenshot 2023-03-13 at 09 57 17](https://user-images.githubusercontent.com/12449255/224653440-35d2c30c-93b7-4354-89b4-fdee9d363b57.png)

For the example above: 

1) Default  -  background = base/white | border (inside) 1px - gray 300 | (drop shadow) Shadow / XS (blur = 2 / Y = 1) 101828 (5% opacity)
2) Hover - background = gray 50| border (inside) 1px - gray 300 | (drop shadow) Shadow / XS (blur = 2 / Y = 1) 101828 (5% opacity)
3) Focused -   base/white | border (inside) 1px - gray 300 | (drop shadow) Shadow / XS focused 4px - gray 100 (blur = 2 / Y = 1) 101828 (5% opacity) + F2F4F7 - spread 4 (199% opacity)
4) Disabled -

**Comment by DonKoko** [comment]
This is done for now.
