### ISSUE TITLE
Feat: PWA install prompt

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#1302]
Prompt users to install PWA when visiting shelf on mobile.

**Comment by carlosvirreira** [comment]
After doing tons of research here. It seems like almost no app is doing a popup prompt for users. 

I like the @rphlmr approach the most. Show after sign up + also via the notice popup we have. Both can be dismissed. 

On the marketing website I will make a page for it too.

**Comment by carlosvirreira** [comment]
![Screenshot 2024-09-05 at 14 21 33](https://github.com/user-attachments/assets/3a234dc6-c149-485b-81f9-ba0c95248b97)

Desktop: Let's use the component we have for notices for this purpose. The black box will be a gif showing how to install on mobile. Full tutorial will send to this page: https://www.shelf.nu/blog/new-shelf-pwa-progresive-web-application-live-learn-how-to-use

Mobile: I would add it to the landing page after signup (Asset Index) / message can be dismissed
![Screenshot 2024-09-05 at 15 42 06](https://github.com/user-attachments/assets/78a87f8e-ebf2-4bf0-a9ca-03e3ba1a9074)


Dashboard: Using the existing notices component we will also promote the message and URL to marketing site.


On mobile menu (if they click skip): 
![Screenshot 2024-09-05 at 15 52 31](https://github.com/user-attachments/assets/1eec99c1-0aea-4565-a2ba-c646bcaef34f)

**Comment by DonKoko** [comment]
> Desktop: Let's use the component we have for notices for this purpose. The black box will be a gif showing how to install on mobile. Full tutorial will send to this page: https://www.shelf.nu/blog/new-shelf-pwa-progresive-web-application-live-learn-how-to-use

This component we already have so nothing new to develop here. We just need to change the content. Also would be good to change the cookie name so even people who dismissed it already can still see it.


> Mobile: I would add it to the landing page after signup (Asset Index) / message can be dismissed

Okey so a few things here. I like the design and general visual approach but I have some feedback.
Doing it after sign-up I dont think is enough. Users could sign up via desktop and open it later via mobile. Also there could be long existing users who also should be informed about it.
