### ISSUE TITLE
[Feature request]:  Export filtered lists

### ISSUE THREAD

**Issue by Joedon3** [Shelf-nu/shelf.nu#1324]
### Contact Details

joedon3@gmail.com

### Is your feature request related to a problem? Please describe?

Filtering and viewing assets works well, but If I need information on a subset of all my assets I would need to export all of them and manually filter.

### Describe the solution you'd like

On the asset list page, allow for the export of the filtered results on that page.

### Additional context

This would be very useful for working with insurance companies, allowing users to export their own asset information, and many more.

**Comment by DonKoko** [comment]
Hey Joe,

thanks for the suggestion. We are currently working on an advanced view of the index, which will have this as well and many more features.

**Comment by DonKoko** [comment]
hey @Joedon3 . This is now available via the export feature on the advanced index.
