### ISSUE TITLE
[Feature request]: Revert to Draft State

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1334]
### Is your feature request related to a problem? Please describe?

My clients sometimes add the wrong dates on a reservation, I want to be able to revert to a 'draft' state.

### Describe the solution you'd like

Revert a booking from a ‘**reserved**’ state to => ‘**draft**’ state. On the draft state, your team can then modify dates/comments/assets that your client has entered. 

1. The action should be within the actions dropdown of the booking
2. The action should only be possible, if the current state of the booking is RESERVED
3. Should be available for ADMIN , OWNER & SELF_SERVICE - you might need to add a special permission action for the booking permission entity
4. It should have a confirmation screen: 

```md
## Reverting to draft state
Are you sure you want to revert this booking back to draft?
```

### Describe alternatives you've considered

Response " that sounds like a fine fix! It would be intuitive for my team to just set it back to draft, change the dates, then reserve it again. Please proceed and thanks so much for the swift response."

**Comment by DonKoko** [comment]
@rockingrohit9639 this can be worked on. Please lmk if there are any questions and move this to "in progress" when you start. Thanks

**Comment by carlosvirreira** [comment]
I have tested this on testapp (mobile/desktop) and it works as expected. I am glad that we do not send a mail when a booking goes back to draft. It would have been too much. This can be released to live and to Rise workspace as well.
