### ISSUE TITLE
[Feature request]: Support marking assets as non bookable via CSV import

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1341]
### Is your feature request related to a problem? Please describe?

We are importing a large set of assets, we want to mark some as not bookable via import

### Describe the solution you'd like

Perhaps a column we can add to the import with bookable yes/no

**Comment by DonKoko** [comment]
This should be pretty straightforward to implement. Its a base asset field so it can be easy to add. 
Here is what needs to be done;

- [ ] Update the import template with a column "Available to book". I would say for user friendliness the values should be `"yes" || "no"`
- [ ] Update the import parser to make sure that this field's value is getting properly extracted from the csv
- [ ] Import the function that creates assets to make sure the value is being properly set to `true` or `false` based on the csv value.

**Comment by DonKoko** [comment]
@carlosvirreira this is done and merged. Currently deploying.
