### ISSUE TITLE
[Feature request]: Improvement to Calendar View

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1350]
### Is your feature request related to a problem? Please describe?

I use the calendar a lot and I want some changes made to improve quality of life using shelf.

### Describe the solution you'd like

As a quality of life improvement it would be great to have an option to scale calendar view to see more data on the grid. Maybe toggle different views like WEEK, MONTH, DAY. It would significantly improve our workflow.

Also the calendar landscape view on my iphone is a bit glitchy .. sometimes it just does not switch from list view to calendar view.

**Comment by Bhavyajain21** [comment]
> > Also the calendar landscape view on my iphone is a bit glitchy .. sometimes it just does not switch from list view to calendar view.
> 
> It shouldn't by design tbh. When we made it we wanted that mobile is always list mode. If it switches to calendar on landscape that is rather a bug.
> 
> > As a quality of life improvement it would be great to have an option to scale calendar view to see more data on the grid.
> 
> This thing I dont understand. Do you have some examples what you mean by scale the calendar view?
> 
> > Maybe toggle different views like WEEK, MONTH, DAY. It would significantly improve our workflow.
> 
> The week and day views we can do easily. Month we already have.
> 
> @Bhavyajain21 I remember you worked on some front-end but not sure if you also did the backend. Would you be interested in implementing the Week and Day view? They are plugins to add and I think with how we are using the FullCalendar with the events api, they should work pretty easy. We will need to style them after they are enabled. You can also always write me on discord if you have questions.

Sure @DonKoko , I can work on it. I did not work on the backend before.

**Comment by DonKoko** [comment]
@Bhavyajain21 I dont think there is any backend needed but we can confirm that as soon as you start working on it. If there is needed I can jump in to help. Lets start by adding the buttons and installing the plugins and we can then see if we need to update the backend.

**Comment by Bhavyajain21** [comment]
Sure @DonKoko , I am on it. Please assign!

**Comment by Bhavyajain21** [comment]
Do we have any designs for the same?

**Comment by DonKoko** [comment]
hey @Bhavyajain21 for the buttons for switching view, just place them next to the date pagination. I will review it after that and change it. For the rest the views should be the same as in the original FullCalendar view, just styled in our style and with our popover component. I don't forsee much issues with this, but if you want to discuss something, I am available on discord.
