### ISSUE TITLE
[Bug]: Front end alignment issues

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1352]
### What happened?

Text overflowing when long kit name

![Screenshot 2024-10-15 at 17 27 49](https://github.com/user-attachments/assets/ade8f27e-c509-49d7-84c3-1c60b0c30c5d)

On asset page
![Screenshot 2024-10-15 at 17 29 12](https://github.com/user-attachments/assets/60d74341-6038-4ce1-9eaa-2b030a8bf0b5)

### What is the expected behaviour?

If text is too large for container area, fine to add (....)

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by rajeshj11** [comment]
@DonKoko can i work on this issue.
