### ISSUE TITLE
[Feature request]: Accordion support for visualising kits on booking view  

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1368]
### Is your feature request related to a problem? Please describe?

We heavily use kits for bookings. We do this for overviewing our booked assets. At the moment, when we add several kits our visualisation gets long and we would prefer to see the kit added and be able to compact it / collapse it on demand. 

This is not applicable for the PDF generation. There the visual is good. 

### Describe the solution you'd like

![Screenshot 2024-10-24 at 12 20 56](https://github.com/user-attachments/assets/3b2f149a-e77f-4352-a5e8-ce1039d2ce96)

**Comment by vikashsprem** [comment]
Hey @carlosvirreira, Do we need to add a collapse button here at every kit in the table? Please confirm.

<img width="1434" alt="Screenshot 2024-10-24 at 6 01 05 PM" src="https://github.com/user-attachments/assets/d7f03b43-3955-4de6-a620-cb10fa373a3f">

**Comment by carlosvirreira** [comment]
hi @vikashsprem for this bounty it will be in the context of bookings. So, you will have to make a team workspace for this.
