### ISSUE TITLE
Purpose of Admin account and how to use it ?

### ISSUE THREAD

**Issue by sochartetu** [Shelf-nu/shelf.nu#1371]
### What happened?

So, there are several env. variables about admin account.
It's only stated that it is the email used to get in touch with an admin when a trouble happens on the website.
But, somewhere else in the doc, it's mentionned we are supposed to login with the admin creds. But, of course, it does not work and I get an error that the account does not exist.

So, what is the purpose of all those variables if it's only used as a contact ?
How am I supposed to login with the creds related to this account ?

### What is the expected behaviour?

Being able to use the account

### Version

Self-hosted

### What browsers are you seeing the problem on?

Firefox

**Comment by DonKoko** [comment]
Hey @sochartetu . 


>So, there are several env. variables about admin account.
It's only stated that it is the email used to get in touch with an admin when a trouble happens on the website.
 But, somewhere else in the doc, it's mentionned we are supposed to login with the admin creds. But, of course, it does not work and I get an error that the account does not exist.


I am not sure which variable you are referring to but the only one mentioning admin in .env.example is this one:
```.env
# Used for sending emails to admins for stuff like Request user delete. Optional. Defaults to support@shelf.nu
ADMIN_EMAIL="support@shelf.nu"
```

This is meant for when a user wants to be deleted, they can send a request to the super admin of shelf.
As for your second question, to make a user be a super admin you need to manually add an entry in `RoleToUser` for the user who you want to be super admin. If you feel like there are any mistakes in the documentation or anything not clear, feel free to open an issue & PR which clearly explains the problem with the docs and what your suggestions.

>So, what is the purpose of all those variables if it's only used as a contact ?

Let me know which other variables you are referring to. The purpose of the ADMIN_EMAIL is to change who those requests are sent to. If you are self hosting shelf, i can assume you dont want delete requests to go to support@shelf.nu

**Comment by sochartetu** [comment]
From your documentation, I am not dreaming:
![image](https://github.com/user-attachments/assets/7505f7ca-58d2-4387-90da-7042054b68bd)

**Comment by DonKoko** [comment]
To answer your question, they don't have a purpose. Those were used before but anymore and we forgot to remove them from the `env.ts` file, however I didn't see any mentions in the documentation about them and they were not used anywhere. 
For the most up-to-date information, please use the docs and `.env.example`.

The variables have been removed from `env.ts`: #1379
