### ISSUE TITLE
[Bug]: Search not working if pagination > 1

### ISSUE THREAD

**Issue by apvlv** [Shelf-nu/shelf.nu#1372]
### What happened?

Steps to reproduce:

1. Go to 'Assets page'
2. Click on eg. 'Page 2'
3. Try to search for a term
4. See "No assets found"

### What is the expected behaviour?

Search should work on any page index

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
Has been resolved. Thanks for reporting.
