### ISSUE TITLE
[Bug]: Modify Category Assignment for Custom Field

### ISSUE THREAD

**Issue by DroneProf** [Shelf-nu/shelf.nu#1373]
### Contact Details

rose196@purdue.edu

### What happened?

Steps to reproduce:

1. Go to Settings>Custom Fields>Edit
2. Toggle 'Use for select categories' OR modify category from dropdown menu.
3. Click 'Save'
4. Custom Field category does not update.

### What is the expected behaviour?

Expect Category assignments for custom fields to update.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by DonKoko** [comment]
hey @DroneProf . I am not able to reproduce your issue. Can you give me a few more details so I can look further into it:

1. What is the field type?
2. How many categories is it linked to?
3. What is the field ID? (you can see it in the browser url)

**Comment by DroneProf** [comment]
Hey @DonKoko . Thanks for checking in!

Here's a gif of the issue. ![shelf_category](https://github.com/user-attachments/assets/9eed5fe0-99fd-422f-b953-c12578429043)
Field ID: cm2dr9fhc00km13caut7lofw9
