### ISSUE TITLE
Update basic UI with implementing optimistic UI

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#138]
We have certain views and actions where optimistic UI will work very good so we should implement it to provide a better UX to users.
- [x] Adding notes
- [ ] Creating categories

**Comment by DonKoko** [comment]
hey @hunar1312 . I would like you to understand the concept of optimistic ui and how it works in remix and implement it here. It's a front end task but it requires some minor understanding on how the backend works. 
Here are some videos explaining it:
- https://www.youtube.com/watch?v=EdB_nj01C80
- https://www.youtube.com/watch?v=TR_wn2y-SYQ

**Comment by hunar1312** [comment]
Thabk you for the references, I'll get started on this after understanding the concepts

**Comment by DonKoko** [comment]
Creating categories is not needed. The rest is done.
