### ISSUE TITLE
[Feature request]: Standard sorting for custom fields

### ISSUE THREAD

**Issue by DroneProf** [Shelf-nu/shelf.nu#1385]
### Contact Details

rose196@purdue.edu

### Is your feature request related to a problem? Please describe?

Custom field ordering on assets are not consistent between similar assets. See the screenshot below of three similar assets containing similar information, but without consistency between custom field ordering. 

![screenshot](https://github.com/user-attachments/assets/3eaca0f3-4f81-4b10-8de2-66ba69921249)

 

### Describe the solution you'd like

Sort by alphabetical as a default.

**Comment by DonKoko** [comment]
Hey Nathan, you are correct. This is something we overlooked but can be easily adjusted. I am wondering, what order would you expect? I think only alphabetical makes sense. What do you think?

**Comment by DroneProf** [comment]
Hi @DonKoko , I agree - alphabetical sounds most logical to me.

I appreciate your fix/update. A consistent ordering will make asset spot checks much easier.
