### ISSUE TITLE
[Feature request]: Searchable and Ordered Custodian in (Admin) Bookings

### ISSUE THREAD

**Issue by DroneProf** [Shelf-nu/shelf.nu#1386]
### Contact Details

rose196@purdue.edu

### Is your feature request related to a problem? Please describe?

Administrators who are creating bookings can not search for custodians (other than by typing the first few letters of their name. Additionally, the list of available custodians is no alphabetical by default. 

[booking.pdf](https://github.com/user-attachments/files/17609456/booking.pdf)

### Describe the solution you'd like

Custodian box in "Create new booking" prompt should default to a textbox ready to search.

**Comment by DonKoko** [comment]
hey @DroneProf . This has been released yesterday. Thanks for the suggestion. We already have a component that allows to search team members, we just didn't catch up yet with implementing it for this use case.
Also I made sure the order is:
- Users
- NRM

Both ordered alphabetically.
