### ISSUE TITLE
App.shelf.nu - Chat Sidebar/Help Sidebar

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#140]
On Safari, it shows a double scroll bar and when closing it - It behaves weirdly.

https://github.com/Shelf-nu/shelf.nu/assets/12449255/99da9eca-30a6-4b16-9ef8-54c1eef06c08

**Comment by jurrejansen** [comment]
@DonKoko @carlosvirreira hmm yeah indeed, missed that. I'm not experiencing the scrollbars when modal is active. No problem in expanded state on both safari and chrome but:

- [ ] When modal is active the responsivess is broken when sidebar collapses

https://github.com/Shelf-nu/shelf.nu/assets/76112272/45d9e1c6-3e5d-4534-8c1b-f569524d7f07

- [ ] When modal is closed the "Questions / Feedback" icon disappears when sidebar collapses. Should behave the same as the "Settings"

https://github.com/Shelf-nu/shelf.nu/assets/76112272/72e80252-81be-4fcb-b45f-07552ff52d5e

**Comment by carlosvirreira** [comment]
After our conversation @DonKoko here is a new iteration/proposal for sidebar. That should help with the UX annoyances you had.

![Screenshot 2023-05-31 at 12 54 33](https://github.com/Shelf-nu/shelf.nu/assets/12449255/14313fa7-c19e-4f69-86fb-61cec67c7c62)

**Comment by DonKoko** [comment]
The bugs with the sidebard scroll bars are fixed. 
The design from above doesn't really work. In th example its over a very dark bg so it looks okey, but when implementing it it looks pretty terrible and doesnt really align well with the breadcrumbs and so on.
For now I have disabled the fold/unfold functionality until we have a good solution.

**Comment by DonKoko** [comment]
@carlosvirreira @jurrejansen this seems good now. Closing the issue.
