### ISSUE TITLE
V1.1 - Most important feature

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#141]
I think that the most valuable feature after launch is to allow for custom fields. This way, our users can create their own logic on the app. What do you think @jurrejansen

**Comment by carlosvirreira** [comment]
can you share some screenshots of what you were cooking on this topic @jurrejansen ?

**Comment by jurrejansen** [comment]
@carlosvirreira a lil start here https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?type=design&node-id=6683-336967

**Comment by jurrejansen** [comment]
Closing this as we have a new issue: https://github.com/Shelf-nu/shelf.nu/issues/307
