### ISSUE TITLE
'Reset password' and other automated mails not working or inconsistent

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#142]
APP.SHELF

- I'm not being logged out after clicking the reset link
- I am not receiving en email with 'password reset' link

I am experiencing inconsistent behaviour with the automated emails. Almost created an easy earlier when i wasn't receiving magic link to login. And then they (multiple attempts) all came in at the same time 20 minutes later from my first attempt.

May need to do some more testing, but documenting there are some issues.

EDIT

![Screenshot 2023-06-01 at 10 47 49](https://github.com/Shelf-nu/shelf.nu/assets/76112272/f6e47507-8e94-415b-8d71-2984095c27e2)

TESTAPP.SHELF

On testapp emails are being sent, but with password reset im getting 'invalid refresh token'

![Screenshot 2023-06-01 at 10 51 31](https://github.com/Shelf-nu/shelf.nu/assets/76112272/5b723774-d73c-4b75-90b2-6740a778833a)

**Comment by carlosvirreira** [comment]
For me on app.shelf.nu 

magic link also does not work.

Creating an account instantly logs me in, no confirm password in place.

**Comment by DonKoko** [comment]
Thanks for reporting guys. I am working on all those issues right now.

**Comment by DonKoko** [comment]
@jurrejansen btw the reason you were not receiving the emails is because the certificate on vimexx for mail.shelf.nu is broken and I had supabase setup so it uses our own smtp but that was failing because there was no valid cert. I disabled custom SMTP now and waiting for some support from vimexx to fix it.

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira Magic link is fixed as well. 
So we have 2 cases
- Signup with Magic Link - this will send an email with subject "Confirm your Signup". Once you click the link this will confirm your email and log you in
- Login with Magic Link  - this will send an email with subject "Your Magic Link". Clicking on the link will log you in.

**Comment by jurrejansen** [comment]
Tested again for good measure and had no issues, closing
