### ISSUE TITLE
[Feature request]: Advanced Index - Export Selection

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1435]
### Is your feature request related to a problem? Please describe?

Let's make this into a 'plus' benefit please. Let us disable the action as we do on import. 

### Describe the solution you'd like

Export selection is a power user feature and not a hobbyist feature. It should be available in Plus and higher plans.

**Comment by DonKoko** [comment]
Yeah thats a bug. Shouldnt happen. Fixing now.
