### ISSUE TITLE
Bug: Issue with display of items per page in pagination

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#1446]
A user reported about having some issues with pagination on the advanced index. Here is what he said:

> Set the assets per page to 100 and it works, set it back to 20 and it stays at 100 on the page though the dropdown still shows 20. If I set it to 50, it goes to 50. Try going to 20 from 50 and it sets it to 100 but shows 20 at the bottom.

![Image](https://github.com/user-attachments/assets/b586ff33-9716-462c-9e3e-74a8c1855924)

@rockingrohit9639 can you please take a look at this?

**Comment by DonKoko** [comment]
@carlosvirreira this is resolved. I dont remember who reported it tbh but I think its good to inform them.

**Comment by carlosvirreira** [comment]
I remember. Will inform.
