### ISSUE TITLE
[Feature request]: Form Asset Create / Edit - Updated Behaviour

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1447]
### Is your feature request related to a problem? Please describe?

As a facilities manager, I have to create a workflow for making an inventory of 1000s of assets. 

I will be using the help of not super technical colleagues. So I try to make the process as simple as possible. In my eyes, if they add the required fields from custom fields this is good. 

Currently on shelf the fields on asset create are grouped alphabetically. Ideally they are bundled on required/optional. 

### Describe the solution you'd like

Group the custom fields by required and optional on asset create/edit form.

![Group by required](https://github.com/user-attachments/assets/18b2dd72-4f14-4ddb-bdbd-91f6f7c8eeab)

**Comment by carlosvirreira** [comment]
@DonKoko bounty-able task or better wait to clear up a bit of dev resources to do this first time right?

**Comment by DonKoko** [comment]
Hey @vikashsprem @Bhavyajain21 . Both of you didn't really fully complete the issue. You had different approaches but missed the same points.

@vikashsprem bacause @Bhavyajain21 was first with his PR, I will accept his attempt. Thanks for trying to resolve this.

**Comment by carlosvirreira** [comment]
Congrats @Bhavyajain21
