### ISSUE TITLE
Improvement: Asset index pagination

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#1455]
- [x] Show current page
- [ ] Allow user to manually input page they want to go to

@carlosvirreira I want to make a bounty for this. Do you think we have some old design that has a current page display/selector and if not can we make a design for it.

**Comment by carlosvirreira** [comment]
I will look @DonKoko

**Comment by carlosvirreira** [comment]
![Pagination design 1](https://github.com/user-attachments/assets/17aef42e-6c2a-4acc-acf8-4eb44962a4c9)

In this design, the '20 rows' when clicked opens the same selector as we have for showing assets on current page/view.


@DonKoko

**Comment by DonKoko** [comment]
Okey I did that but without the input field, its still way better than what we had. I will deploy/release it.
