### ISSUE TITLE
[Bug]: Search bug (Android PWA)

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1471]
### What happened?

When searching (no additional filters applied) for the query "SN: " (note trailing space) on the mobile "app" on Android, I receive this error before I can type additional characters.

![Screenshot_20241130-125557](https://github.com/user-attachments/assets/6c52c853-7c45-4813-ba2a-41108778ab66)

### What is the expected behaviour?

Execute search query

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
@carlosvirreira has been resolved. The user who reported this can be informed.
