### ISSUE TITLE
[Bug]: Category Edit UX Issue - Potential Unintended Overwrites

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1480]
### What happened?

When editing multiple categories in succession, there's a potential UX issue that can lead to unintended overwrites of category information without warning.

**Current Behavior**

- User begins editing Category A (updates description)
- User leaves the edit modal without saving changes
- User starts editing Category B (clicks edit)
- The unsaved changes from Category A persist in the form
- When user clicks save, thinking they're saving Category A's changes:
   - Category B gets overwritten with Category A's information
   - No warning is displayed about potential data loss

### What is the expected behaviour?

**Expected Behavior**
Show a warning popup when switching between category edits with unsaved changes
Clear the form when switching between different categories
Alternatively, persist the correct category information for each edit modal

**Impact**
While this might be a minor inconvenience for users with few categories, it could cause significant issues for users managing large inventories with multiple detailed categories.
Suggested Solution
Consider implementing one or more of these safeguards:

Add a confirmation dialog when closing an edit modal with unsaved changes
Clear form data when opening a new category edit modal
Add a warning when saving changes if the category being edited has changed

**Additional Notes**
Severity: Low/Medium
Current workaround: Ensure to save or discard changes before editing another category

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
@carlosvirreira this is resolved. Nice find. Thanks for the issue.
