### ISSUE TITLE
User request: Location needs

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#150]
I wanted to offer some feedback on a few suggestions that I think may be beneficial user features:

1) on Assets - having a **LOCATION** field - being able to label where the asset is located; for example, Storage closet, Office, Home, Bedroom, Car, and others. Maybe when user adds these locations, it can should as a drop-down menu option. That way if location is changed, then user can easily select a different location. 

2) on Assets - even further into the location field, would be an option for **SUB-LOCATION.** For example, I may have a box that I have labeled as "BIN001" that is located in storage... Inside that box there may be several different items that I want to identify each as being in the same box.

3) IMPORT option - Maybe I have previously used excel or some other program (such as Duck Pack and Track) that I have a list of items already and want to import those into Shelf as a .csv file.

I hope you take these features into consideration. Or if it is already possible to perform something similar, please let me know.

**Comment by DonKoko** [comment]
@carlosvirreira can we consider this completed. We have the basic locations feature. If yes, lets close it.
