### ISSUE TITLE
[Feature request]: Auto log out user accounts after a period of inactivity

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1505]
### Is your feature request related to a problem? Please describe?

 - 

### Describe the solution you'd like

Three days would be good (as submitted in HECVAT)

**Comment by DonKoko** [comment]
Currently our sessions is 30 days which is very long.
@rockingrohit9639 can look into changing this? Should also find a good way to test it? Maybe set it to like 1 minute just to test if it expires correctly and if it works, just adjust the value to 3 days.
