### ISSUE TITLE
Feature request: quantity field

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#151]
Requested by a user. They want to have a field to track quantities of assets. 

We have to think good about that as in a way it conflicts with the tag concept as you have only 1 qr per asset.

**Comment by carlosvirreira** [comment]
I asked the requester for a bit extra context on this. Curious what she has to say.

**Comment by jurrejansen** [comment]
Closing, discussion continues in https://github.com/Shelf-nu/shelf.nu/issues/912
