### ISSUE TITLE
[Discussion]: Make editing faster

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#1524]
### Is your feature request related to a problem? Please describe?

I am migrating inventory for me to click actions then edit takes a lot of time. Any chance we can make this faster?

### Describe the solution you'd like

![Screenshot 2024-12-17 at 13 33 33](https://github.com/user-attachments/assets/6722fa90-f4cb-497f-968a-bba651a983cb)

**Comment by DonKoko** [comment]
Already covered by #1522
