### ISSUE TITLE
Feature request: Change the 'contact owner' message format

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#153]
User asks for adding an optional 'name' field besides email on the contact form. 

Perhaps we have to think of a configurable form? Or something that works with toggles?

Tried checking the format in which I receive mails and unfortunately after 15 mins of waiting, I have not received a message from shelf.

Something to look into @DonKoko

**Comment by DonKoko** [comment]
Yes, I can add it. Its a bit of work but no problem. I would be curious to anyways ask her why not just use the description field to add your name?

**Comment by carlosvirreira** [comment]
I guess it is more instructions to her users. I see your point. We can better ignore this request then.
