### ISSUE TITLE
Feature request: Code production / Orphan codes

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#155]
@DonKoko this is a reply to the options given to our user in terms of their asset tag production. I presented three options (print your own, print from zebra, print via us) here is the reply.

Hi, these options are all possible. We actually have our own thermal printer, but It's always a hassle to print the code exactly on the sticker template and so on. But we can work with that.

What I struggle with right now is the process of generating the QR codes, then printing and then sticking them on the actual items.  I would much rather prefer to pre-print some "blank" QR codes, attach them all to my items and then scan them to inventorize all items if you know what I mean.

Currently I would have to bring the QR printer with me all the time to inventorize the items. Hope you understand my feedback?

**Comment by jurrejansen** [comment]
being tracked i  https://github.com/Shelf-nu/shelf.nu/issues/240
