### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#160]
Tags functionality allows the user to better organize their assets.
<img width="406" alt="Screenshot 2023-06-13 at 14 28 42" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/06ec5815-4cea-4892-ab0b-fc87d432c836">

TODO: 
- [x] Model DB - https://www.prisma.io/docs/guides/other/troubleshooting-orm/help-articles/working-with-many-to-many-relations#explicit-relations
- [x] Tags index
- [x] Create/Delete
- [x] Assigning tags to assets
- [x] Filtering asset index by tags

**Comment by carlosvirreira** [comment]
This will bring so much value @DonKoko let's push it!

**Comment by DonKoko** [comment]
Those issues are fixed and deployed to live.
