### ISSUE TITLE
Let me copy the QR asset link for my asset

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#163]
I have NFC tags. I want to configure them to go to my asset page. 

Right now, unless I know the path I have no way to do this. I would like to have a place for me to copy the 'qr' asset link to my asset page.

**Comment by rockingrohit9639** [comment]
@carlosvirreira Can I work on this issue ?

**Comment by jurrejansen** [comment]
Logged in Tasks sheet
