### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by hunar1312** [Shelf-nu/shelf.nu#169]
As discussed in #150,

Need to build screens for Location Functionality as per the following designs : https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?type=design&node-id=6770-344179&t=XSpPlBakAW6rEp8y-0

**Comment by carlosvirreira** [comment]
Any time estimate for the completion of front end of this Hunar?

**Comment by DonKoko** [comment]
@carlosvirreira i renamed the issue to just locations as we are doing the backend & frontend simultaniously, working in sync with @hunar1312. Its planned to be finished this week including tests.

**Comment by DonKoko** [comment]
This is deployed in beta on the live app. Closing this issue for now.
