### ISSUE TITLE
Shelf is not asking to enable location after scanning QR

### ISSUE THREAD

**Issue by hunar1312** [Shelf-nu/shelf.nu#175]
Hi guys, I was using shelf today and the app didn't show me up the location permission popup after scanning the QR.
I thought could be an issue with the browser so I tried it with different browser and after some time with a different device but still it didn't ask for location permission but after retrying several times it showed up.

I think it should always ask for optional location permission after a user is redirected to shelf after scanning a QR.
We need to figure out a way that it always seek location permission from the user after a QR scan.

**Comment by DonKoko** [comment]
I have resolved this. #297
