### ISSUE TITLE
Backup / Export asset database

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#178]
I had a question about an inventory backup in case anything goes wrong. I remember you use to be able to export the assets in bulk as a file. Is there any way that we can do something similar as a way to save all our progress as we input our inventory into shelf? Thanks and all the best!

**Comment by DonKoko** [comment]
I would consider this in the same scope as the import feature. I would say we have to combine them in 1 issue.

**Comment by jurrejansen** [comment]
Closing this and using https://github.com/Shelf-nu/shelf.nu/issues/152 for further tracking
