### ISSUE TITLE
Improvement to table cells

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#182]
The mobile design of the table cell was not quite right because of the position of the 'Category' pill. This caused the height of the asset name + category pill to be larger than the thumbnail. Down below the changes i want to suggest. These are relevant for both desktop and mobile

- [x] Increase dimensions of thumbnail to 48x48

- [x] When asset name is too long and wraps to a new line, use the '...' to save responsiveness

```
/*Apply "..." after 3 lines of text */
.text-style-3lines {
    display: -webkit-box;
    overflow: hidden;
    -webkit-line-clamp: 3;
    -webkit-box-orient: vertical;
}
```

![Screenshot 2023-06-26 at 12 20 36](https://github.com/Shelf-nu/shelf.nu/assets/76112272/92036ebd-c65c-4b08-8c5b-e739c20822a9)

**Comment by hunar1312** [comment]
Thanks for noticing this @jurrejansen. I also faced this and thought to point it out.
Also, we will be needing a solution for this use case when product name and category name both are lengthy in mobile.
![image](https://github.com/Shelf-nu/shelf.nu/assets/129367263/57bbd9f9-9ea5-4f6c-bfdf-a59ddaefaf53)

**Comment by DonKoko** [comment]
Here is an update on how it should work, based on what we discussed with Jurre:

1. Put the tag below the name
2. Let the name break into multiple rows
3. Make the column to be max100% width
4. Clip it if its only 1 row

for the last point imagine a case when the asset name is: `Verylongassetnamewhichisoneword`, then you cannot break the row so in that case we need to clip
