### ISSUE TITLE
Feature: Paginate notes

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#189]
I think we have to add some pagination to the notes on an asset page, as we are loading them all right now. We can make it on scroll or with a load more button.

@jurrejansen could you make a quick and simple design for it please.

**Comment by jurrejansen** [comment]
@DonKoko we can use a simple 'Show more' button. I can imagine these entries are not that heavy to load in currently so I think we can load quite a few on initial load and only show the button after it exceeds that limit.

![Inspect _ Load more notes 1](https://github.com/Shelf-nu/shelf.nu/assets/76112272/abab54f1-f4cb-4a66-9fe5-505468944197)
![Inspect _ Load more notes 2](https://github.com/Shelf-nu/shelf.nu/assets/76112272/0d9a1645-2710-4669-8b41-31af5735e4a5)
![Inspect _ Load more notes 3](https://github.com/Shelf-nu/shelf.nu/assets/76112272/8f0ef08b-1d41-47b1-92ec-b07e1ea4d890)
![Inspect _ Load more notes 4](https://github.com/Shelf-nu/shelf.nu/assets/76112272/6a1e1e25-585a-4da4-8003-32b338766390)

**Comment by DonKoko** [comment]
Yeah I think thats good. How it worked in frontity which I thought was really nice is it auto loaded the first 2 pages on scroll and then the rest were with a button. That way it doesnt keep loading :)

**Comment by jurrejansen** [comment]
Made this part of a more recent issue: https://github.com/Shelf-nu/shelf.nu/issues/529
