### ISSUE TITLE
Locations

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#194]
- Location has no default empty image
- 
![Screenshot 2023-06-30 at 10 12 08](https://github.com/Shelf-nu/shelf.nu/assets/12449255/b364ef43-ce9d-4f11-bcee-d263f698d157)

**Comment by carlosvirreira** [comment]
@jurrejansen the design for locations has no empty state image for the location. This is not great. Please consider that for future production ready design deliveries. This is slowing us down.

**Comment by DonKoko** [comment]
This is fixed. Will be deployed to testapp a bit later
