### ISSUE TITLE
Introducing 'Asset Status' and the ability to give custody over an asset

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#218]
Because of features like 'Checkouts' that we want to add in future releases I would like start with introducing asset statuses. This will be the foundation of future features like 'Checkouts', 'Reservations' and simply giving a person custody (possession) over an asset.

DESIGNS

https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?type=design&node-id=7613-394771&mode=design

In this first release there will only be a 'Available' and 'In custody' status.

![Screenshot 2023-07-13 at 11 05 12](https://github.com/Shelf-nu/shelf.nu/assets/76112272/348f1c7d-6da0-4410-ba94-387c1c392624)

- [x] As an account owner I want to be able to see the status of an asset in the index
- [x] As an account owner I want to be able to see the status of an asset on the asset inspect page
- [x] As an account owner I want to be able to give a team member custody over an asset by using the 'Actions' dropdown
- [x] As an account owner I want to be able to release custody over an asset by using the 'Actions' dropdown
- [x] When releasing custody of an asset I want to be given the option to release it to a different location from that it was originally given
- [x] As an account owner, when a team member is given custody I want to see a notification of it in the Notes/ Comments thread on the asset page
- [x] - [ ] As an account owner, when a team member is released from custody I want to see a notification of it in the Notes/ Comments thread on the asset page

**Comment by DonKoko** [comment]
@hunar1312 there is something we are missing from the design:


![Image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/7f80adc3-decb-466c-89a8-4ad537182515)

**Comment by hunar1312** [comment]
Completed https://github.com/Shelf-nu/shelf.nu/commit/2bebfb520ec4dd4879e5c1ff1d16905beac5d845
