### ISSUE TITLE
Team member index

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#219]
Because we want to introduce the 'Available' and  'In custody' asset status we'll need an index of contacts to which the account owner can give custody. 

Because we want to start off simple, this index of team members will be account-less. But it would be good to keep in mind that at some point we'll introduce multiple users per environment. 

Team members can be managed under Settings > Workspaces. For now a team member will have these fields:

- Name
- Email

DESIGNS

https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?type=design&node-id=7613-422330&mode=design

- [x] As an admin user I want to be able to add team members
- [ ] ~As an admin I want to be able to edit a team member~
- [x] As an admin I want to be able to delete a team member

**Comment by DonKoko** [comment]
@jurrejansen this is already in progress, both front-end and backend. I personally have to say i think this view is confusing:


![Image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/501e6a2d-8c33-43e5-a100-60ce34e6f159)

I think it will give the impression to people they can manage it as a team. I think we need to put a way more clear notice, maybe even link to a blog post or a md file in the remo that explains:
1. This is what we have now
2. This is what is coming soon

**Comment by DonKoko** [comment]
## Dev Tasks


- [ ] When a user is created, create an organization
- [ ] Create a script that creates an organization for each existing user
- [ ] Maybe when we need to give a direct relationship between assets and organizations, so it doesn't work via the user as that will be hard to manage. Considering there will always be an `Organization` which is default with the type `PERSONAL` we could link assets to the organization and consider the user to be the "creator". That way we can know to which organization the asset belongs and which user created it.

**Comment by jurrejansen** [comment]
BUGS

- [ ] When deleting a team member that has custody over 1 or more items i am not getting the correct modal informing me the team member has custody and when clicking through an error appears

https://github.com/Shelf-nu/shelf.nu/assets/76112272/1c13d7be-d17e-40e7-b5e3-1ba8da91c946

IMPROVEMENTS

- [ ] On the Asset Inspect view it is displayed which team member has custody over the Asset. We don't have an option to give team members an avatar yet but it would be good to add a placeholder avatar regardless. It makes it more clear.

**Comment by DonKoko** [comment]
@jurrejansen this is done and now being deployed to testapp. (https://github.com/Shelf-nu/shelf.nu/actions/runs/5646192633). Once its deployed let me know if everything is okey now. Thanks
