### ISSUE TITLE
[Feature request]: Orphaned codes which are not linked to an asset or user (Internal tooling)

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#240]
### Contact Details

jurre@whale-agency.com

### Is your feature request related to a problem? Please describe?

More or less, because orphaned codes currently have to be linked to an existing user, we are unable to send sheets with orphaned codes to potential clients for marketing purposes. It would be a good way to introduce people to Shelf.

### Describe the solution you'd like

A way to generate fully orphaned codes in the Super Admin area. These codes, when scanned, should prompt a login view when not logged in, and after logging in, a view in which the user will be able to create an asset that will be linked to orphaned code that was scanned.

Maybe we can start off with discussing any technical obstacles that need to be overcome?

**Comment by DonKoko** [comment]
> Maybe we can start off with discussing any technical obstacles that need to be overcome?

We can definitely build this. It will require some changes in the DB that I am not excited about, however I have already thought of it and we can make a plan. Nothing you should worry about, I will take care of that part.

So can you please prepare designs for the user process of claiming the codes and so on? We don't need design for the admin area.

**Comment by carlosvirreira** [comment]
just want to drop a comment and say that this is handy for instance if we sell shelf branded or white labels asset stickers/labels that work with our app.

**Comment by jurrejansen** [comment]
Hi @DonKoko I've reviewed the flow diagram for scanning a QR but I don't think we need additional designs. With the notion that we're sticking to let users only create new assets and to link to existing assets. We've changed the order of the flow a little bit with the current implementation I noticed. We are first checking if the code is linked to any user instead of "is it linked to an any asset?". This is indeed better I think. 

I made a new diagram

https://www.figma.com/file/oBSRWYlWtjlLwu39LtpMHS/Shelf-%7C-FigJam?type=whiteboard&node-id=0%3A1&t=Zdmg0JDC4ocFHArE-1

Changed the designs a bit (Scanning WIP)

![Screenshot 2023-07-28 at 14 34 54](https://github.com/Shelf-nu/shelf.nu/assets/76112272/90bee353-f72e-44bc-bb1a-0679e9970501)

**Comment by carlosvirreira** [comment]
<img width="423" alt="Screenshot 2023-08-07 at 11 48 13" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/b8972b13-ebe4-4d92-829f-45f6108fa8ee">

These are the colour coded stickers we would like to produce to distribute on marketplaces @DonKoko 

Will be printed at DWD.
<img width="662" alt="Screenshot 2023-08-07 at 11 50 07" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/6e2e9d5c-0cae-4fb4-896e-eaba922034ef">

**Comment by timvdalen** [comment]
Definitely useful for printing up a big batch of as-yet unclaimed QR codes without having to re-order in quantities of 1 every time you add a new asset.

**Comment by carlosvirreira** [comment]
> Definitely useful for printing up a big batch of as-yet unclaimed QR codes without having to re-order in quantities of 1 every time you add a new asset.

You totally get it Tim!

**Comment by DonKoko** [comment]
This has been completed and released.
