### ISSUE TITLE
[Feature request]: Scheduling

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#242]
### Contact Details

carlos@shelf.nu

### Is your feature request related to a problem? Please describe?

Double booking gear

### Describe the solution you'd like

Hello team. love the product but a killer feature i'd love to see is scheduling. We are a high school tv program and we want to track our equipment so it doesn't get lost or damaged, but we love the ability to schedule events so we can avoid conflicting equipment usage. that's the only thing stopping me from switching over from **---Redacted---**, so hopefully i can follow along the dev. journey and see this product grow. excellent work thus far, it looks great and responsive and i think it will be successful.

**Comment by evonloch** [comment]
Hey! Want to work on this feature. Will it be possible?
