### ISSUE TITLE
[Bug]: On asset index, when an asset is assigned to a non-account-having team member, the name does not show on index

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#246]
### Contact Details

carlos@shelf.nu

### What happened?

Steps to reproduce:

1. Go to 'testapp'
2. Click on 'assign custodian'
3. Scroll down to 'asset index'
4. See error (shows, 'some user' instead of 'team_member_name'

### What is the expected behaviour?

I expect to see the name of the custodian on the asset table

<img width="190" alt="Screenshot 2023-07-21 at 16 33 08" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/a17a78a9-8d11-42a9-a9ac-a9672e7a9ec7">

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by DonKoko** [comment]
Solved.
