### ISSUE TITLE
[Feature request]: Super Admin - Batch export QR codes from a user

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#252]
### Is your feature request related to a problem? Please describe?

Trying to help create a backup - this is very hard to achieve

### Describe the solution you'd like

Ideally on super admin area next to each code I select I can batch export the codes

### Describe alternatives you've considered

Getting user access and exporting via each asset page 1 by 1

**Comment by carlosvirreira** [comment]
If possible also next to the QR code ID add a column Asset name / next to the ID

**Comment by DonKoko** [comment]
@carlosvirreira do you think the exports we have now are covering it? Like it's a backup of the QR images themselves. Also when we release the import/export its basically going to kinda cover this.
