### ISSUE TITLE
[Feature request]: Add logo to my QR codes

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#263]
### Is your feature request related to a problem? Please describe?

Must manually download QRs and slap my logo on top of it

### Describe the solution you'd like

I can add a SVG logo file and it gets placed right in the centre of my code.

**Comment by carlosvirreira** [comment]
@jurrejansen can you make a flow/design proposal for this?

**Comment by carlosvirreira** [comment]
Some UI that was shared with a prospect:
<img width="547" alt="Screenshot 2023-08-09 at 12 02 11" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/a2a9f5b0-c1e3-4ae0-9712-b1b02847df66">

**Comment by DonKoko** [comment]
hey @tobihans . I can see you have picked this up. I am curious what your ideas are to approach this? We need to consider a few things:

1. Currently the QR is generated on the server. Can we also add the logo on the server? That would be better in my opinion
2. Or maybe we do it on the client using html canvas?

**Comment by tobihans** [comment]
@DonKoko thanks for the head up.

I believe it's better done on the client side according to the UI shared above.
Each trial the user will be making to get his **perfect** QR Code will be hitting the server. 

So maybe we can just avoid that by doing it client side.

But then, I'm open to follow you suggestions. Thanks

**Comment by carlosvirreira** [comment]
@jurrejansen very nice elegant solution. I thank you for thinking deeply about this. I see no loose ends with your proposal. I'd proceed with it. It is the start of 'owning' the style of codes for our users.

**Comment by carlosvirreira** [comment]
@tobihans 👀

**Comment by tobihans** [comment]
@carlosvirreira that's noted. Now, that means I'll add an input for the customer to supply his logo, then generate the code right?

**Comment by carlosvirreira** [comment]
yes, do you have discord, can you add me? > carlosvd

**Comment by timvdalen** [comment]
To give some (unsolicited) user feedback: Initially I thought that the design above would be quicker but inferior to the "full solution" of adding a logo in the middle of a more-redundant QR code, but the more I think about it, the more I prefer it.

The mockups for stickers for well-known brands (I forget where they popped up, I think in-app at first launch?) are very pretty, but might be a little too much for daily use.
The more spartan version probably makes more sense for items that are actually in use.

**Comment by DonKoko** [comment]
hey @timvdalen. Thats why we did it like this. We really focused on functionality rather than aesthetics when designing the QR codes. Of course we have big plans to make you even design your own labels and so on but for the basics, we wanted to keep it simple.

**Comment by timvdalen** [comment]
Preview in the wild: 
![PXL_20230815_123549777](https://github.com/Shelf-nu/shelf.nu/assets/1038428/f45be787-4423-44bc-b806-ff4023aecf10)
