### ISSUE TITLE
[Feature request]: Improvements to Pagination

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#264]
### Is your feature request related to a problem? Please describe?

Pagination controls frontend breaks when having a lot of assets. Especially on mobile.

### Describe the solution you'd like

The designs should explain themselves hopefully. We can discuss if needed.

https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?type=design&node-id=8081-183234&mode=design

**Comment by DonKoko** [comment]
@jurrejansen so I looked at this and i thought its too complex to implement pagination like this. We also discussed it with Carlos and we couldn't find a real reason why a user would navigate to any specific page, unless its prev/next.

So we want to greatly simplify it. 


![Image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/b6c39939-2998-429a-afbe-a7d894e07a0b)




For now I just made this, very simple. You can see it on dev, however I want to give it a bit more functionality. Look at this example:

![Image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/1f6f7e7e-92b6-4d41-abbe-db38d137e6f3)

Can you help me with the input design. I tried to make it but its not so easy directly styling it in the code.

**Comment by DonKoko** [comment]
I have an update. I found a package we could do this with (react-paginate) but its still quite complex as we need to do a lot of custom stuff to make it work with the async fetching on the server and work also client side. It will take some time so I would rather prioritize other tasks. and stick to the simple approach i shared above.

**Comment by jurrejansen** [comment]
Hi @DonKoko sure, let's keep it simple then. Not sure if I like the input approach that much. 

![Screenshot 2023-08-03 at 10 28 14](https://github.com/Shelf-nu/shelf.nu/assets/76112272/2801e5b0-bdad-42be-bb7f-b2dd03e20c6a)

![Screenshot 2023-08-03 at 10 40 26](https://github.com/Shelf-nu/shelf.nu/assets/76112272/d8e9ce5e-b2e5-4dcc-9dd1-7c9e77661da8)

**Comment by jurrejansen** [comment]
Hi @hunar1312 we decided to do some changes to pagination, you can find the designs here:

https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?type=design&node-id=8513-127506&mode=design

Adding a screen recording from Clockify to show off behaviour. Let me know if something is not clear.

Uploading Screen Recording 2023-08-04 at 17.31.34.mov…

**Comment by DonKoko** [comment]
@jurrejansen this is deployed to test, can you please test it and let me know if you find something. I will send you my account on discord as I have hundreds of assets so its easier to test.

**Comment by DonKoko** [comment]
Hey @jurrejansen. I implemented a proper fix for this. We already have the functionality for singular vs plural with the model name so it was just a few mins to enable it there. I am going to merge and deploy this to live now.
