### ISSUE TITLE
[Feature request]: Re-introducing minimizing of sidebar + other frontend improvements

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#265]
### Contact Details

jurre@whale-agency.com

### Is your feature request related to a problem? Please describe?

Removal of minimizing sidebar due to bad UX

### Describe the solution you'd like

- [x] The addition of a button in the sidebar for maximizing / minimizing the sidebar.

![Screenshot 2023-07-31 at 09 58 34](https://github.com/Shelf-nu/shelf.nu/assets/76112272/8769e5bd-57ea-4331-a81b-930c98ec57d4)

- [x] Add proper spacing between bottom nav items and the user details

- [ ] Give user details the proper width, 240px in design

![Screenshot 2023-07-31 at 10 02 43](https://github.com/Shelf-nu/shelf.nu/assets/76112272/6b2568fe-3620-4776-8577-04ce2bc6269d)
![Screenshot 2023-07-31 at 10 02 27](https://github.com/Shelf-nu/shelf.nu/assets/76112272/d5b412f7-9fc6-47df-809d-119d5d6eb400)

**Comment by DonKoko** [comment]
This is done and deployed to live. @carlosvirreira @jurrejansen . Please let us know if there is any feedback.

**Comment by carlosvirreira** [comment]
looks good to me @jurrejansen lets pls focus on UX/UI for other features or areas of the site instead of overpolish

**Comment by hunar1312** [comment]
Hey @jurrejansen, 
With reference to your point `the spacing between the bottom nav links and the announcement modal (when active) is still a bit off` 
The spacing in the sidebar is as per the design for the screen height used in the design.
It may seems to you the spacing being bit larger than actual as you're using a display with good height and for the displays with larger viewport height we are distributing the white space equally between the three divisions of side bar, a reference video for explaination: 

https://github.com/Shelf-nu/shelf.nu/assets/129367263/e0adb015-b0fb-43d8-ae18-6418ec1d7dab
