### ISSUE TITLE
[Bugs/Improvements]: Frontend improvements

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#289]
### Contact Details

jurre@whale-agency.com

### What happened?

Just documenting here, I'll assign at a later point

### Mobile

- [x] height of category / tag badges should be 22px according to design. Currently it's 24px that makes the total height of the title and badge to almost exceed the height of the thumbnail

![Screenshot 2023-08-08 at 10 43 29](https://github.com/Shelf-nu/shelf.nu/assets/76112272/5e0db3a7-d03f-4e9d-9224-e939a032cd9f)
![Screenshot 2023-08-08 at 10 42 14](https://github.com/Shelf-nu/shelf.nu/assets/76112272/26d3c9c6-3409-4c80-bc31-9ccfb66d9e0b)

- [x] field labels are showing, this breaks the design at multiple places

![Screenshot 2023-08-08 at 10 39 02](https://github.com/Shelf-nu/shelf.nu/assets/76112272/cb6ffad8-2fef-4c4f-bc95-2666a335640e)
![Screenshot 2023-08-08 at 10 38 59](https://github.com/Shelf-nu/shelf.nu/assets/76112272/1bc0c19f-9a93-4c52-a21d-a70b545717c1)
![Screenshot 2023-08-08 at 10 34 25](https://github.com/Shelf-nu/shelf.nu/assets/76112272/5fe0dcbf-3c54-4ad4-bb7f-4f15f8f1a47e)

- [x] activation of keyboard is currently affecting the position of the filter modal. This causes the modal to be pushed out of the screen and the modal moving position. I would prefer to not have the modal be affected + the ability to scroll when modal / keyboard is active. I would like to present using Clockify on mobile as a good example.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/c11f8b2f-9921-43f1-8e72-f263f5a7b708

https://github.com/Shelf-nu/shelf.nu/assets/76112272/e68b9331-6623-4e32-9702-df3f660b5856

### What is the expected behaviour?

n.v.t.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by DonKoko** [comment]
Thanks @jurrejansen for reporting those issues. Its front-end mostly so please assign to @hunar1312 when you see fit. Thanks

**Comment by hunar1312** [comment]
@DonKoko The major thing that bothered in modal positioning in mobile was due to the long height of it as there were some by default categories and then other manually created categories which made the modal too long. So, the positioning of it was going out of the user view which is now fixed by having a certain max-height after that max-height user can scroll in modal.
