### ISSUE TITLE
[Feature request]: Change name and description of a category

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#292]
### Is your feature request related to a problem? Please describe?

I own asset tags (50) I am starting to make an inventory of my assets. I want to be able to change the category name and descriptions of the pre-created categories of shelf.

### Describe the solution you'd like

Let me change the name and description / color for the categories.

---- 

> categories are written in json format
> /app/modules/user/service.server.ts this is the file path
> https://github.com/Shelf-nu/shelf.nu/blob/d905fb9e6585b80280dda326a3f6faa7819efccf/app/modules/user/service.server.ts#L29

**Comment by MAYANK-TRIPATH** [comment]
@carlosvirreira  Could you please provide more details about the specific issue you're encountering?

**Comment by carlosvirreira** [comment]
> @carlosvirreira Could you please provide more details about the specific issue you're encountering?

https://discord.gg/FKeAUMVp

**Comment by kanavmittal** [comment]
@carlosvirreira I have gone through Discord to understand the feature.

Thoughts

- Incorporating an edit button adjacent to the delete button.
- A similar UI can open upon clicking, resembling the category addition interface. However, the distinction lies in the pre-existing information of name and desc.
- Replacing the 'Create' button, an 'Update' button will be responsible for modifying the category with the updated information.

**Comment by DonKoko** [comment]
I will give some more context for this issue from a technical perspective and how to do it. So currently we just have create and delete for categories. We also need to implement an edit. 
I would recommend the following approach:

- Add an edit button next to the delete button of the category
- Move the form from `categories.new` into its own component that can be used both for `new` and `edit`. You can check `components/assets/form.tsx` as an example of how its used in both `new` and `edit`
- Create the edit route(see assets for example on how to do it).
- Create `loader` and `action` in the edit route to manage GET and POST requests to the route
- Once a category is edited, redirect `/categories`

I think this should be enough. @kanavmittal do you still want to attempt this? We also have some other people interested but I wanted to check with you first.
