### ISSUE TITLE
[Feature request]: Show asset location history

### ISSUE THREAD

**Issue by timvdalen** [Shelf-nu/shelf.nu#293]
### Contact Details

tim@code-orange.nl

### Is your feature request related to a problem? Please describe?

If a user scans a QR code without logging in, it will log a last scan, but without location data.
This obscures the last _actual_ known location.

### Describe the solution you'd like

Either allow admins to see location history, or show the last known location.

**Comment by carlosvirreira** [comment]
@jurrejansen can you come up with a design proposal for this

**Comment by DonKoko** [comment]
hey @timvdalen . Thanks for opening an issue and reporting this.

So I see 2 points to this:

1. Bug - The location of the last scan should be recorded even if you are not the owner of the asset. We have a hook called `usePosition` that takes care of asking the user to give location permissions and hitting the endpoint that updates the DB. This hook was only called on the asset page, so it would record the location only if you are the owner and logged in. I have solved this (#297) and its being merged and pushed to live.
2. Feature request - scans history. This is the second part. Its a feature we have planned and discussed internally but we didn't get to it yet. Our colleague @jurrejansen will make a design. We will share it here and would love to hear your opinion @timvdalen on it.

Let me know if there is something else.

**Comment by timvdalen** [comment]
@DonKoko ah, clear!

1 is my biggest issue here (related to https://github.com/orgs/Shelf-nu/discussions/294 as well).
Looking at that PR, I'd suggest adding something to the public-facing asset screen that communicates that the location has been logged.
I think my expectation around it not being logged is as much in the UX as in the actual implementation.

At that point, 2 is much lower priority for me personally, since I mainly suggested it as a workaround to 1 (though I agree it should be in the product eventually)

**Comment by DonKoko** [comment]
Thanks for clarifying. I answered in the discussion with a bit more details about how things work. Lets leave this issue open so we can track the second point here.

**Comment by jurrejansen** [comment]
Closing this one. Logged in Tasks sheet.
