### ISSUE TITLE
[Bug]: Items bucket in readme should be `assets`

### ISSUE THREAD

**Issue by timvdalen** [Shelf-nu/shelf.nu#295]
### Contact Details

tim@code-orange.nl

### What happened?

Steps to reproduce:

1. Follow the readme
2. Create buckets https://github.com/Shelf-nu/shelf.nu#items
3. Try to upload asset image
4. Asset image is not uploaded

### What is the expected behaviour?

The correct bucket name seems to be `assets` (https://github.com/Shelf-nu/shelf.nu/blob/a96f21c/app/modules/asset/service.server.ts#L367), so the readme should be updated to reflect that.

Additionally, I would expect to see an error logged somewhere, rather than having this fail silently.

### Version

Self-hosted

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output

```shell
POST /assets/cll552d4g0002v7bcs57js8q1/edit?_data=routes%2F_layout%2B%2Fassets.%24assetId_.edit 200 - - 974.407 ms
```

**Comment by DonKoko** [comment]
Thanks @timvdalen . It used to be named `items` so I think I forgot to rename it when we renamed the model. Thanks for reporting. Its fixed here: https://github.com/Shelf-nu/shelf.nu/pull/298
