### ISSUE TITLE
[Feature request]: Updated appearance 'Actions' dropdown on mobile + Activate after scan

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#296]
### Contact Details

jurre@whale-agency.com

### Is your feature request related to a problem? Please describe?

In most cases users want to perform an action after scanning a code. This will be one less action to perform an action.

### Describe the solution you'd like

After scanning a QR code a user will land on the asset page. In most cases they scan the code to perform an action. For that reason it would be good to already have the 'Actions' menu activated after they scan.

Currently the 'Actions' dropdown on mobile is styled like this:

https://github.com/Shelf-nu/shelf.nu/assets/76112272/164999b5-3de5-457f-8b20-f048501140d3

A more mobile friendly appearance would be:

![actions-dropdown-mobile](https://github.com/Shelf-nu/shelf.nu/assets/76112272/d837f0b1-59f3-494e-8c73-658e9a3f2f71)

**Comment by rishi-raj-jain** [comment]
I'm passing on this one.

Reason: Too much to do to even setup.
