### ISSUE TITLE
[Feature request]: Improvement of setup docs or frequently asked question while setup 

### ISSUE THREAD

**Issue by hrutik7** [Shelf-nu/shelf.nu#311]
### Contact Details

hritikkumthekar7@gmail.com

### Is your feature request related to a problem? Please describe?

While I was doing setup of shelf.nu repo on my local system I face error below 
![image](https://github.com/Shelf-nu/shelf.nu/assets/62372737/2dd39f78-0cd3-4362-933f-493cad03bd91)

### Describe the solution you'd like

For resolving this issue user need to run this command 
`npm install --save-dev npm-run-all`
My point is that many other enthusiasts may have faced this problem. So, would it be a good idea to document it?

**Comment by hrutik7** [comment]
I would be more than happy to contribute to the documentation of shelf.nu.

**Comment by carlosvirreira** [comment]
@hrutik7 consider joining us here! https://discord.gg/nJYKvpcf

**Comment by hrutik7** [comment]
@carlosvirreira sure !

**Comment by DonKoko** [comment]
From discord:

> 
> okey so I am gonna chip in here
> I just saw the issue you made, its a very valid issue, so here is what I have thought about this before, just never got to implementing it. Now that you have made the issue if you are open to contribute I would suggest the following:
> 
> 1. Keep the readme in the root folder as a general readme: Explains what shelf is, has links to more relevant docs, our blog knowledgebase and so on. I @Carlos-san can give you some usefull links to add there and we can of course adjust it.
> 
> 2. Create a folder docs in the root of the project where we simply use MD to create our docs. For now we can have a get-started.md where we can place all the content from the current readme which explains how to setup the app locally + any suggestions you have based on the issue you created. Our app can be a bit tricky to setup at first so I want to make it as easy as possible for all our contributors and users.
> 
> 3. In the same docs folder we have to add a standard file with how to contribute, as we dont have it not and I think its important to write down some rules.
> 
> This is my general idea. Let me know if you are interested in helping with this @hrutik_k
> If you are, please fork the repo, make some changes and make a PR

**Comment by hrutik7** [comment]
hey @carlosvirreira  @carlosvirreira 
you can check this out 
https://jam.dev/c/8d40e390-db98-4e48-825c-cfee2f51848b

**Comment by hrutik7** [comment]
I'll raise the PR if there are any suggestions on this please let me know on PR

**Comment by hrutik7** [comment]
PR merged
