### ISSUE TITLE
More Powerful Search (Plan of approach Bounty) 💎

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#314]
### Is your feature request related to a problem? Please describe?

I have added information of my assets on my description, sometimes on a custom field, sometime on a note. I want to be able to have a powerful search that I can type a word or phrase and returns a link to the right area of the application.

### Describe the solution you'd like

This bounty is to create a comprehensive plan of approach on how to do this within our application, considering our infrastructure. Ideally using open source libraries or vendors.

With a not too crazy complexity to implement. 

The best plan of approach gets the bounty and gets invited to submit a build bid if needed.

Our requirement is that this is described as much as possible as a feature proposal and if you can add some graph or diagram it would be great. 

### Describe alternatives you've considered

This request comes from a comment we received.

"Also I'm missing some basics (at least for me) like adding a serial number and being able to search for it (for now I added it to the description field, which doesn't appear to get used for searching). I somehow need to have this working with our existing systems, so having a searchable device serial number or internal inventory ID is pretty much a must have."

### Additional context

Join us on Discord to discuss this in detail: 

https://discord.gg/nJYKvpcf

**Comment by SuperSchek** [comment]
Some options I've used or heard about:

[Elastic](https://www.elastic.co/about/free-and-open) is free and open and extremely powerful. Used it many times and it's amazing. Docs leave something to be desired though. Also, if you want to use the 'open and free' version, you obviously need to provide your own infra. And Elastic needs you to provision some pretty beefy resources, so it might not be exactly what you are looking for.

[Zincsearch](https://github.com/zincsearch/zincsearch) is an open-source solution which is supposed to be a lightweight alternative to Elastic. No experience with it, but might be worth looking into.

[OpenSearch](https://opensearch.org) is also a big name in this area. It's similar to Elastic. From what I can tell in the docs it also needs a beefy machine with plenty of memory. At least 4GB of memory for the Docker container. I haven't used it, but it should offer results similar to Elastic.

A benefit of OpenSearch is that [AWS offers it natively as a service](https://aws.amazon.com/opensearch-service/) (apparently they even have a [serverless offering](https://aws.amazon.com/opensearch-service/features/serverless/), which is kinda sick). So people looking to run Shelf in the cloud can easily provision their own instance of OpenSearch on AWS to use in conjunction with the web app. You could even offer a CloudFormation contruct to make it more or less plug and play.

**Comment by DonKoko** [comment]
hey @SuperSchek . Great suggestions. We already looked at Elastic as well as Algolia. We have done a few sites using algolia so we have experience with it, however its paid so its not the best option here.

I see this challenge can be broken down in 2 parts:
 - UI - what do we use for the UI to have such a search
 - Data - how do we handle the data and i think this is where something like elastic comes in however there are some complexities that will make this quite a chunky scope so we are looking for a way to maybe implement it using our own api's as a start.

**Comment by SuperSchek** [comment]
Hmm, if you want to keep things simple you might want to look into [full text search](https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search) offered by Prisma (currently in preview). This will require you to do some parsing of the user input to make it usable for a prisma query though.

One thing to note is that you will want to avoiding polluting the search results with assets owned by other users. You probably want to determine for which user you're querying entirely server side (based on JWT or whatever type of auth you're using) so people can't just change the userId in their network tab and see assets that don't belong to them.

**Comment by DonKoko** [comment]
Thanks @SuperSchek . I will check it. We already use Prisma so that's a good match.

**Comment by DonKoko** [comment]
Thanks @SuperSchek . I will check it. We already use Prisma so that's a good match.

**Comment by mahendraHegde** [comment]
/attempt #314
 
Hello @carlosvirreira @DonKoko  
Since this is asset management and usually a tenant wont have millions of assets, may be you can consider [Orama search](https://github.com/oramasearch/orama), its super easy to implement, but it stores the data in memory hence its super fast also, you can even deploy it to edge(cloudflare etc).

**Comment by DonKoko** [comment]
hey @hunar1312. This is mostly done, we just need to implement the tooltip from the designs. I have already made the backend work and made the component (`search-field-tooltip.tsx`). 
What still needs to be done:
- Icon
- tooltip component - it exists in shadcn: https://ui.shadcn.com/docs/components/tooltip

Could you please implement those things tomorrow morning? then we can ship this. Branch to work on is: `mahendraHegde/vectorized-search-using-view-for-assets`. Please create your own copy of it and then make your PR to it.

**Comment by hunar1312** [comment]
The ui updates in search bar are completed @DonKoko, Here's the PR: https://github.com/Shelf-nu/shelf.nu/pull/348

**Comment by jurrejansen** [comment]
- [ ] Would be nice if we can keep the 'X' to clear the search query after one has been submitted. It should replace the question mark when a query has been submitted.

PLACEHOLDER
![Screenshot 2023-09-12 at 13 47 21](https://github.com/Shelf-nu/shelf.nu/assets/76112272/c3dcc6a9-9efc-4c6e-ae75-9c1044fabf68)

TYPING
![Screenshot 2023-09-12 at 13 47 13](https://github.com/Shelf-nu/shelf.nu/assets/76112272/24218e3a-3e96-462a-8817-7b83f7370ef7)

SUBMITTED
![Screenshot 2023-09-12 at 13 47 33](https://github.com/Shelf-nu/shelf.nu/assets/76112272/de602896-efb1-4580-a62b-4a62992b8974)

**Comment by DonKoko** [comment]
@jurrejansen its already being fixed together with #356

**Comment by DonKoko** [comment]
@jurrejansen this is fixed and deployed.
