### ISSUE TITLE
[Bug]: Cannot delete assets

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#322]
### What happened?

Tested on Safari on a Mac
As well as on the (on development) Mac desktop app

### What is the expected behaviour?

Delete the asset

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by carlosvirreira** [comment]
From Crisp:

When I delete an asset now, the interface becomes unresponsive. The browser

isn't frozen, but none of the links on the page will work. Refreshing the

page seems to resolve the issue, but I can't imagine this is intended

behavior.

**Comment by DonKoko** [comment]
On it.
