### ISSUE TITLE
[Feature request]: Bookings: reserve assets for a certain time period and track when they're due back

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#326]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

In order to assign custody over multiple assets at once, maintaining and tracking custody on a project basis we would like to introduce Bookings. When an asset is part of a Booking, it means that it has been borrowed or rented by someone and is currently being used outside or inside the organization by a registered user / custodian (currently we don't have multiple users per workspace but this will be a thing so good to keep in mind) or team member. Bookings allow the equipment manager to lend out assets and to keep track of when certain assets are not available to avoid double bookings.

### Describe the solution you'd like

A user creates a Booking and specifies the following information:

- Name (of Booking)
- Booking period
- Custodian (user who is assigned custody / responsibility over the assets)
- Included assets (a Booking is a collection of individual assets that will be in custody of the custodian over the specified period of time)

Designs - I've added annotations under certain designs to hopefully give more clarity about the different states of a Booking.

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=14-50738&mode=design

**Comment by carlosvirreira** [comment]
Hi @jurrejansen 

A few questions: 

- I like the layout, one thing I really worry about is date/time. Could we not MVP this into a date only support?
- The Figma is so large is easy to be lost. I would think it can greatly increase the productivity if you attach a recording of the to be created UX so our contributors/members can better help.
- I see that the flow starts with a new checkout - do we not have a checkouts index available? I'm not sure if it was left our purposely. I think it makes some sense to have it. Curious of your POV.

**Comment by carlosvirreira** [comment]
Left Comments on Figma.

@DonKoko can you comment thoughts?

**Comment by jurrejansen** [comment]
@carlosvirreira 

- Yeah we could do that but for development would be good to keep in mind that this eventually is intended to be included when laying the foundations. As for timezones I'm not sure how to tackle this. @DonKoko can this be based on date / time settings of operating system? Date / time formatting needs to be added to settings for sure.
- Made a video, included in original post
- Added checkout index

**Comment by carlosvirreira** [comment]
Thank you @jurrejansen 

Timezones are horrible to deal with so id like to simplify this.

**Comment by carlosvirreira** [comment]
hi @jurrejansen we want to start building this. Can you confirm that your designs are final and also mobile ready / with explanations, etc? We want to make a bounty for this.

**Comment by jurrejansen** [comment]
@carlosvirreira yes, should be clear enough

**Comment by carlosvirreira** [comment]
Extra context of the original request: 

```Hello team. love the product but a killer feature i'd love to see is scheduling. We are a high school tv program and we want to track our equipment so it doesn't get lost or damaged, but we love the ability to schedule events so we can avoid conflicting equipment usage. that's the only thing stopping me from switching over from ---Redacted---, so hopefully i can follow along the dev. journey and see this product grow. excellent work thus far, it looks great and responsive and i think it will be successful.```

**Comment by carlosvirreira** [comment]
hi @jurrejansen 

Please confirm that the Figma, description, etc is all up-to-date and ready to be assigned. 

Want to avoid having conflicting contents or designs here.

**Comment by jurrejansen** [comment]
@carlosvirreira @mahendraHegde I've edited the original comment with up-to-date information and a link to the final designs

**Comment by rockingrohit9639** [comment]
@jurrejansen @carlosvirreira I want to work on this issue.
