### ISSUE TITLE
Improvements to asset index + status and category labels

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#330]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

@carlosvirreira @DonKoko 

Currently users are unable to see the status of an asset in the asset index. For future releases this becomes more important when we'll introduce more asset statuses with Checkouts and archiving assets and making assets unavailable for e.g. Checkouts.

![Screenshot 2023-08-31 at 13 04 09](https://github.com/Shelf-nu/shelf.nu/assets/76112272/bc2c2a59-a0db-4a85-a464-a243eaff6e46)
![Screenshot 2023-08-31 at 13 05 23](https://github.com/Shelf-nu/shelf.nu/assets/76112272/563c872e-52a0-4ac9-b1fd-6e5161b7e424)

Also, with the introduction of more statutes we'll need a good way to filter the index. A dedicated filter to filter statutes. With filtering on 'Archived' only showing Archived assets. Archived assets will not show when filter is set on 'All'

![Screenshot 2023-08-31 at 14 14 30](https://github.com/Shelf-nu/shelf.nu/assets/76112272/e44bbb22-e87a-4f1d-a3e4-32bc856873fb)
![Screenshot 2023-08-31 at 14 13 09](https://github.com/Shelf-nu/shelf.nu/assets/76112272/d61765fe-68ce-4976-b3dc-f3c4302187dc)
![Screenshot 2023-08-31 at 14 13 25](https://github.com/Shelf-nu/shelf.nu/assets/76112272/4f4f1bca-9c26-4f62-88f0-951c04759634)

For category badges I would like to remove the 'dot' and reserve the 'dot' exclusively for status badges instead. I'm still doubting on how to style the status badges in the index. 

![Screenshot 2023-08-31 at 14 17 43](https://github.com/Shelf-nu/shelf.nu/assets/76112272/63d09671-f0fe-473e-be29-ef10e82b3dc4)
![Screenshot 2023-08-31 at 14 17 34](https://github.com/Shelf-nu/shelf.nu/assets/76112272/50f7d2a9-a33e-4d3b-be85-408fcd4089b6)

I do want to style the badge like this on the Inspect asset view, and also on the Checkout page so I think we'll just have to keep it consistent and style it like this in the index too.

![Screenshot 2023-08-31 at 14 18 40](https://github.com/Shelf-nu/shelf.nu/assets/76112272/8b3f39f8-b4d5-4c1e-8b47-b202dc9fd4ae)

On mobile we're currently prioritizing the category badge. I think we should change this and prioritize the status badge instead.  I was dabbling with the idea to keep the category badge and indicate the status with the 'dot' on the avatar. But I would opt not to do this.

Can we also make sure all the badges have the proper padding, for example padding on tag badges is not correct.

![image](https://github.com/Shelf-nu/shelf.nu/assets/76112272/37c7e352-56d6-416a-b290-0cde64374ccc)
![Screenshot 2023-08-31 at 15 39 15](https://github.com/Shelf-nu/shelf.nu/assets/76112272/b934faad-2fc0-4e92-af6c-4a816f92d024)
![Screenshot 2023-08-31 at 15 39 31](https://github.com/Shelf-nu/shelf.nu/assets/76112272/525d1a10-10de-442c-bdd3-46b7f6660374)
![Screenshot 2023-08-31 at 15 39 42](https://github.com/Shelf-nu/shelf.nu/assets/76112272/0a6dcaae-5ec1-44f9-b659-f6f5942005eb)

Opened this issue to propose these changes. Let me know your thoughts and perhaps other ideas that may arise after reading. Thanks.

### Describe the solution you'd like

Implement these changes after discussion.

**Comment by carlosvirreira** [comment]
I agree about the tag/badge consistency. 

Would be much more confusing if, based on the view I am in, that this completely changes.

**Comment by DonKoko** [comment]
@hunar1312 @jurrejansen this is solved right? Can you please close the issue if it is. Thanks

**Comment by jurrejansen** [comment]
@DonKoko part of this issue is also the improvements to filtering the index but I'll create another issue for this when the time comes
