### ISSUE TITLE
[Improvement request]: Changes to 'Category' badge + show 'Status' badge in Asset index + other improvements

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#339]
### Contact Details

jurre@whale-agency.com

### Is your feature request related to a problem? Please describe?

I would like to have a clearer visual difference between 'Status' and 'Category' badges.

### Describe the solution you'd like

- [x] For category badges I would like to remove the 'dot' and reserve the 'dot' exclusively for status badges instead.

![Screenshot 2023-09-08 at 12 22 52](https://github.com/Shelf-nu/shelf.nu/assets/76112272/b480bd3c-9b56-42de-b67e-fd8cc54af219)

![Screenshot 2023-09-08 at 12 23 39](https://github.com/Shelf-nu/shelf.nu/assets/76112272/71ab1830-9097-4079-8bb2-c634efccc87d)

![Screenshot 2023-09-08 at 12 24 37](https://github.com/Shelf-nu/shelf.nu/assets/76112272/528dcb37-2d21-47b2-a703-6b1692c6ab04)

- [x] Add "Status' badge in table cell in Asset index

![Screenshot 2023-09-08 at 12 27 35](https://github.com/Shelf-nu/shelf.nu/assets/76112272/edb9afe6-f686-46ac-bb63-79b0921ba6ae)

- [x] Can we increase the left / right padding for 'Tag' badges to 8px

![Screenshot 2023-09-08 at 12 33 48](https://github.com/Shelf-nu/shelf.nu/assets/76112272/9c3bf14b-c359-4592-9a1e-e09c3a8bf974)
![Screenshot 2023-09-08 at 12 33 05](https://github.com/Shelf-nu/shelf.nu/assets/76112272/1ccac65d-e79a-425e-88c3-34019c65fc3d)
![Screenshot 2023-09-08 at 12 32 38](https://github.com/Shelf-nu/shelf.nu/assets/76112272/2e26c815-decf-4bfa-ab5b-ec234c70e847)

**Comment by DonKoko** [comment]
@hunar1312 could you take care of adjusting those styles globally please? Thanks

**Comment by DonKoko** [comment]
@jurrejansen its deployed.

**Comment by jurrejansen** [comment]
Hi @hunar1312 few things

- [ ] Padding is 6px / 8px for category badges. Because the badge had a dot before. Please change to 8px / 8px

- [ ] For category badges change top and bottom padding to 2px to keep consistent with other badges

![Screenshot 2023-09-12 at 11 29 18](https://github.com/Shelf-nu/shelf.nu/assets/76112272/1be618ca-e0a8-46cc-8829-9d22413f3239)

- [ ] Custodian badges have a 6px / 6px padding, please change to 8px / 8px for consistency with all other badges

![Screenshot 2023-09-12 at 11 35 40](https://github.com/Shelf-nu/shelf.nu/assets/76112272/1f094b5c-a14b-4ad0-a6ba-3975c54d442b)

Sorry to be this precise, but if you're gonna do the stuff above I guess this can taken into account as well.

- [ ] Decrease the dot in the badges that have a dot to 6px x 6px. In Figma the dot has a little padding that shouldn't be taken into account.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/36b79ce5-8507-43e0-a903-a2cde6d76fc9

- [ ] Also change category badges in the Category index, missed this one

![Screenshot 2023-09-12 at 11 44 02](https://github.com/Shelf-nu/shelf.nu/assets/76112272/2378c7b6-a0f8-4166-ae37-fee19f550db7)

- [ ] The dots are still there in the Category filter dropdown

![Screenshot 2023-09-12 at 11 43 49](https://github.com/Shelf-nu/shelf.nu/assets/76112272/343b127b-e67c-416f-bbf0-e985ace003b9)

**Comment by hunar1312** [comment]
@jurrejansen @DonKoko https://github.com/Shelf-nu/shelf.nu/pull/350 resolves this
sorry @jurrejansen for missed points

**Comment by hunar1312** [comment]
This one is completed and merged @jurrejansen

**Comment by jurrejansen** [comment]
Looks good, thanks!
