### ISSUE TITLE
[Improvement request]: Add 'Location' column + rearrange order of columns

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#349]
### Contact Details

jurre @shelf.nu

### Is your feature request related to a problem? Please describe?

@DonKoko maybe this can be picked up by @hunar1312 ?

User are unable to see the location of an asset while inspecting the asset index.

### Describe the solution you'd like

- [x] Add a 'Location' column in the index displaying the location of an asset.

![Screenshot 2023-09-12 at 12 17 28](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a2c67cf7-a169-4ae8-9e51-cea3f36adaa7)

- [x] Rearrange columns like in the design above: Category | Tags | Custodian | Location

**Comment by carlosvirreira** [comment]
I close this issue, this request will be bundled with another issue.

**Comment by carlosvirreira** [comment]
@jurrejansen @DonKoko the user wanted to be able to have an overview of the assets on each location. 

If the user can search on the search field and 'filter' by this location. Then he can achieve his/her goal of quickly seeing where things are. 

If there is no filter or search for this on index then this adds very little to no value.

**Comment by DonKoko** [comment]
@carlosvirreira please look at https://github.com/Shelf-nu/shelf.nu/pull/345. We are combining this columns with it.

**Comment by carlosvirreira** [comment]
ok nice thank you for notifying me

**Comment by DonKoko** [comment]
This will be resolved by PR #345

**Comment by DonKoko** [comment]
@jurrejansen this is live. LMK if there are some issues.
