### ISSUE TITLE
[Bug]: [Mobile] Tags are showing on mobile which breaks the view

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#351]
### Contact Details

jurre@shelf.nu

### What happened?

@hunar1312 

![Screenshot 2023-09-12 at 15 42 03](https://github.com/Shelf-nu/shelf.nu/assets/76112272/dded45c4-5f46-4128-9f58-86025bc15809)

Steps to reproduce:

1. Go to 'app.shelf.nu'
2. See error

### What is the expected behaviour?

Tag badges should be hidden on mobile breakpoint

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by DonKoko** [comment]
@jurrejansen yeah my bad. I broke that. Fix is being deployed: https://github.com/Shelf-nu/shelf.nu/actions/runs/6161218750
