### ISSUE TITLE
[Bug]: Search 'close' button / action positioned wrongly 

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#356]
### What happened?

Steps to reproduce:

1. Go to 'Asset index'
2. Click on 'search bar'
3. Perform a search

<img width="1104" alt="Screenshot 2023-09-13 at 11 23 59" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/48fcf002-e180-46cb-8e06-0ce235b2a4f5">

### What is the expected behaviour?

Show the 'X' on the correct place. 

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by DonKoko** [comment]
@carlosvirreira its already being fixed. Thanks for reporting.
