### ISSUE TITLE
Hosting solution

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#36]
We are currently hosting on fly.io with the stack based on supa-fly.

As I quite used to vercel and I love their per-branch links and deployment, I am considering hosting the live app on vercel. 
Found this repo: https://github.com/vercel-labs/remix-on-the-edge
Could be an interesting this to consider.

**Comment by carlosvirreira** [comment]
Little stars but good contributors. Could be interesting. A bit hard for me to grasp now maybe we can call discuss it.

**Comment by DonKoko** [comment]
Yeah i found it because of following one of the guys that work on the deployment stuff in vercel. Just keeping it here as a backlog when we decide to release v1.

**Comment by DonKoko** [comment]
For now we will stick with long-running servers as we are also using SSE. What we have to do in the future is look into Kent's stack and see how to implement deployment to different regions on fly.io
