### ISSUE TITLE
[Feature request]: Additional custom fields

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#362]
### Is your feature request related to a problem? Please describe?

We have released a custom field area, we currently have one field. The type is 'Text'

<img width="897" alt="Screenshot 2023-09-15 at 13 34 18" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/2b215b08-763f-404e-bcc0-d4eba20fdd32">

We want to create more custom field types:

**Most valuable**
- Select (Single select / AKA: Dropdown)
- Boolean
- Date (Check https://ui.shadcn.com/ for a component as this is integrated)

**Still valuable but slightly less**
- Multi line text

### Describe the solution you'd like

Add custom field types and validations on our custom field area (under settings)

We have designs ready. 

https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?type=design&node-id=7291-376406&mode=design

**Comment by DonKoko** [comment]
I want to add something picker. So we use the shadcn implementation of radix. Check the link to see it. For the Datepicker it is composed of 2 other components that need to be implemented:
- Popover - https://ui.shadcn.com/docs/components/popover#installation
- Calendar - https://ui.shadcn.com/docs/components/calendar#installation

In the implementation details you will see there are 2 ways. We use the **manual** approach as it allows for more customization. You can see how we did it in some other components we implemented such as dropdown for example.

**Comment by carlosvirreira** [comment]
Nice to collaborate once again on another issue @mahendraHegde

**Comment by DevGajjar28** [comment]
@carlosvirreira  Can you explain what exactly you want , I would like to work

**Comment by carlosvirreira** [comment]
hi @DevGajjar28 this is already being worked on by @mahendraHegde so the issue is already being picked up. Perhaps you can look at another issue? 

You can always join us on Discord! https://discord.gg/aANTrYhD

**Comment by jurrejansen** [comment]
@mahendraHegde @DonKoko 

FUNCTIONAL

- [ ] When adding a 'Date' custom field and setting it on required I am able to create an asset without filling the 'Date' field


I'm not really happy with some copy and some styling things

- [ ] Change copy

![Screenshot 2023-09-28 at 11 27 02](https://github.com/Shelf-nu/shelf.nu/assets/76112272/246e69ba-f16a-4524-8221-38c5d453d865)

![Screenshot 2023-09-28 at 11 36 35](https://github.com/Shelf-nu/shelf.nu/assets/76112272/983f8cbe-cd2b-4ff9-9640-9a7225fd1f68)

- [ ] Can we change to order types when selecting a field type

- Single-line text
- Multi-line-text
- Option
- Boolean
- Date

- [ ] Can we style the date picker button like a secondary button. Currently the button is not following the styles of the design system. Also showing different button text color or desktop and mobile. We can keep the date picker the same for now

![Screenshot 2023-09-28 at 11 23 07](https://github.com/Shelf-nu/shelf.nu/assets/76112272/35306f26-fd55-4e09-8119-6a57a9807beb)

**Comment by DonKoko** [comment]
@mahendraHegde this is all good. Can you make a PR from your branch with all the changes to `main`. Thanks.

**Comment by DonKoko** [comment]
This is live. Closing issue.
