### ISSUE TITLE
Implement Error and Catch boundries

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#37]
We need to implement it Error and Catch boundaries for the whole app.

https://remix.run/docs/en/1.14.3/route/error-boundary
https://remix.run/docs/en/1.14.3/route/catch-boundary

**Comment by carlosvirreira** [comment]
Seems like a great initiative!

**Comment by DonKoko** [comment]
We also need to handle 404's for stuff like the item page as they are not working out of the box,.

**Comment by DonKoko** [comment]
Okey to handle this we have a few things:

- [ ] Create a 404 component
- [ ] Create a 500 component (optionally on all servers except production, it should render the actual error)
- [ ] Handle errors on Root level
- [ ] Handle Errors also on layout level
