### ISSUE TITLE
[Feature request]: Support SAML 2.0 for our application

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#376]
### Is your feature request related to a problem? Please describe?

One of our users has requested the ability for their staff to view and manage assets assigned to them within Shelf. (Note: We do not have these views at all as shelf is currently working for a single asset manager but we still want to explore this initiative.)

To accommodate this request, we are exploring the possibility of implementing Single Sign-On (SSO) using Security Assertion Markup Language (SAML) 2.0. Our user's organization currently utilizes Google Workspace, which aligns with Supabase's supported identity provider (IdP) for SAML 2.0 integration.

https://supabase.com/docs/guides/auth/sso/auth-sso-saml
https://supabase.com/blog/supabase-auth-sso-pkce#single-sign-on-support-using-saml-20

One of the requirements for this, is to have a PRO subscription with Supabase. We have this, so we should be ok to proceed in theory. 

If you have worked on this or have experience on it. Do let us know as we could discuss a bounty for this initiative.

### Describe the solution you'd like

Ideally a SAML 2.0 solution that integrates well with our stack.

**Comment by 5war00p** [comment]
Look into this: https://boxyhq.com/guides/jackson/frameworks/remix
And @boxhq/jackson supports to use postgres: https://boxyhq.com/guides/jackson/frameworks/remix

**Comment by DonKoko** [comment]
hey @5war00p. Thanks for the suggestion. We already checked Boxy but we dont really need it as Supabase already has SSO which is quite forward to implement, so implmentation will have to be done with that.

**Comment by ezhil56x** [comment]
@carlosvirreira I'm interested on work on this issue. I don't have Supabase pro. Any workaround will be helpful to develop and test the SAML 2.0 properly ✨

**Comment by DonKoko** [comment]
hey @ezhil56x . Thanks for showing interest in this. 
You should be able to use SAML if you self host supabase. https://supabase.com/docs/guides/self-hosting

I personally haven't tested it but I heard its quite an easy setup.

**Comment by ezhil56x** [comment]
@DonKoko I have tried selfhosting supabase but I couldn't an option to integrate SAML SSO when selfhosted in supabase. It would be really helpful if you can guide me to set it up

**Comment by DonKoko** [comment]
hey @ezhil56x, I haven't tested self-hosting supabase, however I would love to help you. 
So I checked this article: https://supabase.com/blog/supabase-auth-sso-pkce#single-sign-on-support-using-saml-20 and It clearly says this:
> This feature is available for the [Pro-plan and above](https://supabase.com/pricing), starting today. This will also be available on the self-hosted version.

So it should be possible for self hosted. Do you have some more info about what issue you are facing. If you share it I can ask around and try to help you get it going.

**Comment by ezhil56x** [comment]
@DonKoko, 

Self-hosted Supabase uses GoTrue for authentication [supabase.com/docs](https://supabase.com/docs/guides/self-hosting/docker#architecture)

I think [Netlify's GoTrue](https://github.com/netlify/gotrue) supports SAML SSO but [Supabase's GoTrue](https://github.com/supabase/gotrue) doesn't support SAML SSO, I found this on [supabase.com/docs](https://github.com/supabase/gotrue#inherited-features)

In the meantime I'll also look for a walkaround ✨

**Comment by carlosvirreira** [comment]
Exciting @ezhil56x !

**Comment by DonKoko** [comment]
This can be closed. We already have SSO working.
