### ISSUE TITLE
User picture upload

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#38]
We need to add a user picture upload functionality to the profile.  For now we will be using the [storage service of Supabase](https://supabase.com/docs/guides/storage).

## Checklist
This has multiple aspects related to it that we need to consider:

### 1. Bucket config
- [x] Create bucket - based on the recommendations of supabase, I have decided we will have different buckets for different files. This is also related to policies as something like profile pictures for example might need public SELECT but auth is required for INSERT, UPDATE, DELETE
- [x] Setup policy - just starting with something basic like in the example on supabase docs

### 3. Back-end implementation (CRUD)
- [x] Create an api endpoint for it as it can be called from different places and I don't want to just put it in the edit user route
- [x] Create some re-usable functions and logic to be able to handle uploads of different assets(MVP please)
- [x] Upload the file to the correct bucket and folder
- [x] If there is already a profile picture, remove it after the upload has finished (Here we have to think about filenames and so on, how do we transition from old to new)
- [x] Update the user after the file upload has finished
- [x] Currently we have the whole bucket private but I think I will make it so that SELECT(viewing pictures) is public.
- [x] Optimize the file - we can of course do some front-end validations for file size, but users will still be dropping huge images. We need to optimize them somehow. Maybe use [imagemagick](https://www.npmjs.com/package/imagemagick) or maybe Supabase has something for optimizing but I doubt it. Will look further into it.
- [ ] Can we implement some profanity filters? Just an idea we have to look into it.

### 4. Front-end implementation
- [x] Choose a package(ship fast) to implement drag/drop uploading. So far [react-dropzone ](https://react-dropzone.js.org/) looks like it.
- [x] Implement front-end ux for drag/drop
- [x] Implement UX for click to select file and upload
- [x] Implement a preview of the image that the user has added.
- [x] Implement different states based on fetcher(uploading, uploaded, error)
- [x] Implement disabled state for the Dropzone while an upload is happening
- [ ] Use some type of clean animation for showing the status message. Will make the layout shift a bit smoother

## Design

![image](https://user-images.githubusercontent.com/7840007/227267852-32e9e63c-1649-4e85-b8cc-8ebd288322b6.png)

@jurrejansen based on our discussion on discord, when the user drops the file it uploads immediately but there are a few more things that need to be clarified:

- Positioning - currently the profile picture is positioned within the user details form, however technically they are different and considering that it needs to be uploaded immediately and not when clicking save, it could be confusing for the user. I see 2 soltutions now, please feel free to give suggestions
  - Change the logic so the image gets uploaded as part of the user details save action. This will require some more info messages to be designed such as "Dont forget to save your profile"
  - Think about positioning of the element, maybe below the form.
  
- Success message - where and how do we show the success messages
- Error messages - where and how we show the error messages
- Preview - in the design there is a preview of the current user image. Do we just replace it at the moment that the drop has completed? What if the upload fails, we can revert it quite easily i think using the [Optimistic UI strategy ](https://www.youtube.com/watch?v=vTzNpiOk668&list=PLXoynULbYuEDG2wBFSZ66b85EIspy3fy6)

**Comment by DonKoko** [comment]
Okey so option 1 is not really great, because once the user uploads they will not see the upload thing anymore so they wont be able to upload a new once.
The second one is fine but it will add some layout shift which might not be that great. We can animate the layout shift to make it smoother.
Also doing the % is kind of a biatch. So maybe we can just use a lottie?

**Comment by DonKoko** [comment]
Just placing here some examples of uploading to supabase storage in remix: 
https://makerkit.dev/docs/remix-supabase/uploading-data-to-storage
https://dev.to/aaronksaunders/how-to-upload-to-storage-buckets-and-write-data-with-remix-and-supabase-3l7c

**Comment by DonKoko** [comment]
@carlosvirreira @jurrejansen this is deployed and ready for testing. Please test different file format, different file sizes etc. I think its good for now, i cant think of anything we are missing.

**Comment by jurrejansen** [comment]
@DonKoko did a bunch of test uploads and everything seems to work as expected (including errors and stuff). 

Only thing I notice is the width of the upload field (also the rest of fields). Looks cleaner if all the rows have the same max width.

![Screenshot 2023-04-04 at 10 33 37](https://user-images.githubusercontent.com/76112272/229736120-517fa91d-da6b-4761-955f-9a72716cafd9.jpg)

**Comment by DonKoko** [comment]
@jurrejansen solved and deployed. Can you check it please.
