### ISSUE TITLE
[Feature request]: Duplicate asset

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#381]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

In some cases it would save a lot of time if a user would be able to duplicate an asset. E.g. multiple of the same cable. They would create an initial asset, configure the asset (name, category, tags, location), then duplicate that asset multiple times.

### Describe the solution you'd like

Under the 'Actions' dropdown on an asset page, add 'Duplicate'

![Screenshot 2023-09-25 at 12 39 51](https://github.com/Shelf-nu/shelf.nu/assets/76112272/f4b4eaff-d803-44c8-bf6e-d4cd91ff7737)

A modal appears showing the asset you're about to duplicate. It'll also ask if you want to duplicate multiple times.

![Screenshot 2023-09-25 at 13 19 39](https://github.com/Shelf-nu/shelf.nu/assets/76112272/d7ee90c7-3494-4057-8567-d23a52f2c7fb)

After duplicating an asset once (amount = 1) you'll get redirected to the asset page of the newly duplicated asset

After duplicating an asset multiple times (amount = >1) you'll get redirected to the asset index

DESIGNS:

https://www.figma.com/file/2XkiKJ4II7Mux6JJL9hYTm/Shelf-App-%7C-Production-Ready?type=design&node-id=9690-74591&mode=design

**Comment by rockingrohit9639** [comment]
@DonKoko I can work on this issue.

**Comment by carlosvirreira** [comment]
Is this one going well for you @rockingrohit9639 ?

**Comment by rockingrohit9639** [comment]
> Is this one going well for you @rockingrohit9639 ?

Yes @carlosvirreira 
I have raised a PR against this issue. @DonKoko will review it today and if everything is ok, this will be in testing.

**Comment by carlosvirreira** [comment]
Sounds great! Thank you!
