### ISSUE TITLE
[Improvement request]: Option to add avatar image to a team member

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#385]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

Nothing major, it would help with quickly identifying team members from the index and during assigning custody.

### Describe the solution you'd like

Add option to upload a avatar image when creating a team member

![Screenshot 2023-09-25 at 16 32 44](https://github.com/Shelf-nu/shelf.nu/assets/76112272/16831d44-f443-4ff8-9caf-2e5c071dde9c)

![Screenshot 2023-09-25 at 16 32 50](https://github.com/Shelf-nu/shelf.nu/assets/76112272/87e9833c-8f1d-4bad-b9e0-70848ea85999)

This change should be reflected in multiple views

![Screenshot 2023-09-25 at 16 34 05](https://github.com/Shelf-nu/shelf.nu/assets/76112272/6bf7e6d4-001f-4ff0-8afc-c0927a7116b6)

![Screenshot 2023-09-25 at 16 35 30](https://github.com/Shelf-nu/shelf.nu/assets/76112272/7d193b1c-a2df-40b5-8948-a0c1183d70b5)

![Screenshot 2023-09-25 at 16 37 33](https://github.com/Shelf-nu/shelf.nu/assets/76112272/0d70d1f0-520c-4399-99d9-22860d5c0551)

![Screenshot 2023-09-25 at 16 37 41](https://github.com/Shelf-nu/shelf.nu/assets/76112272/7c358d14-90bf-42e9-a7fc-03dbcb813cdb)

![Screenshot 2023-09-25 at 16 41 45](https://github.com/Shelf-nu/shelf.nu/assets/76112272/814d6f27-6ac4-47c2-9cb6-1a914e41be82)

**Comment by carlosvirreira** [comment]
Hi, this is a great issue. However, the drag and drop uploader we had issues with and @DonKoko chose to use the 'normal' uploader. 

So, for the bounty taker. Please use the normal uploader.

**Comment by rockingrohit9639** [comment]
@DonKoko I can work on this issue.
