### ISSUE TITLE
Unknown field tier for select on User

### ISSUE THREAD

**Issue by timvdalen** [Shelf-nu/shelf.nu#386]
### Contact Details

tim@code-orange.nl

### What happened?

Steps to reproduce:

1. Go to Assets

I'm up to date with all migrations from `main`, and I can see the Tiers table in my database.
Is there another upgrade step I'm missing?

### What is the expected behaviour?

See assets

### Version

Self-hosted

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output

```shell
Invalid `prisma.user.findUnique()` invocation:

{
  where: {
    id: 'USERID'
  },
  select: {
?   firstName?: true,
    tier: {
    ~~~~
      include: {
        tierLimit: true
      }
    },
?   id?: true,
?   email?: true,
?   username?: true,
?   lastName?: true,
?   profilePicture?: true,
?   onboarded?: true,
?   createdAt?: true,
?   updatedAt?: true,
?   assets?: true,
?   categories?: true,
?   notes?: true,
?   qrCodes?: true,
?   scans?: true,
?   tags?: true,
?   roles?: true,
?   locations?: true,
?   images?: true,
?   organizations?: true,
?   _count?: true
  }
}


Unknown field `tier` for select statement on model User. Available options are listed in green. Did you mean `id`?

    at Ui.validate (D:\home\tim\werk\shelf.nu\node_modules\@prisma\client\runtime\library.js:148:73)
    at gn.createMessage (D:\home\tim\werk\shelf.nu\node_modules\@prisma\client\runtime\library.js:164:1298)
    at D:\home\tim\werk\shelf.nu\node_modules\@prisma\client\runtime\library.js:177:11600
    at Object.runInChildSpan (D:\home\tim\werk\shelf.nu\node_modules\@prisma\client\runtime\library.js:174:1394)
    at t._executeRequest (D:\home\tim\werk\shelf.nu\node_modules\@prisma\client\runtime\library.js:177:11577)
    at loader34 (D:\home\tim\werk\shelf.nu\app\routes\_layout+\assets._index.tsx:73:16)
    at Object.callRouteLoaderRR (D:\home\tim\werk\shelf.nu\node_modules\@remix-run\server-runtime\dist\data.js:52:16)
    at callLoaderOrAction (D:\home\tim\werk\shelf.nu\node_modules\@remix-run\router\router.ts:3671:16)
    at async Promise.all (index 3)
    at loadRouteData (D:\home\tim\werk\shelf.nu\node_modules\@remix-run\router\router.ts:2993:19) {
  clientVersion: '4.16.2'
}
```

**Comment by timvdalen** [comment]
Okay yeah, I was missing a `npx prisma generate`. What's your internal process for generating prisma?
Should the documentation mention a step for migration + client generation?

**Comment by DonKoko** [comment]
hey @timvdalen . Indeed i think this is an issue related to `npx prisma generate`. 
I do agree with you that we need to find a way to make it easier, in general it always has to be done but I am not sure whats the best way to make it part of the process and make it easy for users like you. Do you have any suggestions? 

I am also wondering if @mahendraHegde maybe has some suggestions. I know he has experience with workflows like this with big teams.

**Comment by timvdalen** [comment]
I've never worked with prisma before but I would expect either:

1. It to run as part of `dev` (which is a bit of a performance hit, but makes it basically always work)
2. There to be some sort of "in case of migrations run this" section in the docs

**Comment by DonKoko** [comment]
@timvdalen I added my idea as an edit of my previous comment just as you were sharing it. So to comment on what you said, i think that will work but I would rather include it in the command you run to deploy the migrations to your db, as conceptually and process wise i think it fits better. So when you deploy your migrations using `npm run db:deploy-migration` we also run `npx prisma generate`

**Comment by DonKoko** [comment]
@timvdalen i have started this but I need to wait for some blockers to be resolved to finalize it. Will let you know when its done.

**Comment by timvdalen** [comment]
No worries, it's not a blocker for me now, just think it might help others later on!

**Comment by DonKoko** [comment]
@timvdalen thanks again for reporting this and the suggestion.
Here is the PR: https://github.com/Shelf-nu/shelf.nu/pull/411
