### ISSUE TITLE
[Feature request]: Bulk edit assets

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#397]
### Is your feature request related to a problem? Please describe?

Bulk edit option in the future so that it could be possible to change location for multiple assets at once.

Bulk edit option in the future so that it could be possible to change location for multiple tags at once.

### Describe the solution you'd like

-

**Comment by DonKoko** [comment]
I think that's a really good idea but we can combine it with some other bulk actions.
What do you guys think should be bulk actions? Here are some ideas:
- Delete
- Assign Category
- Assign tags
- Change/set location
- Archive? ( for that we would need to also think how archived assets are displayed and how the index can be changed between archived and published)

**Comment by jurrejansen** [comment]
Hi @carlosvirreira in theory bulk editing location is already a thing bu tI know what you mean
https://github.com/Shelf-nu/shelf.nu/assets/76112272/aea84a4d-df7a-42b0-959c-93a182bb6073

As for bulk action suggestions:
![Screenshot 2023-11-07 at 16 40 58](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a6b486fc-ac82-44e5-b556-eaeb50f7a522)

As for displaying Archived assets. I consider Archived as a status so if a user wants to see Archived assets they'll use the Status filter. When no Status filter is applied Archived assets will not show in the index.
![Screenshot 2023-11-07 at 16 44 03](https://github.com/Shelf-nu/shelf.nu/assets/76112272/bda8079c-b71a-4ff4-af6f-413e40f97b39)

**Comment by DonKoko** [comment]
Released
