### ISSUE TITLE
[Bug]: Asset name

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#398]
### What happened?

1. Create an asset with name: name 5156
2. Edit asset and remove 5156, hit save
3. Asset list, shows asset name without 5156, all good.
4. Go to asset and click edit. 
5. Name will be: Name 5156, but name field will be just name.
6. Clicking next to the name field it will update the name preview to correct one. 

### What is the expected behaviour?

- 

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
@carlosvirreira deployed.
