### ISSUE TITLE
Serial Number Logging

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#40]
From doing social listening and talking with potential customers. It seems like serial numbers are important for assets. This is not a required field at all, but an optional field which is very beneficial for asset database export and insurance purposes.

@jurrejansen can you please add it to our create page and let me know. Then I can add it to the MVP checklist. 

At the moment, let us make it into a simple text field. Later we can consider making it even more easy/powerful.

Approach | Explanation | UX Considerations | External Libraries
-- | -- | -- | --
OCR Scanner | OCR (Optical Character Recognition) scanner reads text from an image and converts it into machine-readable text. An OCR scanner can be used to capture the serial number from an image of the asset. | The UX should allow the user to upload an image of the asset and highlight the area where the serial number is located. The OCR scanner should be able to detect the serial number automatically and populate the serial number field in the app. | Google Cloud Vision API, Tesseract.js, OCR.Space
Automatic Serial Number Detection | Automatic serial number detection uses computer vision algorithms to detect and extract the serial number from an image of the asset. The algorithm can use techniques such as edge detection, feature extraction, and pattern recognition to locate and extract the serial number from the image. | The UX should allow the user to upload an image of the asset and preview the extracted serial number. The user should have the option to confirm or edit the extracted serial number before it is saved in the database. | OpenCV, TensorFlow, PyTorch

**Comment by jurrejansen** [comment]
Hi @carlosvirreira I've added the Serial No. field and showing it in the MVP views.

![Create Item _ Filled](https://user-images.githubusercontent.com/76112272/230342856-9e442d6f-6260-4028-b06b-a3708869840f.jpg)

Hiding the non MVP fields again

**Comment by DonKoko** [comment]
From what I see from the design this is the view for "New item". You have to remove the id then, as when creating a new item there is no ID until you click create

**Comment by carlosvirreira** [comment]
> Hi @carlosvirreira I've added the Serial No. field and showing it in the MVP views.
> 
> ![Create Item _ Filled](https://user-images.githubusercontent.com/76112272/230342856-9e442d6f-6260-4028-b06b-a3708869840f.jpg)
> 
> Hiding the non MVP fields again

Serial is good, but why do we have non MVP fields there such as: 

Depreciation and Tags?

Can you please remove it?
