### ISSUE TITLE
[Feature request]: Update search field UX

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#400]
### Is your feature request related to a problem? Please describe?

Currently we have quite a powerful search but the UX is not great.

### Describe the solution you'd like

The idea I have is that each search term, when added to the text field and pressing enter(for example), will be added as an active filtering term and displayed as a tag that can be removed later.
This has many benefits:
- cleaner search input
- easier to overview the full filtering list
- super easy to add/remove search terms

@carlosvirreira I already explained that to you and i think you really liked the idea and i think its a nice and not to complex front-end task to do. 
@jurrejansen when you read my explanation, does it make it clear what I want?

@hunar1312 i think we discussed this also with you so I think you also have an idea about it

**Comment by jurrejansen** [comment]
@DonKoko hmm yeah sorta, so will the results match with all the search queries or matching 1 query is enough to show up in results.

I'm not that convinced this will be an improvement. Did you see this UX somewhere? I feel like updating the index after typing query without having to press enter would improve things

**Comment by DonKoko** [comment]
Yeah i think a great example of this UX is adding more people to your email when sending an email.
Also keep in mind that this will not change how the search works, its just a visual improvement.

**Comment by DonKoko** [comment]
This is old and irrelevant approach. Once we decide to improve search, we will have to think of a new approach for this.
