### ISSUE TITLE
[Feature request]: Remove/assign location from quick actions

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#412]
### Is your feature request related to a problem? Please describe?

We have some feedback from users that removing/adding location can be confusing. 

### Describe the solution you'd like

Make it part of quick actions, being able to assing/clear location.

**Comment by DonKoko** [comment]
hey @jurrejansen. Is this something we have considered before? If not can we make a simple design to manage it?

**Comment by jurrejansen** [comment]
Hi @DonKoko this should do the trick. Please ignore other updated UI.

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=107-42253&mode=design

**Comment by DonKoko** [comment]
Looks good. @hunar1312 can you take care of that please.

**Comment by DonKoko** [comment]
@carlosvirreira @jurrejansen this is live. Pls test and re-open if there is any further feedback.

**Comment by jurrejansen** [comment]
Seems to work good. I assume the clear button will be handled globally for these select components when tackling this issue: https://github.com/Shelf-nu/shelf.nu/issues/413

**Comment by hunar1312** [comment]
yes correct @jurrejansen
