### ISSUE TITLE
[Feature request]: Clear location

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#413]
### Is your feature request related to a problem? Please describe?

At the moment, if you go to the edit view of an asset, you cannot clear the current location: 
<img width="883" alt="Screenshot 2023-10-02 at 13 52 23" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/9ad86ba8-9050-42e5-990b-e8ac07ff9f26">

### Describe the solution you'd like

A link/button somwhere in the dropdown or just anywhere in the view that allows to remove the location.

**Comment by DonKoko** [comment]
@jurrejansen could you make a quick and simple design for this? Thanks

**Comment by jurrejansen** [comment]
@DonKoko I'm inclined to go with option 1, don't think we should put extra stuff in dropdown components

OPTION 1

![Screenshot 2023-10-02 at 15 07 49](https://github.com/Shelf-nu/shelf.nu/assets/76112272/ce55eb14-f836-44b2-9199-0cc25588f4c4)

OPTION 2

![Screenshot 2023-10-02 at 15 08 18](https://github.com/Shelf-nu/shelf.nu/assets/76112272/cafb3472-5251-4819-acda-73ce7f3e5e08)

**Comment by DonKoko** [comment]
@jurrejansen I agree. LEts go for option 1. Can you share a figma link please?

@hunar1312 could you take care of this issue please.

**Comment by jurrejansen** [comment]
@hunar1312 here is the link https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=128-233470&mode=design

Please ignore other changes to UI
