### ISSUE TITLE
[Bug]: Mobile usability issues

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#415]
## Issue 1)

> Since adding some of custom fields, some do not display quite right. 
> I realise these are very recent additions so I thought I would let you know. Please see fields below with missing headings on the New Asset interface.
>  I’m using a **OnePlus Nord 5G on Android** should this be useful info.
> 

This we received from a client. Its because of how we manage the labels. They are not working properly on mobile. Here is a screenshot.
![image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/f01a3143-5e8a-494d-a5a8-e927131175d1)
![image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/70d61c4a-38ee-484b-ac72-664bacd58edc)

## Issue 2)

> Cannot grant custodianship of asset on mobile. 

So there are a few issues here. 
1. I cannot even open the dropdown when simulating a mobile on my browser(works on actual phone)
2. There are some alignment issues
![image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/1e75ef18-7528-491a-aaad-8ada255338b3)

3. The UI of the modal/select of giving custody seems totally broken. It seems like it submits when the select changes and that shouldnt be the case. We have a confirm button.

https://github.com/Shelf-nu/shelf.nu/assets/12449255/a130c35e-0619-4d48-8b55-a9b28607994b

**Comment by DonKoko** [comment]
This is fixed and deployed. I also tested it on live. @carlosvirreira @jurrejansen
