### ISSUE TITLE
[Bug]: flicker when opening/closing sidebar

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#419]
### What happened?

Steps to reproduce:

1. Go to shelf
2. Click on minimize sidebar
3. Click on maximize sidebar
4. Notice flicker

I believe its because of different gap between the elements when open/closed

https://github.com/Shelf-nu/shelf.nu/assets/7840007/07426dec-74d5-45bd-a93e-f95687130e86

### What is the expected behaviour?

No flicker

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by imVinayPandya** [comment]
Hey @DonKoko 
Here is the small MR, hopefuly it will fix the sidebar flicker issue.

**Comment by carlosvirreira** [comment]
Thank you! @imVinayPandya !

**Comment by DonKoko** [comment]
Thanks @imVinayPandya.
Merged and live already.
