### ISSUE TITLE
[Feature request]:Setup PWA (Remix-PWA)

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#423]
### Is your feature request related to a problem? Please describe?

I want to use shelf as a PWA on my iPhone

### Describe the solution you'd like

Give me PWA feel for Shelf

**Comment by DonKoko** [comment]
Love the idea. There is a package that can help with that: https://github.com/remix-pwa/remix-pwa
Comes with lots of features and its seems very easy to use with existing apps.

**Comment by DonKoko** [comment]
@kremedev are you still attempting that? I saw you closed your PR. If not please cancel your attempt so someone else can take care of it.

**Comment by 5war00p** [comment]
@DonKoko  what do you think on having pure native implenetation for PWA?

**Comment by carlosvirreira** [comment]
Maybe you can tell us why we should consider this @5war00p ?

**Comment by 5war00p** [comment]
Because it's fun and  easier by doing little bit of research and its straight forward in my opinion. Also it provides more flexbile for doing things like handle own indexedDB for caching API requests, CDNs and static assets.

You can refer one of my PR where I did caching for static assets for a PWA: https://github.com/heyxyz/hey/pull/3876

**Comment by carlosvirreira** [comment]
We got a warning about this > 

"Service worker, once installed, hard to change if you introduce a bug in its code"

What do you think about that statement @5war00p 

Did you encounter this before?

cc @DonKoko

**Comment by 5war00p** [comment]
You can maintain the version for the service-worker script and claims the new worker

**Comment by DonKoko** [comment]
hey @5war00p . First of all welcome to the shelf community and thanks for showing interest in contributing. 
I will be quite happy with our own PWA implementation. Of course with pwa we can go very deep but as a start thats not what we want. As long as our users can take advantage of the basic features of pwa and are able to easily add it to their home screen, we will be happy.
If you want to go ahead, please make an attempt and feel free to open a PR.

**Comment by 5war00p** [comment]
@DonKoko Added PWA config without remix-pwa. I haven't added any service worker, the current config only makes the web app installable on desktops and mobiles.

**Comment by carlosvirreira** [comment]
Sounds promising @5war00p 

Curious about the review.
