### ISSUE TITLE
[Feature request]: Onboarding

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#425]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

New users are not getting an introduction after their first login to their Shelf environment. We should give them a small introduction to help them on their way and already gather some important feedback on how the particular user is planning on using Shelf.

### Describe the solution you'd like

A proper onboarding flow. @carlosvirreira @DonKoko any feedback on the current flow? 

A technical thing I am not sure about. How are we going to store the feedback we're asking the user in one of the steps?

DESIGNS

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=149-118790&mode=design

**Comment by DonKoko** [comment]
Okey this is great, however we have a few things to discuss and handle:
1. Does this happen after our current onboarding process? We still need to collect some user data like we do now. I would expect this process comes after it
2. How do you want to handle the survey and where do we store the results?
3. We need to figure out the UX in those cases:
  - When you skip the process
  - When you complete the process
  - When you want to restart the process

**Comment by carlosvirreira** [comment]
1. Absolutely, this is post our current onboarding. It is more like a pseudo 'user success/get started' tutorial.
2. If we could use something like Formbricks for this or another OS solution. Super helpful. (We are using it on marketing site and works well)
3. UX:
I see two parts of this flow: 
- the info slides
- the checklist process

For info slides > Press skip, skips that slide. No need to allow for a 'restart' of the slides in my opinion.

The checklist process > From what I know, this is a pre-requirement to 'show' the dashboard. So, I think we might as well push for the 'info slides' part of this until @jurrejansen has a clear UI for the dashboard. 

what do you think @DonKoko

**Comment by jurrejansen** [comment]
Hi @hunar1312 I've updated the UX scenario and added some more annotations that should explain the complete process. You can either leave comments in Figma or ask questions in the Discord thread if needed.

**Comment by hunar1312** [comment]
Hey @jurrejansen, Thank you.
