### ISSUE TITLE
[Feature request]: Filter asset index by Status

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#427]
### Is your feature request related to a problem? Please describe?

Currently procuring a better description of this: 

"Is there any way I can see the tools that are in custody" 

### Describe the solution you'd like

Not sure yet, hoping that @jurrejansen can come up with a good UX for this

**Comment by carlosvirreira** [comment]
@DonKoko this works for me, do you have any feedback here? 

Would you consider this a simple / mid / high complexity task? 

Legit curious. No pressure here.

**Comment by DonKoko** [comment]
Once we have the new dropdown its mid-low i would say.

**Comment by carlosvirreira** [comment]
Sounds great to me. Let us see how it goes with the new dropdowns. Thank you for the reply.
