### ISSUE TITLE
[Bug]: URL structure seems to be off for Settings

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#429]
### Contact Details

jurre@shelf.nu

### What happened?

Steps to reproduce:

1. Go to 'app.shelf.nu'
2. Click on 'Settings'
3. Cycle through tabs

https://github.com/Shelf-nu/shelf.nu/assets/76112272/3dc4426a-6d1c-403e-8f92-150d5256fa34

### What is the expected behaviour?

When I look at the actual URLs of the pages I expect the breadcrumbs to also show 'Home > Settings > ... ' just it does for Custom Fields

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by DonKoko** [comment]
I would not call this a bug, we just didnt add the breadcrumbs title, we forgot it. Anyways we will solve it. Thanks for reporting Jurre.

**Comment by DonKoko** [comment]
@jurrejansen merged and deploying.
