### ISSUE TITLE
[Feature request]: Create a default value field for assets 

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#436]
### Is your feature request related to a problem? Please describe?

We want to show on the dashboard the total value of assets of the user database (or workspace database). 

<img width="507" alt="Screenshot 2023-10-06 at 12 04 16" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/fc1c99cc-36d6-418e-b2e8-835375135e2d">

We cannot rely on a custom field for this. So we would like to do it with a standard field on shelf.

### Describe the solution you'd like

On asset create, have a value field - so our users fill it up and we can calculate it.

**Comment by jurrejansen** [comment]
'Value' field has been added to Asset creation form.

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=128-233469&mode=design

User should be able to select preferred currency in the settings

https://www.figma.com/file/8RjvxGnNySRCYsgpSrK0M4/Shelf-App-%7C-Library?type=design&node-id=6706-66211&mode=design

**Comment by DonKoko** [comment]
Looks good. I assigned it to @hunar1312 to look at after onboarding flow.

**Comment by carlosvirreira** [comment]
<img width="969" alt="Screenshot 2023-10-10 at 11 27 10" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/69cb44fd-4a5c-4e4e-b612-0f73c83d915f">

**Comment by DonKoko** [comment]
@hunar1312 here is an enum to add to our DB for currencies. 

```
enum Currency {
  USD  // United States Dollar
  EUR  // Euro
  GBP  // British Pound Sterling
  JPY  // Japanese Yen
  AUD  // Australian Dollar
  CAD  // Canadian Dollar
  CHF  // Swiss Franc
  CNY  // Chinese Yuan
  INR  // Indian Rupee
  ZAR  // South African Rand
  BRL  // Brazilian Real
  MXN  // Mexican Peso
  SGD  // Singapore Dollar
  NZD  // New Zealand Dollar
  SEK  // Swedish Krona
  NOK  // Norwegian Krone
  KRW  // South Korean Won
  RUB  // Russian Ruble
  HKD  // Hong Kong Dollar
  SAR  // Saudi Riyal
}
```

And then within Organization model we should add:

```
currency Currency
```

**Comment by carlosvirreira** [comment]
Excited for this one - necessary for our dashboard building!

**Comment by carlosvirreira** [comment]
Hey @hunar1312 this one is waiting for merging?
