### ISSUE TITLE
[Feature request]: Search in 'give custody' field for custodians

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#440]
### Is your feature request related to a problem? Please describe?

1 user has 30+ team members.

Giving custody not so fast as it should be.

Allowing someone to search for a name will make things much easier.

### Describe the solution you'd like

Ideally we let a user search for a user rather than relying on a dropdown.

**Comment by jurrejansen** [comment]
We would have to change the 'Select custodian' from a dropdown into a input field. Or add a search field to the dropdown menu that appears. Option 1 would be better. Design below.

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=385-125432&mode=design

**Comment by carlosvirreira** [comment]
Got a comment on this today from a user who has 20+ team members - spends a lot of time doing the lookup (he has NRMs) - if not too complex this could be a valuable improvement towards the time it takes for our users to manage their custodianship inventory
