### ISSUE TITLE
[Feature request]: Make category a required field for creating an asset

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#450]
### Is your feature request related to a problem? Please describe?

For dashboard and reporting it is important to have insightful outputs. 

Categories being one of them. 

Ideally when a user creates an asset, it has a default 'uncategorised' category that one can change. 

Alternatively, it can show as a required field, if the user inputs or changes to nothing new it groups it under 'uncategorized'

### Describe the solution you'd like

On asset create, have a dropdown category called uncategorised or allow me to create without category and automatically add the uncategorised category.

**Comment by jurrejansen** [comment]
I guess we'll need to give all assets that don't have a category the 'Uncategorized' category in all databases. Not sure if this will be a hassle to do.

I have adjusted designs + added annotations

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=128-233469&mode=design

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=128-233470&mode=design

**Comment by vineetjk** [comment]
I would like to take this up, assign me

**Comment by DonKoko** [comment]
Okey so I thought about this and I have a suggestion.
Looking at the goal which is for dashboard reporting, I don't think I want to make any db changes and add a category called `uncategozed` as that involves quite some changes and cases to handle that I don't want to deal with as it introduces unnecessary overhead.

How we can handle it is simply by doing it on the front-end. So we have to do a few things:
1. Create a component for category badge, that simply renders the category badge for `uncategorized` when there is no category assigned.  Here is an example how we use it now: https://github.com/Shelf-nu/shelf.nu/blob/main/app/routes/_layout%2B/assets.%24assetId.tsx#L249-L251C29 . Keep in mind its also used on the asset index so it needs to be adjusted there as well.
2. Set the default(empty) value of the category select in the asset form to `uncategorized`.

I think that should be enough to handle it. @vineetjk let me know if there are any questions. You can also always join our discord if you want to discuss something.

**Comment by carlosvirreira** [comment]
Good luck @vineetjk 

Please feel free to join us here: https://discord.gg/cAEY9S4n

**Comment by carlosvirreira** [comment]
> Okey so I thought about this and I have a suggestion. Looking at the goal which is for dashboard reporting, I don't think I want to make any db changes and add a category called `uncategozed` as that involves quite some changes and cases to handle that I don't want to deal with as it introduces unnecessary overhead.
> 
> How we can handle it is simply by doing it on the front-end. So we have to do a few things:
> 
> 1. Create a component for category badge, that simply renders the category badge for `uncategorized` when there is no category assigned.  Here is an example how we use it now: https://github.com/Shelf-nu/shelf.nu/blob/main/app/routes/_layout%2B/assets.%24assetId.tsx#L249-L251C29 . Keep in mind its also used on the asset index so it needs to be adjusted there as well.
> 2. Set the default(empty) value of the category select in the asset form to `uncategorized`.
> 
> I think that should be enough to handle it. @vineetjk let me know if there are any questions. You can also always join our discord if you want to discuss something.

Thanks for the suggestion. It sounds great.

**Comment by vineetjk** [comment]
@DonKoko Thank you for yours inputs :)

@carlosvirreira sure I will join

**Comment by DonKoko** [comment]
hey @vineetjk . I had to unfortunately revert those changes because we had some crashes in live.
So I checked it and I noticed that we have different places where we update asset, we dont only do it in the updateAsset form. You can for example check the file refresh-main-image.

So we need to adjust how the update function works. WE will have cases when we are updating and we are not passing a categoryId but we dont want the category to be disconnected.

Maybe what you can try is to use null.
So if categoryId is:

    undefined - we dont do anything
    null - we disconnect.

Then we will have to simply make sure that the value of categoryId when updating an asset and setting the category to Uncategorized is passed as null.

Please also search around the codebase and see for other places we are updating asset, as we have to also consider it there. I took a quick look and there is a few places where we use updateAsset so they all have to be tested.
