### ISSUE TITLE
[Feature request]: Administrators can configure PDF template documents used for assigning Custody and Bookings

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#462]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

As an IT manager, whenever I check out an asset to an employee. I want to have the option to enhance the 'formality' of the checkout. Recording the date/time/IP address and signature of an employee that received an asset from me would do this. In case this employee leaves the company. We can then rightfully request the return of all the assets that he / she got access and signed off for.

### Describe the solution you'd like

Administrators can navigate to Settings > Templates to manage PDF templates that can be used for assigning Custody and Bookings. A PDF template has the following fields.

- Type* | Indicates for what the template will be used (Custody, Bookings, ...)
- Name* 
- Signature | A toggle to specify if a signature is required
- Description
- Upload PDF* | Here the PDF document can be uploaded that will be shown to custodian for reading (and signing)

DESIGNS
https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=544-176481&mode=design

**Comment by jurrejansen** [comment]
@carlosvirreira @DonKoko any comments here?

**Comment by carlosvirreira** [comment]
It is pretty clear to me. 

**Note** for the future bounty attempter. You might see there some styles that are new layout wise. I want to ask you to please ignore them and focus on the new dashboard setting tab and the fields inside of it only. 

This bounty is part of a bigger epic (collect signatures for custody assignments).

Any questions about this bounty can be discussed on our Discord: https://discord.gg/nGdu8zHG

**Comment by rajdip-b** [comment]
@jurrejansen hey, can you please specify the `type` names of the templates?

**Comment by jurrejansen** [comment]
Hi @rajdip-b , thanks for reaching out

User needs to select a type to indicate for what the template will be used. For now the only 2 options for template type will be **Bookings** and **Custody**. 

However, Bookings functionality is currently not built yet. Is it possible to hide the Bookings type after you've finished? So we can easily unhide when we eventually need it.

**Comment by rajdip-b** [comment]
Hey @jurrejansen, yes surely I can do that. So in the testing phase, I can very well disable the selection field and hard code the value (just temporarily). Think that will be ok?

**Comment by jurrejansen** [comment]
Hi @rajdip-b , is it also possible to not disable the select field but only show the **Custody** option and hide the **Bookings** option?

**Comment by rajdip-b** [comment]
Yeah surely, that can be done.
