### ISSUE TITLE
Chore: Upgrade prisma to 5.x

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#466]
### Is your feature request related to a problem? Please describe?

There are huge performance improvements with prisma 5 so we should upgrade.

### Describe the solution you'd like

Upgrade to 5.x

**Comment by mahendraHegde** [comment]
@DonKoko  plz assign this to me.

**Comment by DonKoko** [comment]
This was done as part of the Teams functionality release
