### ISSUE TITLE
[Server update]: Create a custom server and auth/cookie middleware 

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#467]
### Is your feature request related to a problem? Please describe?

We are currently using the default server from remix which works but its not customizable. If we want to add our own middleware we need to consider making a custom server.
When we do a custom server we will be able to:
- create auth middleware
- create cookie setting middleware

This way we dont have to worry about committing the session or protecting each route. We can just manage it via the middleware.

### Describe the solution you'd like

After discussing it with some community members I was recommended to use Hono due to it being super easy to test and build middleware for. https://github.com/sergiodxa/remix-hono

Once we have the server working we can create the middleware to add. I already have examples that I can share once we get there.

**Comment by rajdip-b** [comment]
On it

**Comment by DonKoko** [comment]
@rajdip-b okey we have the server working, we need to make the protect middleware part now, which was the main reason we did this. Here is a list of what we still need to do in my mind.

1. Enable protect middleware. This basically works already, just needs to be added. We also need to add the array of `publicRoutes`
2. remove `requireAuthSession` from within `requirePermision`
3. We will now be getting the session data like this:
```ts
export async function loader({ context }: LoaderFunctionArgs) {
    const { username, userId } = context.getSession();
...
```
so we need to adjust `requirePermission`. We have to decide weather we pass directly the `userId` or we just pass the whole context or just the `userId`. I think it might be better to just pass the `userId`. 
4. CHange the returns of `requirePermission`. Should not return the `authSession` anymore as we dont need it. I also dont think it should return `userId` as we will be getting that from the context as in the example above
5. We need to go to every loader/action, change the props to include context and adjust how we get the `userId` and how we call `requirePermision`

**Comment by DonKoko** [comment]
Progress:

### Routes:

- [ ] ./api+/user.prefs.upload-user-photo.ts
- [ ] ./api+/$organizationId.qr-codes[.zip].ts
- [ ] ./api+/public-stats.ts
- [ ] ./api+/utils.parse-markdown.ts
- [ ] ./api+/user.prefs.dismiss-support-banner.ts
- [ ] ./api+/user.prefs.minimized-sidebar.ts
- [ ] ./api+/image.$imageId.ts
- [ ] ./api+/user.change-current-organization.ts
- [ ] ./api+/sse.notification.ts
- [ ] ./api+/asset.refresh-main-image.ts
- [ ] ./api+/oss-friends.ts
- [ ] ./api+/user.prefs.skip-onboarding-checklist.ts
- [ ] ./api+/admin.export-org-assets.$organizationId.$fileName[.csv].tsx
- [ ] ./api+/admin.import-org-assets.$organizationId.tsx
- [ ] ./api+/stripe-webhook.ts
- [ ] ./api+/client-notification.ts

---

- [ ] ./_welcome+/onboarding.tsx
- [ ] ./_welcome+/_layout.tsx
- [ ] ./_welcome+/welcome.tsx
- [ ] ./_layout+/$.tsx

---

- [ ] ./_layout+/settings.tsx
- [ ] ./_layout+/assets._index.tsx
- [ ] ./_layout+/assets.$assetId.qr.tsx
- [ ] ./_layout+/assets.$assetId.give-custody.tsx
- [ ] ./_layout+/assets.$assetId.update-location.tsx
- [ ] ./_layout+/assets.export.$fileName[.csv].tsx
- [ ] ./_layout+/assets.new.tsx
- [ ] ./_layout+/assets.$assetId.note.tsx
- [ ] ./_layout+/assets.import.tsx
- [ ] ./_layout+/assets.$assetId_.edit.tsx
- [ ] ./_layout+/assets.$assetId.duplicate.tsx
- [ ] ./_layout+/assets.$assetId.tsx
- [ ] ./_layout+/assets.$assetId.release-custody.tsx
- [ ] ./_layout+/assets.tsx

---

- [ ] ./_layout+/locations.new.tsx
- [ ] ./_layout+/locations.$locationId.add-assets.tsx
- [ ] ./_layout+/locations.tsx
- [ ] ./_layout+/locations.$locationId_.edit.tsx
- [ ] ./_layout+/locations.$locationId.tsx
- [ ] ./_layout+/locations._index.tsx

---

- [ ] ./_layout+/admin-dashboard+/$userId.tsx
- [ ] ./_layout+/admin-dashboard+/org.$organizationId.tsx
- [ ] ./_layout+/admin-dashboard+/users.tsx
- [ ] ./_layout+/admin-dashboard+/_layout.tsx
- [ ] ./_layout+/admin-dashboard+/announcements.tsx
- [ ] ./_layout+/admin-dashboard+/announcements.new.tsx

---

- [ ] ./_layout+/dashboard.tsx

---

- [ ] ./_layout+/bookings.new.tsx
- [ ] ./_layout+/bookings.tsx
- [ ] ./_layout+/bookings.$bookingId.tsx
- [ ] ./_layout+/bookings.$bookingId.add-assets.tsx

---

- [ ] ./_layout+/settings.custom-fields.$fieldId_.edit.tsx
- [ ] ./_layout+/settings.general.tsx
- [ ] ./_layout+/settings.team.invite-user.tsx
- [ ] ./_layout+/settings.custom-fields.index.tsx
- [ ] ./_layout+/settings.custom-fields.tsx
- [ ] ./_layout+/settings.index.tsx
- [ ] ./_layout+/settings.custom-fields.new.tsx
- [ ] ./_layout+/settings.team.add-member.tsx

---

- [ ] ./_layout+/categories.new.tsx
- [ ] ./_layout+/categories.tsx
- [ ] ./_layout+/categories.$categoryId_.edit.tsx

---

- [ ] ./_layout+/tags.tsx
- [ ] ./_layout+/tags.$tagId_.edit.tsx
- [ ] ./_layout+/tags.new.tsx

---

- [ ] ./_layout+/settings.subscription.customer-portal.tsx
- [ ] ./_layout+/settings.subscription.tsx
- [ ] ./_layout+/settings.team.tsx
- [ ] ./_layout+/settings.workspace.tsx
- [ ] ./_layout+/settings.workspace.index.tsx
- [ ] ./_layout+/settings.workspace.$workspaceId.edit.tsx
- [ ] ./_layout+/settings.workspace.new.tsx
- [ ] ./_layout+/settings.account.tsx

---

- [ ] ./_layout+/_layout.tsx

---

- [ ] ./_auth+/login.tsx
- [ ] ./_auth+/join.tsx
- [ ] ./_auth+/oauth.callback.tsx
- [ ] ./_auth+/_auth.tsx
- [ ] ./_auth+/logout.tsx
- [ ] ./_auth+/send-magic-link.tsx
- [ ] ./_auth+/accept-invite.$inviteId.tsx
- [ ] ./_auth+/resend-email-confirmation.tsx
- [ ] ./_auth+/reset-password.tsx
- [ ] ./_auth+/forgot-password.tsx
- [ ] ./_auth+/verify-email.tsx

---

- [ ] ./healthcheck.tsx

---

- [ ] ./qr+/$qrId_.not-logged-in.tsx
- [ ] ./qr+/$qrId.tsx
- [ ] ./qr+/route.tsx
- [ ] ./qr+/$qrId_.contact-owner.tsx
- [ ] ./qr+/$qrId_.link.tsx
- [ ] ./_index.tsx

**Comment by DonKoko** [comment]
This has been completed and released already long time ago.
