### ISSUE TITLE
[Bug]: Blank screen appears when you scan qr of an asset which doesn't exist in your system

### ISSUE THREAD

**Issue by hunar1312** [Shelf-nu/shelf.nu#485]
### What happened?

Steps to reproduce:

1. open in app qr scanner
2. scan a qr code of an asset which is deleted or someone's asset's qr of shelf (basically a qr whose id doesnt exist in your db)
3. a blank screen with shelf's logo is shown

![image](https://github.com/Shelf-nu/shelf.nu/assets/129367263/9e95bbee-3d44-46bd-b2a4-feba4e656f30)

### What is the expected behaviour?

A UI screen that addresses the user properly about this use case.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by carlosvirreira** [comment]
Thank you for reporting this bug, @hunar1312 we will make a design for it and assign it.

**Comment by DonKoko** [comment]
@carlosvirreira hmm this case should be handled already. I think its a bug related to the scanner inside the app. Would need to test it to debug it.

**Comment by DonKoko** [comment]
This has been resolved in #875
