### ISSUE TITLE
[Bug]: Scan QR button works only once

### ISSUE THREAD

**Issue by hunar1312** [Shelf-nu/shelf.nu#489]
### What happened?

Steps to reproduce:

1. Go to In-app QR code scanner button (placed in the header)
2. Click on the button and scan an asset's QR 
3. After that try clicking on the button
4. It won't work

### What is the expected behaviour?

The QR scanner should function everytime the user clicks on it but currently it works only once per session

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by carlosvirreira** [comment]
On safari (PWA) I have encountered this issue lately a lot. It seems to indeed get bugged after the first scan.

**Comment by DonKoko** [comment]
Should be resolved by  #796

**Comment by DonKoko** [comment]
Resolved by #796
