### ISSUE TITLE
[Question]: Why can't I give custody of my asset to an admin? 

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#491]
### Is your feature request related to a problem? Please describe?

I am on a personal workspace. I have non registered members. 

Some assets are under my custody. I do not understand why I cannot select myself from the custodianship list.

### Describe the solution you'd like

Allow to add my name (admin) on a custody of an object.

**Comment by carlosvirreira** [comment]
Perhaps on the dropdown of user it reads. 

"{{Admin_full_name}} (You)"

**Comment by jurrejansen** [comment]
It wasn't described in the initial issue. I had included it as UX in the designs. Made a scenario for it now. Suggestion from Carlos could also work if that is less hassle to implement.

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=875-10311&mode=design

**Comment by carlosvirreira** [comment]
For whoever attempts this bounty: Use our default styles.

So, do not do any UI work just use what is available.

**Comment by kremedev** [comment]
@Dhoni77 I'm not sure but this should be fixed with their new launch of Teams
