### ISSUE TITLE
Items index

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#50]
Some pending stuff:

- [ ] ~shortcut to focus on field~
- [x] Next button is not working when on page 0/1
- [x] add current items found vs total items in DB

**Comment by jurrejansen** [comment]
@DonKoko couldn't really find anything major at this point.

- [ ] Image thumbnails in index are distorted, set to cover with aligment center center?

![Screenshot 2023-04-04 at 10 47 20](https://user-images.githubusercontent.com/76112272/229739273-5d0afc49-7f56-4ec7-b795-6b73bc535c84.jpg)

**Comment by DonKoko** [comment]
> [ ] Image thumbnails in index are distorted, set to cover with aligment center center?

Yeah good one. I think i forgot to do it there. Thanks. I will let you know when its solved.

**Comment by DonKoko** [comment]
@jurrejansen solved and deployed. Please check it.

**Comment by DonKoko** [comment]
Search field needs to be updated. We need some loading indicator while searching.

**Comment by jurrejansen** [comment]
@DonKoko 

![Index _ Search _ Loading](https://user-images.githubusercontent.com/76112272/230614394-d06ae738-57b6-4a17-9276-0531554eda03.jpg)
