### ISSUE TITLE
[Feature request]: Dashboard

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#500]
### Is your feature request related to a problem? Please describe?

I want to see an overview of my workspace with some useful stats

### Describe the solution you'd like

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=595-32887&mode=design&t=48fVU8pa68ptCrGf-0

**Comment by DonKoko** [comment]
@hunar1312 dashboard is deployed but we are still missing a few things:
- [ ] fallback for charts for SSR
- [ ] suggestions/recommended actions when visiting dashboard for the first time

**Comment by hunar1312** [comment]
@DonKoko I'm working on the actions when visiting dashboard for the first time and should be ask @jurrejansen for creating a placeholder animation/graphic for fallback for charts in dashboard
