### ISSUE TITLE
Team Related feedback and bugs

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#522]
Collection of issues we found when testing new teams functionality:

- [x] Notes for changing custody are assigned to the person who created the asset instead of the person performing the action
![Screenshot 2023-11-01 at 17 27 09](https://github.com/Shelf-nu/shelf.nu/assets/7840007/a575e676-370b-438a-9e77-8d42c2f8396b)

**Comment by carlosvirreira** [comment]
- [ ] - We have the issue with locations that if you make one and click add location you get the old name there as a placeholder. So instead of ‘Untitled location’ it shows you the previous location name as a placeholder (Confusing)
- [ ] Same issue as above but with Custom Fields

**Comment by DonKoko** [comment]
> - We have the issue with locations that if you make one and click add location you get the old name there as a placeholder. So instead of ‘Untitled location’ it shows you the previous location name as a placeholder (Confusing)
Same issue as above but with Custom Fields

@hunar1312 we had this issue also with assets right? I thought we found a fix already. Can you check it please?

**Comment by hunar1312** [comment]
yeah, I'll fix that. @DonKoko

**Comment by DonKoko** [comment]
@carlosvirreira issue with title when creating a new item is solved. We made a more long term solution that should be perfectly applicable to any model where we need to use this pattern.

**Comment by carlosvirreira** [comment]
thanks guys
