### ISSUE TITLE
[Overview]: Automated emails

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#526]
### Is your feature request related to a problem? Please describe?

As we're moving forward notifying our users gets more important. I would like to create an overview here of the various parts of the application that need email notifications. These email notifications are for informing the user or requesting an action from them.

**Magic Link**
- [ ] Login

**Email Confirmation**

**Forgot Password**

**Notes** (Perhaps change naming into Updates or something similar)
- [ ] Comments
- [ ] Notification (updates in Custody, Location, GEO Location, etc.)

**Custody**

- [ ] As a custodian I want to receive an automated email notification when I was assigned custody over an asset
- [ ] As a custodian I want to receive an automated email notification when my custody over an asset was released

**Bookings** https://github.com/Shelf-nu/shelf.nu/issues/563

- [x] As a custodian I want to receive an automated email notification when I have successfully reserved 1 or more assets via the bookings area 
- [x] As a custodian I want to receive an automated email notification when it is almost time to pick up the assets I have reserved via the bookings area
- [x] As a custodian I want to receive an automated email notification when it is almost time to return the assets I have reserved via the bookings area
- [x] As a custodian I want to receive an automated email notification when the status of my booking has changed into Overdue
- [x] As an admin I want to receive an automated email notification when a student successfully reserved 1 or more assets via the bookings area
- [ ] As an admin I want to receive an automated email notification when it is almost time to handover assets that are included in a bookings
- [ ] As an admin I want to receive an automated email notification when the status of a booking has changed into Overdue

**Signing**
- [ ] Sign invitation (custodian)
- [ ] Sign success (admin)

**Workspace** (Team)
- [x] Invited
- [ ] Revoked

Asset Scan
- [ ] Asset found (owner)
- [ ] Assetn found (reporter)

### Describe the solution you'd like

Automated emails

**Comment by DonKoko** [comment]
This is very outdated issue and most of those are already solved or irrelevant. Closing.
