### ISSUE TITLE
[Improvement suggestions]: Related to shelf for teams

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#527]
### Is your feature request related to a problem? Please describe?

I found a few small improvements we can do to make shelf better. 

Please consider them. 

### Describe the solution you'd like

- On team, let us write down the asset create date as a note and the user.

<img width="516" alt="Screenshot 2023-11-03 at 17 01 50" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/809512de-349a-4170-ae6c-83c59e0ff676">

Context: I wonder, who created this asset and when? Which date/time?

- It would be nice to show the subscription type of the workspace. For instance, I am on TEAM premium. Would be cool to show it - although I do know that - there is no way to get team without paid.

<img width="1074" alt="Screenshot 2023-11-03 at 17 03 40" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/43275ac2-f6d2-4e46-b778-4653bf99f44d">

(perhaps something like: Team (paid) plan active since (date)

- If I am on a team environment and want to create a new user to give custody to an asset. I have a CTA to create team members. This is taking me to Workspaces. I have to then go to team. I feel a lil bit confused. Can we not directly go to the 
current org team tab? On there I see the name of my workspace - which makes me calm.

**Comment by jurrejansen** [comment]
Closing this one, added relevant feedback in https://github.com/Shelf-nu/shelf.nu/issues/916
