### ISSUE TITLE
[Bug]: As a Free tier user that is part of Team workspace I can use Import / Export functionality

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#530]
### Contact Details

jurre@shelf.nu

### What happened?

Steps to reproduce:

https://github.com/Shelf-nu/shelf.nu/assets/76112272/e9da56d9-1a90-4eb5-ad3b-67a9519a1b2e

### What is the expected behaviour?

When switching back to my own Personal workspace I shouldn't be able to use the Import / Export buttons.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by DonKoko** [comment]
I checked it specifically with a new user and cannot re-create what you reported. Then I checked and I can see your user jurre@shelf.nu already has plus so that's why you can import.
