### ISSUE TITLE
Foldable sidebar

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#54]
We need to implement the functionality to make the sidebar foldable.

## Design

Open state:
![image](https://user-images.githubusercontent.com/7840007/229462815-a673a8c7-d1e7-4e7b-a114-42394ee6640f.png)

Closed state:
![image](https://user-images.githubusercontent.com/7840007/229462872-3621774c-8e40-402f-b6b8-e5100c78d62c.png)

@jurrejansen @carlosvirreira 
We are missing some designs related to this, or at least I cannot find them
- How does the user open the folded sidebar?
- How does the user log-out when sidebar is folded?

## Functionality

1. The sidebar closes when clicking the icon on the right of the logo
![image](https://user-images.githubusercontent.com/7840007/229463069-96933747-bcff-45e7-92fa-bb2f3c3a9445.png)
2. The sidebar opens ( we are still waiting for designs for that)
3. The sidebar opening/closing should be animated. I guess we can just do it with css, however we use Framer motion(https://www.framer.com/motion/) maybe that's easier?
4. We should implement a cookie that remembers the user's last state of the sidebar, as we don't want them to have to close it every time. This can also be saved in the DB but for now a cookie is fine.

**Comment by jurrejansen** [comment]
Hi @DonKoko 

I was thinking about taking a similar approach as Mailchimp

https://user-images.githubusercontent.com/76112272/229478659-29fa3409-862f-48c4-898d-193011cc0a00.mov

> How does the user open the folded sidebar?
By hovering over the sidebar -> sidebar expands absolute -> with top right icon the user would be able to keep the sidebar in an open state (when clicked sidebar pushes the main content to the right)

> How does the user log-out when sidebar is folded?
When hovered, the sidebar would always be in an open state

As you can see in the screen recording Mailchimp is not using an animation. I would be happy to prototype one or we can skip (for MVP).

The behaviour described above is a bit different than what I had in mind when doing the designs. Let me know if you're down with this or not. Then I'll update / expand the design where needed.

**Comment by DonKoko** [comment]
Okey i see. I personally find this very annoying functionality with this thing popping in and out the whole time, It just feels not so smooth, but I am open for giving it a test. Thanks for clarifying.

**Comment by hunar1312** [comment]
What are your views on this example of foldable sidebar @DonKoko ? 

Demo: https://www.cssscript.com/demo/smooth-collapsible-sidebar-navigation/
Code: https://www.cssscript.com/smooth-collapsible-sidebar-navigation/

should we follow the same approach?

**Comment by DonKoko** [comment]
@hunar1312 yes, i like that its just a bunch of css. We do have already existing tooling to implement this tho using tailwind. So tailwind has all the classes to manage the folding and twMerge can help you dynamically merge classes.

Here is an example how you can dynamically merge tailwind classes based on a condition: https://github.com/Shelf-nu/shelf.nu/blob/dev/app/components/shared/button.tsx#L46-L48

**Comment by hunar1312** [comment]
Yes will implement that with tailwind only.
also, as of now we will be opening the hidden part of sidebar only on hovering on it?

**Comment by DonKoko** [comment]
Yes please check the comment/video from @jurrejansen above. He explained how it should behave.
