### ISSUE TITLE
[Bug]: I am able to delete team members that have custody over an asset at the time of deletion

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#543]
### Contact Details

jurre@shelf.nu

### What happened?

Steps to reproduce:

1. Go to Settings > Team
2. Delete a team member that currently has custody over an asset
3. There is no modal stating the team member currently has custody over 1 or more assets

https://github.com/Shelf-nu/shelf.nu/assets/76112272/5f624150-4068-49d6-824a-8f92bed6815e

![Screenshot 2023-11-13 at 10 43 10](https://github.com/Shelf-nu/shelf.nu/assets/76112272/f27b9a5a-3132-4a4b-a996-2e494c764142)

### What is the expected behaviour?

Team member should not have custody over any assets before it can be deleted

I remember this was working like described when custody was released

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by DonKoko** [comment]
@jurrejansen very good one. Glad you found it. Its solved and deploying now.
