### ISSUE TITLE
[Feature request]: Link values in custom fields should be actual link in the front-end

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#558]
### Is your feature request related to a problem? Please describe?

Our users can set text custom fields on their assets. When the value of a text field is a link it is not clickable on the front-end.

### Describe the solution you'd like

 One thing that we want to do is check weather the value of the string is a link(we can use regex) and if it is, render it using our `<Button/>` component and append to it a ref param. Something like ```to={`${customFieldValue}?ref=shelf-webapp`}```

**Comment by carlosvirreira** [comment]
Thank you to all attempters! 

Let's see which one is picked!
