### ISSUE TITLE
[Feature request]: Calendar view of booking index

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#564]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

This is something requested by a user. The booking index is sorted by starting date / time, however to get the best overview a calendar view would be best.

![Screenshot 2024-03-21 at 17 35 51](https://github.com/Shelf-nu/shelf.nu/assets/76112272/8a8e581e-eb2d-4208-bb9e-bae29716e902)

### Describe the solution you'd like

A simplified implementation of a calendar view showing booking entries. Starting out with a monthly overview exclusively.

WIP SCENARIO
https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=4434-4519&mode=design

**Comment by carlosvirreira** [comment]
can you upload our design here @jurrejansen ?

**Comment by jurrejansen** [comment]
Hi @DonKoko spend a bit of time on this scenario last week after Carlos found a Calendar library. It's work in progress.

https://demo.mobiscroll.com/jquery/eventcalendar/desktop-month-view

We also shared the scenario with @rockingrohit9639 and he suggested another library.

http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/about-big-calendar--page

Thoughts on complexity?

**Comment by DonKoko** [comment]
Okey so the first one for sure we cannot use as its jquery.
I did some research and so far the 2 things that are coming up a lot are:
- [Big calendar](https://github.com/jquense/react-big-calendar)
- [Full calendar](https://github.com/fullcalendar/fullcalendar-react)

I am not really certain which is better. I am asking around and trying to find some more info.
