### ISSUE TITLE
Create item

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#58]
Functionality for creating an item.
Tasklist:

- [x] Basic create
- [x] Title
- [x] Asset main image
  - [x] Add timestamp to main image filename
  - [x] Delete asset when deleting item
  - [x] Change expiration time to 24h
  - [x] Implement automatic re-signing of image when its expired
- [x] Implement Markdown for description
- [x] Adding category

**Comment by DonKoko** [comment]
Because of the issue related to react-dropzone we have removed it from the item create and are using a simple file field. What we could also try is to manually place the file in the input field when using react-dropzone's `onAcceptedFiles` but first I would like to wait and hear back from the react-dropzone guys.

**Comment by DonKoko** [comment]
Ready to test. In the end i just did a simple implementation that works for now. Please test and lmk if we can move forward.

**Comment by carlosvirreira** [comment]
Works good on Safari and on my browsers. Let's release.
