### ISSUE TITLE
[Feature request]: Inviting a user and assigning them a 'Self-service' user role with limited permissions

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#588]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

After booking functionality is implemented some Shelf users / workspaces will require a user role that is only permitted to create a reservation. After that an administrator user can take care of doing the actual Check-out and Check-in to complete the booking process.

### Describe the solution you'd like

When inviting a user to a workspace the administrator or account owner can choose the user role from a dropdown. I'm thinking the 'Self-service' user role needs to be a default system role.

A small description of the 'Self-service' user role. 

"Users with the Self-service user role can reserve assets."

Asset overview: The Self-service user can see the assets but is unable to create / update / delete. They are also not allowed to update locations, or give and take custody over assets.

This means the Self-service user is able to see all assets in the index except for assets that are marked as 'Unavailable for bookings'

Creating booking reservations for themselves: Self-service users are able to generate their own reservations but are unable to perform a check-out or initiate a check-out from the beginning. **An administrator will need to handle the check-out and check-in process.**

Cannot manage settings: The Self service user cannot change workspace settings nor invite or update other account users. They can only change settings related to their own account. User details etc.

Their UI will probably look similar to this:

![Bookings](https://github.com/Shelf-nu/shelf.nu/assets/76112272/72215fd4-18c1-4705-9a23-588dc4eab991)
![Index](https://github.com/Shelf-nu/shelf.nu/assets/76112272/b9a413bc-1ba7-48dd-9a8f-2e03e5fa03ca)
![Asset](https://github.com/Shelf-nu/shelf.nu/assets/76112272/2926312a-f69f-4e59-98d2-d7e069140acc)

Wwith the eye on the future, permission will have to be structured kind of modular in a sense. Meaning the permissions that are attached to a user role should be categorized so at a later stage custom user roles can be made and certain permissions can be toggled on/off per user role. Hope that makes sense. Please don't hesitate to let me know if anything is unclear whoever picks up this issue. Thanks!

DESIGNS

     ↳ Inviting new users to a workspace
https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=2059-21594&mode=design

Now we're introducing a 2nd role it would be good to introduce the Edit action for users so administrators can change the role of a user

     ↳ Edit the role of a user
https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=510-271842&mode=design

**Comment by carlosvirreira** [comment]
Note: We will want to introduce more user types in the future. At some point even a permissions style custom user type creation.

**Comment by carlosvirreira** [comment]
Hi @mahendraHegde discussed this request with Nikolay - we need it for booking - perhaps you can assist?

**Comment by jurrejansen** [comment]
Hi @hunar1312 I'm assigning you this issue as @DonKoko and me were discussing this one and we would like for you to work on the front-end for this if possible.

Please review and let me know if any questions arise. Thanks!
