### ISSUE TITLE
[Bug]: Cannot change Custom Field -type

### ISSUE THREAD

**Issue by arthurkallinen** [Shelf-nu/shelf.nu#589]
### Contact Details

akfilmit+github@gmail.com

### What happened?

Steps to reproduce:

1. Go to Edit a 'Custom Field'
2. `Type` is greyed out

### What is the expected behaviour?

Type not being greyed out and to be able to change it.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by arthurkallinen** [comment]
> Hey @arthurkallinen, this is not a bug. Types of custom fields are not changeable. If you want a custom field with a different type you have to create a new one.

If I can't change it (make this a feature rquest then) nor delete ( #590 ) then I'm stuck with a non usable (for me) field and can't create one that I need. What am I supposed to do?

**Comment by DonKoko** [comment]
@arthurkallinen I answered your other issue #590. That was actually a bug. We are deploying the fix now. Lets move the conversation there if you have further questions.
