### ISSUE TITLE
[Feature request]: New fields

### ISSUE THREAD

**Issue by arthurkallinen** [Shelf-nu/shelf.nu#591]
### Contact Details

akfilmit+github@gmail.com

### Is your feature request related to a problem? Please describe?

For free users, custom fields being limited, and for ease of use having more already made fields that would seem very useful all around. 

### Describe the solution you'd like

New fields: 
- Lenght (for cables)
- Amount (for raw materials, cables, where there is usually multiples)
- Shelf coding (for example 01-02-03: Shelf 1, Column 2, Row 3)

**Comment by DonKoko** [comment]
hey @arthurkallinen. Thanks for your question and suggestions. We will discuss it with the team, however I want to explain to you why we have the field types we have so far.

So we wanted to focus on flexibility but also we wanted to release this asap, so these are the types we decided to use. We don't have a number field as we are not having any calculation features yet so we found it was not needed.

Concerning your requests, they are a bit too specific for your use-case for us to implement them as general features, however I think you can solve all 3 using the fields we already have.

1. Length - use a single-line text field called `Length` and in the description you can put your desired format, so for example: "Use cm" or "Use meters". The description will be shown as a help text for the field when creating an asset.
2. Length
3. Shelf coding - use a single-line text field called `Shelf coding` and in the description you can put your desired format you want it to have. Moreover looking at your example you can simply create fields like "Column", "Row" and "Shelf" if you want to store the data on separate fields.

Hope this makes it a bit more clear to you why we don't want to add super specific fields like in your suggestion. Please let us know if you have more questions.
