### ISSUE TITLE
[Feature request]: Other currencies (EURO)

### ISSUE THREAD

**Issue by arthurkallinen** [Shelf-nu/shelf.nu#592]
### Contact Details

akfilmit+github@gmail.com

### Is your feature request related to a problem? Please describe?

I live in Europe, so it's annoying trying to use USD for the equipment price.

### Describe the solution you'd like

Add Euros/other currencies option to equipment value. Maybe make this an workspace setting, so the app doesn't need to do conversions at least yet, fro faster implementation.

**Comment by evoxf1** [comment]
Hello, @arthurkallinen 
May I look into this ?

**Comment by arthurkallinen** [comment]
Go ahead @evoxf1

**Comment by DonKoko** [comment]
hey @evoxf1 and @arthurkallinen . At the moment you can change the currency only for Team workspaces but not for personal.
To do this we would need to make an edit page that also works for personal workspace and of course has some limitations.
1. Should not be able to change a personal work space's name
2. Should not be able to change a personal work space's picture

@evoxf1 if you want please feel free to work on that. Follow our contribution guide, and open a PR with your changes. Just make sure to ask me for review to speed up the process as much as possible. Let me know if there are questions.

**Comment by evoxf1** [comment]
@DonKoko Thanks, I will just browse at the moment and if there's any changes I will first confirm with you. 
Regards

**Comment by DonKoko** [comment]
Just let me know if you want to work on it so I know what to do with the issue. Thanks
