### ISSUE TITLE
[Feature request]: Settings area re-structure

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#601]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

I would like to improve how the Settings area within the application is structured. Basically in order to make it more organized and to have a good place for future settings. Also, some things are currently causing issues. For example, currently Personal users are unable to change workspace name and currency settings because there is no Edit action for Personal workspaces.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/6b2a1940-5818-47c6-b392-46e8e4f3d48e

### Describe the solution you'd like

My solution requires a few steps.

**1. Move User details from Settings area to it's own area + combine some actions into a dropdown**

This scenario should pretty much explain what I mean:
https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=627-136769&mode=design

@rajdip-b Please only focus on the content and ignore the new styles for e.g. the Header, Tabs. Focus should be on implementing the interaction for the Account element at bottom of sidebar.

![Screenshot 2023-12-12 at 14 55 31](https://github.com/Shelf-nu/shelf.nu/assets/76112272/6097d588-415c-4c98-af63-d521057c1c74)

- [ ] In Settings area change name from **User details** to **Account**
- [ ] Make Account element, at bottom of sidebar, click-able + when clicked should activate a dropdown
- [ ] Move Log out, Account details and Questions/Feedback to the dropdown
- [ ] Account details menu should link to **Settings** > **Account**

![Screenshot 2023-12-12 at 14 52 09](https://github.com/Shelf-nu/shelf.nu/assets/76112272/d5d0af13-0ffa-41ad-b987-5faab1ff6d1a)

2. Add a General tab in the Settings area

- [ ] Add a General tab in the Settings area
- [ ] Add **Workspace name**, **Workspace logo** and **Currency** fields under the General tab in Settings area
- [ ] After an account gets created the user's Personal workspace should be automatically named based of what they filled for their First name. So if user's first name is Olivia their personal workspace should automatically named Olivia's workspace.  Also the logo / avatar of the Personal workspace will be whatever they upload as an avatar image in their Account details. When a user is on their Personal workspace, and they go to **Settings** > **General**, the **Workspace name** and **Workspace logo** fields should be disabled. When hovering these fields a tooltip should appear (see screenshot)

![Screenshot 2023-12-12 at 13 59 36](https://github.com/Shelf-nu/shelf.nu/assets/76112272/089ca483-ab1c-451c-a5fa-8a455f09d686)

- [ ] Remove **Currency** field from **Settings** > **Workspaces** > Edit **workspace**. But keep the **Workspace name** and **Workspace logo** fields
![Screenshot 2023-12-12 at 13 16 42](https://github.com/Shelf-nu/shelf.nu/assets/76112272/6429ecc7-a9ef-4194-84e2-f943a2e11950)

3. Re-order the Tab items located in the Settings area

- [ ] Re-order Tab items (see screenshot)

![Screenshot 2023-12-12 at 14 58 40](https://github.com/Shelf-nu/shelf.nu/assets/76112272/971ec060-8c15-44cd-ad3f-529ec0a936b4)

**Comment by rajdip-b** [comment]
Would like to take this up!

**Comment by jurrejansen** [comment]
Hi @rajdip-b thanks for looking into this. I made the final adjustments after talking with @DonKoko You can start working on this whenever you're ready. Just hit me up on Discord if anything is unclear. Thanks!
