### ISSUE TITLE
[Improvement request]: Go to first / last page buttons in Pagination components

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#604]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

If a user has a large amount of assets, or other entries in other tables, they'll have to click the next button multiple times to reach the last page. 

### Describe the solution you'd like

Adding 'Go to first / last page' buttons within the Pagination component used throughout multiple tables within the app. In this new designs I have also changed the icons used in the buttons. Using Chevrons instead Arrow. Thanks!

- [ ] Change Arrow icons used for navigating to next / previous page into Chevron icons. Chevron icons are already being used within the app so please use those to replace Arrow icons
- [ ] Add 'Go to last / first page buttons. These buttons should use the Double chevron buttons. I'm providing these icons down below. Please make sure the icons use the same conventions (colors, container, etc.) as other icons used throughout the app. I am providing only 1 SVG file. Please use CSS to flip the icon.

[chevron-left-double.svg.zip](https://github.com/Shelf-nu/shelf.nu/files/13672697/chevron-left-double.svg.zip)

DESIGNS

![Screenshot 2023-12-14 at 12 10 40](https://github.com/Shelf-nu/shelf.nu/assets/76112272/f93fe3c0-648c-41bc-8165-e79ff2f2b772)

![Screenshot 2023-12-14 at 12 10 57](https://github.com/Shelf-nu/shelf.nu/assets/76112272/45f7c2ae-c3e7-4568-8588-1e59e1cdd714)

**Comment by lakshay-saini-au8** [comment]
Hey @jurrejansen  possible to assign this issue to me

**Comment by DonKoko** [comment]
please go ahead @lakshay-saini-au8 . Let us know if you have questions.

**Comment by DonKoko** [comment]
hey @lakshay-saini-au8 . Are you going to work on this issue? Please let us know so we can assign it to someone else if you cant.

**Comment by lakshay-saini-au8** [comment]
yes   I am working on this

**Comment by carlosvirreira** [comment]
Great! Good luck @lakshay-saini-au8

**Comment by arthurkallinen** [comment]
Requesting an extension for this: add pagination to top bar; If I know I have to go to the 1st item I have to scroll down, select 100 items, and it will jump me to the top, then scroll all the way down. If I had more than 100 items I'd need to N times to page right.

**Comment by DonKoko** [comment]
@jurrejansen could you think of a good way to add pagination also on top?

**Comment by DonKoko** [comment]
@GauravBurande if you are still interested in a bounty, you can pick this up.

**Comment by ezhil56x** [comment]
Can I work on this?
/attempt #604

**Comment by GauravBurande** [comment]
> @GauravBurande if you are still interested in a bounty, you can pick this up.

Thanks, I'll start working on this.

**Comment by DonKoko** [comment]
Awesome man. Lmk if there are questions. You can also join our discord to ask around.

**Comment by GauravBurande** [comment]
I'll, thanks for the opportunity!

**Comment by GauravBurande** [comment]
A little help here, I've added proper db URL and direct URL still getting this error when running npm run setup

![image](https://github.com/Shelf-nu/shelf.nu/assets/100035026/a16246d7-3dad-417c-8886-38939de4ab34)

**Comment by DonKoko** [comment]
hey @GauravBurande,

did you make your .env file? If that is good, maybe you can also try to use `npm run reset:db`? 
if you still are not able to make it work, its better to join our discord and open a discussion there or send me a dm, so i can help you resolve it.

**Comment by GauravBurande** [comment]
I've made a .env.local file, is that the reason?

**Comment by GauravBurande** [comment]
I'll open a discussion in disccord

**Comment by GauravBurande** [comment]
I've added the svg icon provided above, just wanted to make sure this looks good and is ready to go.

![image](https://github.com/Shelf-nu/shelf.nu/assets/100035026/62af2224-98f2-482a-8aa2-8a39d9fdc004)

**Comment by DonKoko** [comment]
@jurrejansen this is done and deploying to live now: https://github.com/Shelf-nu/shelf.nu/actions/runs/7742430292
