### ISSUE TITLE
Improvement: Implement new styles in platform

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#617]
Implement the updated global styles of the platform.
There are some stuff that are quite complex to implement and feel inconsistent across views that we still need to review so we are going to take it step by step. Here are the first 3 things we will do:

- [x] Change border radius everywhere - including buttons and inputs
- [x] Implement (partially like discussed) the new header style
- [x] Change <main> padding

**Comment by DonKoko** [comment]
Okey I am looking at the designs and trying to point out other small wins we can do here:

- [ ] Workspace selector - we should implement new style. Maybe better to directly apply the new style to the Select component we have that extends radix: `forms/select.tsx`
- [ ] Settings/account - put the content inside a card like in the other tabs
- [ ] Settings - within settings we have a few cards that still have the old border radius
- [ ] Settings/team - I think the new design could be implemented - https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=2066-33485&mode=design&t=B1a9BNV7drixdBPA-0 . Important note: In the new design it just says "Team". Lets not do that. I think what we have now with "${workspace.name}'s team" is better
- [ ] Tabs within settings - so as we talked on discord i really dont like the inconsitency between the designs and how the header is being used and I find it very poor, however, i think in this case it actually makes sense, because we have another level of layout/navigation below. So what I would recommend is that we add an option to hide the title row of the header on some views(like settings for example) so we can add the menu there in the new style

**Comment by jurrejansen** [comment]
@DonKoko @hunar1312 nice one

Would it be good to push this to testapp whenever possible and then I review and list out what is left. Then we can decide what else could be relatively easily adjusted and what we can icebox for later.

Regarding the header, I see it as a component made up from a couple of different elements. Depending on the current view it shows the elements that are relevant. Elements that could be in the header.

- Breadcrumbs + Action buttons
- H1 + (Status badge)
- Filters
- Tabs

Could be views that show a combination of these elements. Could be view that only show Breadcrumbs.


ASSET PAGE (Breadcrumbs + H1 (Status) + Tabs
![Screenshot 2023-12-21 at 10 26 29](https://github.com/Shelf-nu/shelf.nu/assets/76112272/fd36e665-8420-4ee3-ae3d-b1e59c1d14e9)
![Screenshot 2023-12-21 at 10 26 43](https://github.com/Shelf-nu/shelf.nu/assets/76112272/3269e8df-31cd-4c3a-9694-e2fcef2ac0c4)

ASSET INDEX (Breadcrumbs + H1 (Status) + Filters
![Screenshot 2023-12-21 at 10 27 08](https://github.com/Shelf-nu/shelf.nu/assets/76112272/581080c4-626d-428f-8148-2acca81ef9f6)
![Screenshot 2023-12-21 at 10 33 37](https://github.com/Shelf-nu/shelf.nu/assets/76112272/32ab930d-321e-4ffb-bc16-75cfd16b187e)

SETTINGs (Breadcrumbs + Tabs)
![Screenshot 2023-12-21 at 10 34 24](https://github.com/Shelf-nu/shelf.nu/assets/76112272/9146034a-3f17-4c8e-86d1-c376788751ad)
![Screenshot 2023-12-21 at 10 34 30](https://github.com/Shelf-nu/shelf.nu/assets/76112272/36ba8434-716e-4f70-a2b8-2c371e8b2209)

Anyways, feel free to suggest /change things that make life easier. The dream would be to have a sticky header component in the future that'll make Action buttons always accessible.

**Comment by DonKoko** [comment]
@hunar1312 2 places i found where we didnt change the border. Tags and Categories edit/create
![Screenshot 2023-12-21 at 11 48 02](https://github.com/Shelf-nu/shelf.nu/assets/7840007/f267855e-7888-4ee5-9e0f-435f08356db6)
![Screenshot 2023-12-21 at 11 47 57](https://github.com/Shelf-nu/shelf.nu/assets/7840007/82b86803-7dd1-4dee-9354-241a6dcc2b1c)

**Comment by DonKoko** [comment]
More feedback:


<img width="309" alt="Screenshot 2023-12-22 at 12 45 36" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/44b423c2-80d3-4964-8c0e-d1d21b2dafc4">

- [ ] Border radius too big
- [ ] DropdownTrigger has some empty space on the right

<img width="337" alt="Screenshot 2023-12-22 at 12 46 18" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/e235b5e1-603a-4052-aafc-20912e12b575">

- [ ] DropdownTrigger has space on the right. Should reach end
- [ ] The DropDown content should be wider. It doesnt have to fit within the width of the trigger. WE have to make sure the names are visible like it was before.

<img width="188" alt="Screenshot 2023-12-22 at 12 48 17" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/2a9c46ed-f68e-4862-a6b6-abafd14c2001">

- [ ] OrganizationSelect when sidebar is minimized is not showing correctly. Its border is being cut-off. Can you make it work like the user dropdown in the bottom of the sidebar

<img width="1663" alt="Screenshot 2023-12-22 at 12 50 15" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/6570bf4a-9504-4571-af46-464fc92f2971">

- [ ] Menu is not right. Check in the design, it should be within the new style with the background and stretching to the end. Here is an example: https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=510-271403&mode=design&t=5MjSRsGNxeRDWHkc-0

<img width="1651" alt="Screenshot 2023-12-22 at 12 53 02" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/fddd9d18-72ca-4303-be03-d7d0a5b38912">

- [ ] Dashboard - first chart has issues with border radius and spacing on top

<img width="400" alt="Screenshot 2023-12-22 at 12 53 47" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/2be975ee-ae6c-4bd8-b2da-d1adc0a08e69">

- [ ] Tooltip border radius

<img width="255" alt="Screenshot 2023-12-22 at 12 56 15" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/315a4fe0-d456-464e-bcd4-fc8793eee137">

- [ ] Dropdown border radius


<img width="883" alt="Screenshot 2023-12-22 at 12 55 07" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/26e41c4c-a048-4058-b1d7-17fb3057723b">

- [ ] Dialog border radius is kinda broken. Its different on each side and doesnt look right on either :)

<img width="511" alt="Screenshot 2023-12-22 at 12 55 51" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/cabfde8b-1d96-440a-87f6-5ef140611621">

- [ ] Pagination border radius

<img width="964" alt="Screenshot 2023-12-22 at 12 58 01" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/468c7880-c768-4693-97b0-8317c2572b0f">

- [ ] asset.new border radius on tags selector
