### ISSUE TITLE
[Feature request]: Creating a booking and inspecting asset index and asset page as a Self-service user

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#627]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

We're introducing the first new user role next to Administrators called the Self-service user role. Self-service user will have limited permissions so in this issue we're defining these limitations. The issue for creating users with this role is located here: https://github.com/Shelf-nu/shelf.nu/issues/588

### Describe the solution you'd like

SIDEBAR

A Self-service user will have less menu items in their sidebar menu. They will only have access to:

- Assets
- Bookings
- Settings (only Account)
- Minimize
- User dropdown
 - Account details
 - Feedback/Questions
 - Log out

ASSET INDEX

The Self-service user will be able inspect the asset index. However the Custodian column will be hidden for them. Also, if an asset is marked as 'Unavailable for bookings' it will be hidden from the index when logged in as a Self-service user. They're also unable to perform any actions from this view.

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=2739-106611&mode=design

ASSET PAGE

The Self-service user will able to visit / inspect most asset pages but the information shown there will be limited and they're not able to perform any actions. Most importantly the Notes area is hidden.

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=2699-36926&mode=design

BOOKINGS

The Self-service user will be able to create a booking (only for themselves) in the Bookings area. They will only be able see and create bookings related to themselves. They are unable to perform the Check-out action, this can only be done by Administrators. **So they will only be create and configure Draft a booking, add assets and Click Reserve.**

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=2013-16223&mode=design

**Comment by jurrejansen** [comment]
Hi @mahendraHegde I've prepped this for some more clarity about what users with Self-service role will be able to do and see. Perhaps you can take a look if everything seems clear. Thanks man!

**Comment by DonKoko** [comment]
This is done and released so I am closing it.
