### ISSUE TITLE
[Feature request]: Disable UI while switching workspace

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#638]
### Is your feature request related to a problem? Please describe?

There is a small delay when switching workspaces because of server requests and changing cookies.

### Describe the solution you'd like

I in general dont like blocking the UI but I think its this case its important to do it. @jurrejansen can you create a simple design to disable the UI when switching between worskpaces.

**Comment by jurrejansen** [comment]
@DonKoko tried to keep it simple. Updated the 'Switch workspaces' scenario.

https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=96-21706&mode=design

I re-used the loader that is currently being shown after clicking the link in the confirmation email after registering a Shelf account.

![Screenshot 2024-01-04 at 13 05 13](https://github.com/Shelf-nu/shelf.nu/assets/76112272/447954e4-f631-46e5-8800-7a1bb14a71ea)

**Comment by DonKoko** [comment]
Thanks @jurrejansen. The design looks good. 
In terms of technical implementation the easiest will be to just create an atom that hold some state like `swithingWorkspace: boolean` and then we can load this atom from all the relevant components (`_layout+/_layout.tsx` and `sidebar.tsx`) so we can disable the sidebar and show the loader in the main area.

**Comment by melsonic** [comment]
/attempt #638
can I get assigned?

**Comment by GauravBurande** [comment]
Can I work on this issue?

**Comment by DonKoko** [comment]
hey @GauravBurande . There is already an open PR on this. https://github.com/Shelf-nu/shelf.nu/pull/702
If its not successful you can take over of course. Feel free to discuss with the other person.

**Comment by GauravBurande** [comment]
ok

**Comment by DonKoko** [comment]
@jurrejansen this is merged and being deployed.
