### ISSUE TITLE
[Bug]: Items per page not remembered

### ISSUE THREAD

**Issue by arthurkallinen** [Shelf-nu/shelf.nu#641]
### Contact Details

akfilmit+github@gmail.com

### Is your feature request related to a problem? Please describe?

Annoying when everytime going back to asset list, having to scroll down, select 2nd page or to make it show 100 items, selecting & editing item, and repeat. Slows down massively mass editing items.
![brave_YafbqMp9gb](https://github.com/Shelf-nu/shelf.nu/assets/44576346/00370505-452e-4ecc-8fed-c5f86ceef03c)

### Describe the solution you'd like

 - Save per page item amount to cookies
 - Optimally saving it to user / workspace

### Describe alternatives you've considered

- Default it to more than 20 items

**Comment by DonKoko** [comment]
hey @arthurkallinen . Thanks for opening an issue.
We already have a user-prefs cookie that saves the per-page and it works across workspaces. I did test it and I can confirm its not working as expected so it seems like its a bug. We will address it and let you know when i fix is deployed.

**Comment by DonKoko** [comment]
@arthurkallinen thanks again for reporting this. It has been fixed and deployed with #808
