### ISSUE TITLE
[Feature request]: Custom fields sorting

### ISSUE THREAD

**Issue by arthurkallinen** [Shelf-nu/shelf.nu#649]
### Is your feature request related to a problem? Please describe?

- Custom fields to be a sortable column in asset list view
![brave_zdbYD0cFhI](https://github.com/Shelf-nu/shelf.nu/assets/44576346/e10bf1bd-6bfb-492d-b47d-37a5561a655c)
- Reordering custom field items (for example, dropdown list items currently stuck in order of input. ++ for sort by name option.
![brave_FMyy3MweC7](https://github.com/Shelf-nu/shelf.nu/assets/44576346/6b3c71ec-4b0a-498e-93c9-445e4235d2f2)

### Describe the solution you'd like

- Custom fields to be a sortable column in asset list view

- Reordering custom field items (for example, dropdown list items currently stuck in order of input.  ++ For sort by name option.

### Additional context

Regarding Discussion: https://github.com/orgs/Shelf-nu/discussions/639

Comment by @DonKoko - 
> This is amazing and we have it planned, however it comes with quite some complexities and we have it blocked by some other issues we have to solve first. Feel free to create 1 feature request issue for this and we will pick it up as soon as we can or place a bounty once the blockers are solved. 
>
https://github.com/orgs/Shelf-nu/discussions/639#discussioncomment-8049785

**Comment by DonKoko** [comment]
After we release our Bookings functionality we will be reworking our List components and adding all types of filtering and sorting options. This can be combined with that scope.

**Comment by DonKoko** [comment]
This is resolved by advanced index.
