### ISSUE TITLE
[Feature request]: (Multi)select & custody assign in Asset view

### ISSUE THREAD

**Issue by arthurkallinen** [Shelf-nu/shelf.nu#651]
### Is your feature request related to a problem? Please describe?

Usually I move a lot of stuff at once, so it'd be very useful to be able to select multiple assets to be assigned to custody.

### Describe the solution you'd like

A check box in the left side of asset, maybe not visible until selected (either via a menu or command like ctrl (+shift for row selection) + click etc. 
Add "Assign custody" to hamburger menu in asset view and make it follow selection.

### Additional context

I understand this will need UX/UI rework and will propably be low on priorirty list. But throwing this here if you are doing bigger redesign to be included or  had as a pre-thought to not create a block as a future possibility.

**Comment by DonKoko** [comment]
Thanks for opening the issue @arthurkallinen . We already have designs and so on so we will be implementing it soon.

**Comment by jurrejansen** [comment]
@arthurkallinen we'll be including this in another issue, so i'm closing this one. Thanks for the feedback!

https://github.com/Shelf-nu/shelf.nu/issues/397
