### ISSUE TITLE
[Feature request]: Asset groups / Packs

### ISSUE THREAD

**Issue by arthurkallinen** [Shelf-nu/shelf.nu#652]
### Is your feature request related to a problem? Please describe?

I have multiple items, that for inventory purposes are good to be separeated, but the are in one physical rack unit, that will be moved as one, so creating some kind of asset packs or groups would be useful.

### Describe the solution you'd like

Asset pack, back-end would be hybrid of Asset and Location; it would have similar list of Assets it's containing, but still assignable to loccation and custodian, and would be on the Asset list as it's own item.
It could have a link to custody and location of the Assets inside it (AssetA separate Asset listing would show it's location & custodian as same as the pack.

### Describe alternatives you've considered

Groups of assets, would be it's own page, but similar technical specs of custodian and location assignable. 

### Additional context

This would be a bigger feature needing some rework, but propably a wanted feature, so I know this won't be a high priority. Technical implementation may differ.

**Comment by DonKoko** [comment]
hey @arthurkallinen. We already have this planned and have some designs ready, so it will be implemented some time in the near future. Would you mind giving some feedback on the designs? @jurrejansen can you share them here so AK can take a look?

**Comment by arthurkallinen** [comment]
I'd love to check out them if possible!

**Comment by jurrejansen** [comment]
Hi @arthurkallinen we indeed have this planned but designs yet unfortunately. Lots to do at the moment but I've bumped this up on my to do list and hope to work out a concept soon. I'd love for you to check them out and give your input when the time comes though. I'll make sure to share them here and notify you. Thanks for opening the issue!

**Comment by jurrejansen** [comment]
Hi @arthurkallinen we're tracking this concept in another issue. https://github.com/Shelf-nu/shelf.nu/issues/779#issuecomment-2022078220

There I have also posted some links to a scenario with designs. Please feel free to share further input there. Thanks, it is much appreciated!
