### ISSUE TITLE
[Bug]: QR code scanning uses ultra-wide camera

### ISSUE THREAD

**Issue by arthurkallinen** [Shelf-nu/shelf.nu#656]
### What happened?

TApp using ultra-wide camera on my phone (S22Ultra) and no way to change it, causing QR code not to be read. Luckily using phone's own camera app is a work around.

https://github.com/Shelf-nu/shelf.nu/assets/44576346/25d7702b-2ade-4e4c-a4ba-2e807095c047

### What is the expected behaviour?

Scanning the code and displaying the item (and registering location).

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
hey @arthurkallinen . We would have to research this a bit. I am not sure what is this ultra wide camera and why it wouldn't work.
I did made some research specifically about your phone model and it seems like a common issue people are facing. Apparently the QR scanning can be disabled in the camera settings. Maybe good to test that?

**Comment by arthurkallinen** [comment]
QR scans are enabled, and the phone's own camera scans QR-codes well. But Shelf's QR scanner just shows ultra-wide camera (which I think is not capable of scanning) and doesn't scan it. App/chrome needs to request certain camera: Ultra wide 0,6x is Back - 0, normal 1x is Back - 1, Telefoto 3x is Back 2, Telefoto 10x is Back - 2, Selfie camera Front - 0. This is how they are shown in vMix Call (Advanced, can't demo this currently). Propably needs a Samsung S Series specific request.
![Screenshot_20240110_153505_Camera](https://github.com/Shelf-nu/shelf.nu/assets/44576346/9d9be77b-a964-415e-aaab-8bd47f866b56)

**Comment by DonKoko** [comment]
Okey, thanks for the extra info. We will look into it.
