### ISSUE TITLE
[Feature request]: Assign custom fields to categories

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#658]
### Is your feature request related to a problem? Please describe?

Don't need to see all/every custom field on each asset. On my shelf setup I have 100s of custom fields - it makes my experience time consuming and tedious.

### Describe the solution you'd like

Custom fields are related to categories. Categories become more important and valuable.

**Comment by jurrejansen** [comment]
@carlosvirreira here's a scenario for this one: https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=3226-31757&mode=design

I've worked out 2 options, I guess @DonKoko can decide which one would be easier to implement

**Comment by carlosvirreira** [comment]
@DonKoko which option you think its easier to implement from your POV? 

Also curious what @rockingrohit9639 has to say 🙏🏼

**Comment by carlosvirreira** [comment]
> @carlosvirreira I think, me and @DonKoko have discussed about it before. We decided to go with option 2. I will give it a shot whenever I get time.

Oh this is great - I think Nikolay may have shared this with me, but I can't recall. 

I am happy that it is option 2 that we go for - it feels like the most powerful of the two!

**Comment by carlosvirreira** [comment]
> @carlosvirreira I think, me and @DonKoko have discussed about it before. We decided to go with option 2. I will give it a shot whenever I get time.

Complexity wise I assume this change has quite some moving parts, right?
