### ISSUE TITLE
Bookings remaining feedback

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#681]
This is the remaining feedback from the bookings that was on the PR. Moved it to its own issue.

- [x] When configuring a booking and clicking save, additional Draft bookings get created. Sometimes 1, sometimes 2 additional ones that shouldn't have been created
https://github.com/Shelf-nu/shelf.nu/assets/76112272/1927176b-6175-46c7-9e46-9516e8c0fd01

Sorry to suggest this late in testing but...

- [ ] Can we send user back to booking index after performing actions like Reserve, Check-out, Check-in, Delete and Archive. I think in 90% of the cases they'll prefer this over staying on the individual booking page. We'll just have to make sure the notification works consistently informing them the action was successful. In my experience the notifications consistently  
 
- [ ] We need a ‘Check-in reminder’ mail when a booking gets checked out after the End date / time. Currently the mail is quite weird when this happens. This example is when check-out happened 44 minutes after End date / time. “Your booking was due for check-in 44 minutes ago”. Not a real case but it can happen.

![Screenshot 2024-01-23 at 15 07 57](https://github.com/Shelf-nu/shelf.nu/assets/76112272/1f0e480a-64d5-43cd-a9f9-dc0ca86826e5)

- [ ]  If we remove the left and right padding for the elements containing the fields for Name, Booking period and Custodian we can save some horizontal screen real estate

![Screenshot 2024-01-23 at 15 08 42](https://github.com/Shelf-nu/shelf.nu/assets/76112272/bff06415-a3e7-438a-ab29-a291151b51cd)

- [ ] when configuring booking we're using the 24-hour and DD/MM/YYYY time / date format. In the booking index we're using the 12-hour and MM/DD/YY time / date format. Maybe not for now, as we have not yet implemented the settings for this. There was talk about potentially syncing it with device settings.

- [ ] If we want to follow designs the 'checked out' warning label should say 'Unavailable' instead. Also the 'checked out' label is only showing on assets in the Manage assets modal and not on the assets in the index within the booking. The logic of when the 'checked out' AKA 'Unavailable' label should show is described in the annotations under design.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/c98c9800-ec9d-4c43-8acb-b21ecab0de8c

_Originally posted by @jurrejansen in https://github.com/Shelf-nu/shelf.nu/issues/555#issuecomment-1906124042_

**Comment by carlosvirreira** [comment]
I had made a booking reservation. Then as an admin I went and gave custody of one of the assets to a user. This resulted in a reservation having a conflict. This makes sense. However, I was still able to perform a check out. I believe this should result in an error. Either the admin should un-assign the asset to the person or the assigning should have not been allowed to happen in the first place. 

@jurrejansen - thoughts?

**Comment by DonKoko** [comment]
@carlosvirreira @jurrejansen I have checked the code and we are not doing a check for this but I can add it if we agree its a good idea. I believe we decided to leave it like this as "Giving custody" is a manual action by the admin, so we leave it to them. Yes its stupid to check-out a booking that has items already in custody but its possible.
I do think tho, that no matter what we do we have to do some testing of edge cases because for example if you do this now, and do the check-out the asset status gets changed to checked out but on the asset page you can still see the custody as that never gets cleared, so we will have data inconsistency. Lets decide what approach to take so I know what fix to implement.

**Comment by jurrejansen** [comment]
@carlosvirreira @DonKoko these conditions should fix issues

- [ ] Asset that is 'IN CUSTODY' can be added to a booking, booking can then be Reserved, but it shouldn't be possible to Check out. Currently this is possible
https://github.com/Shelf-nu/shelf.nu/assets/76112272/ddaabae9-e412-4159-955a-0bef2fd4af46

- [ ] If asset is part of a booking that is in Reserved state, Admin will still be able to assign custody to that asset as it has an Available status. However, it will not be possible for the booking to be Checked out because the booking is In custody

- [ ] When an asset has a Checked out status, it should not be possible to perform any actions on that asset. This includes assigning custody.

![Screenshot 2024-01-25 at 14 17 05](https://github.com/Shelf-nu/shelf.nu/assets/76112272/5e7dffa3-42e6-4781-878e-dea285db6da1)

**Comment by carlosvirreira** [comment]
if I mark an asset as 'unavailable for booking' and I have a 'complete' (previously done/finished) booking - I will get the 'includes unavailable assets' . This microcopy is confusing and not necessary. Would be best if this tag does not get shown on completed bookings.
