### ISSUE TITLE
Index category filtering

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#70]
Adding the category filtering to the index. Its basically working but we still have quite some things to handle:

- [x] Search is somehow broken right now. If you try to search it refreshes the page
- [x] Empty state for categories filter(if no categories)
- [x] Merge params of prev,next,search and page numbers with categories params(maybe make it so that categories filter and search are part of the same form.
- [x] Double check for hydration issues due to client side only components 
- [ ] Clear categories filter ( Dont have design for this so I will wing it)
- [x] Fallback states for clientOnly components(category select and categories filter dropdown)

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira this is mostly working. I only miss design for the 1 point above, but it can already be tested and reviewed. Thanks

**Comment by jurrejansen** [comment]
@DonKoko some things i noticed

- [ ] After clicking the 'Categories' filter the text input isn't activated and you have to click it before you are able to start typing/searching for a category

- [ ] After clicking the text input and typing 1 character the input gets deactivated and you have to click the input again

https://user-images.githubusercontent.com/76112272/231700615-add2dab1-4c58-461b-8ceb-245d6a8979e1.mov

**Comment by DonKoko** [comment]
Thanks @jurrejansen . I am aware of this issues, but I was having trouble fixing it. I will take care of it.

**Comment by DonKoko** [comment]
@jurrejansen one more thing. Can you please give me a design for the point above that is missing. Thanks

**Comment by DonKoko** [comment]
@carlosvirreira this is fixed. Can you please test it and lmk. Thanks

**Comment by carlosvirreira** [comment]
It's fixed.
 

GG

**Comment by DonKoko** [comment]
@carlosvirreira I have also deployed the clear filters button.
