### ISSUE TITLE
[Feature request]: Consumable area of website

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#737]
### Is your feature request related to a problem? Please describe?

I have to track the quantity of my assets. They are not individual assets like a laptop but more like parts that I can use for a production. I do not need for them to be related to a project or anything inside shelf I just want to use my asset management system to also track consumables.

### Describe the solution you'd like

When you create an asset:
- Ask quantity (editable if you want update quantity later)
- Ask minimum quantity alert (editable too)

When someone scan the qr code of the asset
- Ask to update quantity (you can simply edit the field above)
-  or in alternative, more nice, just if someone scan "Did you use it?" or something similar, ask the quantity and update the quantity of the asset. (Consider / discuss > @jurrejansen )

Whe the asset reach the minimum quantity -> send email. That's all! I think that with this feature you will take all (redacted) users

**Comment by jurrejansen** [comment]
Closing, discussion continues in https://github.com/Shelf-nu/shelf.nu/issues/912
