### ISSUE TITLE
[Improvement request]: Improve settings logic / routings related to Account details and Subscription

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#741]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

Within the Settings area we have a few setting categories that relate to the user account instead of the workspace. These settings are Account details, Workspaces and Subscription. To decrease potential confusion I would like to suggest some changes.

### Describe the solution you'd like

- [ ] Separate Account details from Settings area. Viewing and editing Account details can exclusively be done by clicking the User element in the bottom of side bar and choosing Account details.

![Screenshot 2024-06-03 at 11 15 49](https://github.com/Shelf-nu/shelf.nu/assets/76112272/54adc65e-05a1-47e1-b843-68aabb46081c)

https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=627-136769

- [ ] The Subscription and Workspaces tabs currently located in Settings should be moved to Account details

![Screenshot 2024-06-03 at 11 08 35](https://github.com/Shelf-nu/shelf.nu/assets/76112272/7c05931c-4fcf-4ec3-a5ce-c66c1a4fa0de)

![Screenshot 2024-06-03 at 11 08 47](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a9512c1f-c554-4eb5-9772-6750ddbc4fac)

- [ ] Change link in Workspaces dropdown. Change text into "Manage workspaces" and make it link to Account details > Workspaces

![Screenshot 2024-06-03 at 11 12 23](https://github.com/Shelf-nu/shelf.nu/assets/76112272/bcb4fa7b-9e12-4cbc-8955-a6e6ef8fcbc8)

**Comment by jurrejansen** [comment]
@DonKoko let me know if you agree or see any issue here, thanks

**Comment by ezhil56x** [comment]
Can I get this assigned?
