### ISSUE TITLE
[BUG]: Post scan quick actions are no longer working on mobile after last update

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#743]
### Is your feature request related to a problem? Please describe?

Whenever I scan a tag on mobile I want to do an action to the item (logged in) such as update a note or location or something. 

### Describe the solution you'd like

Before, we used to open the actions dropdown, this saved me a few clicks. Would be handy if it comes back.

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira a fix is being deployed for this. It was an issue with its default value.
