### ISSUE TITLE
[Bug]: Notes area seem to have a maximum amount of characters 

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#744]
### What happened?

The notes field seems to have a maximum character restriction. This is not mentioned on the UI - causing confusion. 

For use cases as writing an inspection report or auditing an asset, having a restriction of characters is a liability - specially if not mentioned explicitly.

Trying to add such a text to the asset notes:

Visual Inspection:
A visual inspection of the exterior of the drone revealed no signs of damage or wear. All propellers were found to be free from nicks, cracks, or other forms of damage. The motors appeared to be functioning properly, with no visible signs of overheating or malfunction. The camera and gimbal system also appeared to be in good working order.

Electrical Systems Check:
All electrical systems were tested and found to be within normal operating parameters. The battery level was at 87%, which is above the recommended minimum charge level of 70%. No issues were detected during this check.

### What is the expected behaviour?

Ideally there is not a character limit - I can understand if for displaying the notes that this wants to be prevented (the note would take a large amount of space) for that we could work with a maximum height of the card and then an expand button/link. Something like what Quora has seems interesting. 

_Collapsed state_
<img width="692" alt="Screenshot 2024-02-14 at 13 39 03" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/ac74e91e-149b-4fc7-bb82-17a6415f0645">

_Expanded state_
<img width="679" alt="Screenshot 2024-02-14 at 13 39 16" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/d3b316fa-a740-4a19-8190-b136506c2e46">

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by carlosvirreira** [comment]
Hi @jurrejansen perhaps you can come up with a design for it if @DonKoko sees it as something valuable

**Comment by DonKoko** [comment]
solved here: https://github.com/Shelf-nu/shelf.nu/pull/782
I set the limit to 100000.
Lets make a different issue for the read more functionality, once its requested by our users.

**Comment by carlosvirreira** [comment]
Maks sense, let's close this for now.
