### ISSUE TITLE
[Bug]: AK's Test of Team Plan and Bookings

### ISSUE THREAD

**Issue by arthurkallinen** [Shelf-nu/shelf.nu#751]
### **Importing .CSV**
- `"` (quote) will not be parsed.
![image](https://github.com/Shelf-nu/shelf.nu/assets/44576346/4270e7f6-2652-4c60-9a9c-ad74e2a2e724)
- "–" (long dash) not interpreted.
![_image](https://github.com/Shelf-nu/shelf.nu/assets/44576346/77d3ea58-3ad4-4214-9425-ea0138e111dd)
- "ä" "ö" (a and o with dots, Finnish) not interpreted.
![longdash](https://github.com/Shelf-nu/shelf.nu/assets/44576346/02ce7407-5800-4d4e-bd5c-e8223eae40f0)
- After importing there is an alert that gives mixed message of both broken .csv and an success.
![mixedMessage](https://github.com/Shelf-nu/shelf.nu/assets/44576346/72e1b43f-bc9e-4800-8ead-c9ffa90ec543)

### **Bookings**
- email of Custodian userselection will spill out of box
![HwmQZ44](https://github.com/Shelf-nu/shelf.nu/assets/44576346/08c3b1e1-26f5-4c3a-8008-4eda7185faf9)

### **Team Plan**
- User invite accepting button goes to error page, even tho accepting goes thru. This causes confusion on receiving end. 
![invite](https://github.com/Shelf-nu/shelf.nu/assets/44576346/16de85b2-d1eb-46f5-aa49-beb4076c948f)
- Resending invites and revoking access from a user will cause all icons to do loading animation, giving the impresson that it wll action on all. 
https://i.imgur.com/by7VVtD.gif

### What is the expected behaviour?

-

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by DonKoko** [comment]
hey @arthurkallinen. Thanks for the feedback. We will work on it. Could you provide us with an example asset import file you used so we can debug with it? It can be only 1 or 2 assets.

**Comment by DonKoko** [comment]
hey @hunar1312.
Could you please take care of the following stuff from the report:

- [ ] Import popup content
- [ ] email of Custodian userselection will spill out of box

**Comment by DonKoko** [comment]
> Resending invites and revoking access from a user will cause all icons to do loading animation, giving the impresson that it wll action on all.

This has been fixed and is being deployed right now. Should be live soon.

**Comment by DonKoko** [comment]
Closed by mistake. Re-opening.

**Comment by DonKoko** [comment]
> User invite accepting button goes to error page, even tho accepting goes thru. This causes confusion on receiving end.

This is fixed + other improvements to auth. Will be live in a bit.

**Comment by DonKoko** [comment]
@arthurkallinen everything here is solved without the import issues, as I couldn't recreate them. As we talked on discord, please send me a example file which i can use to re-create this bug and we will create a new issue if needed.
