### ISSUE TITLE
[Feature request]: Kits

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#779]
### Is your feature request related to a problem? Please describe?

I want to track a kit as an asset, but also the assets inside the kit as individual entries.

### Describe the solution you'd like

Create a 'Kits' area of the app. Works a lot like locations. Difference is that the kit does generate a QR code. 

The kit should also be shown on the asset page index.

**Comment by carlosvirreira** [comment]
@jurrejansen please pick up this one and deliver a simple UI scenario / flow for it as we will fast-track this development.

**Comment by jurrejansen** [comment]
@DonKoko @carlosvirreira I should have handled all the scenarios for the version of kits we have discussed. 

Here's the basic scenario for creating a kit: https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=3753-12837&mode=design

From there you can view the rest of the scenarios.
![Screenshot 2024-03-01 at 09 32 05](https://github.com/Shelf-nu/shelf.nu/assets/76112272/8a6b975a-ec4b-4d75-a34d-f2ff82153076)

**Comment by carlosvirreira** [comment]
Reviewing @jurrejansen

**Comment by carlosvirreira** [comment]
> Reviewing @jurrejansen

Comments on Fig

**Comment by DonKoko** [comment]
Duplicates #652

**Comment by jurrejansen** [comment]
@DonKoko I've added a couple of extra scenarios. Let me know if you have more concerns when you get to it.

**Comment by carlosvirreira** [comment]
@jurrejansen there are comments added to the file

**Comment by jurrejansen** [comment]
Kits feature is stable, closing this and we can open a  new issue when we want to build expand the feature
