### ISSUE TITLE
[Bug]: Chat bubble positioned over action

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#785]
### What happened?

![Screenshot_14](https://github.com/Shelf-nu/shelf.nu/assets/12449255/0ec77d96-74b8-4a49-b70e-05f63563da80)

### What is the expected behaviour?

action should be available for usage

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by rockingrohit9639** [comment]
Hey @carlosvirreira I would like to work on this issue.

**Comment by jurrejansen** [comment]
There's not really a solution described in this issue @rockingrohit9639 

@carlosvirreira @DonKoko maybe @rockingrohit9639 can pick up this issue? https://github.com/Shelf-nu/shelf.nu/issues/663

**Comment by rockingrohit9639** [comment]
Let me know If I can work on this @DonKoko

**Comment by jurrejansen** [comment]
@rockingrohit9639 i'm going to give https://github.com/Shelf-nu/shelf.nu/issues/663 a bit more detailed description as we want to tackle a couple of similar views at once.

@DonKoko will let you know when you can start working on it. Thanks for your interest :)

**Comment by DonKoko** [comment]
hey @rockingrohit9639, as Jurre said the actual issue that should be used to resolve this is #663, however I need to review some stuff first. Will do it and let you know.

**Comment by rockingrohit9639** [comment]
Ok sure @DonKoko

**Comment by DonKoko** [comment]
This is handled by implementing #663
