### ISSUE TITLE
[Bug]: Location capturing not working

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#791]
### What happened?

Steps to reproduce:

1. Go to any asset page
2. Click on view QR code
3. Scan QR code

### What is the expected behaviour?

When you scan the code (not logged in) the app usually sent you to a 'contact owner' page. This seems to be going now to the 'log in' page. Therefore forcing a user to register in order to update the location / request the location syncing. 

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by DonKoko** [comment]
Resolved in #797
