### ISSUE TITLE
[Bug]: Broken link

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#802]
### What happened?

I was just looking in the settings and the hover tool tip text on the Workspace name field has a bad link to https://app.shelf.nu/settings/general/settings/subscription instead of [https://app.shelf.nu/settings/subscription](https://app.shelf.nu/settings/general/settings/subscription)

<img width="484" alt="Screenshot 2024-02-29 at 21 26 12" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/61f8eece-6a1b-4fc6-8aab-de4f895dd166">

### What is the expected behaviour?

Link me to the correct route

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
Fixed in https://github.com/Shelf-nu/shelf.nu/pull/803
