### ISSUE TITLE
[Bug]: Scaning QR does't ask and record location

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#804]
### What happened?

Steps to reproduce:

1. Scan a QR
2. Notice is the browser asks for permissions.

This has been reported by a shelf user. They are having this issue only on chrome, both in pwa and browser mode.
I asked the user some questions and this is the input:

What device do you use? 
> OnePlus Nord 2T 5G
>  
Can you check which version of Chrome you use? 
> 122.0.6261.64
>  
Did you try in another browser(just so we can validate if its a browser or device issue)
> I have logged in using Firefox and I can confirm that the location is now displaying after scanning! 😊
>  
Did you get the popup for permissions for sharing location? I know you said the permissions are there but I am wondering if you get the popup. On theory it should pop-up every time.
> I don’t get a pop-up or any prompt to give permission to share location.
>  
Are you using shelf directly from the website or you added it to your homescreen?
> Previously was Shelf.nu added to the homescreen using Chrome. Above test was using Firefox in browser.
>  
Can you try resetting the permissions for shelf.nu and then scan again? You should get a popup for sharing location.
> I did try this for Chrome but no effect. Could be the fact I am launching from a bookmark on my homescreen?

### What is the expected behaviour?

Browser should ask for permissions

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
I can't recreate that. I have asked the user to help with debugging/testing this. Waiting for response

**Comment by DonKoko** [comment]
This should be resolved by the updates to the scanner. Waiting for response from the user who had the issue.

**Comment by jurrejansen** [comment]
Will get solved by completing https://github.com/Shelf-nu/shelf.nu/issues/914
