### ISSUE TITLE
[Bug]: Cannot select self service users when creating a booking

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#806]
### What happened?

Steps to reproduce:

1. Create a new booking
2. Open dropdown

This was reported by a user but we can't re-create it. I think something is corrupted in their workspace so I am waiting to be added so we can test it.

### What is the expected behaviour?

Being able to assign custody to self-service users.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by carlosvirreira** [comment]
Also, on a team workspace the owner cannot be selected to give custody of an asset to. This seems to also be failing. This was possible before.

**Comment by DonKoko** [comment]
The self service seems to be a one-off bug with this specific user. I couldnt recreate it again. This specific issue has been fixed for the user who reported it, so I am closing this issue. In case it happens again, we will make a new issue.
