### ISSUE TITLE
[Bug]: Booking related bugs / improvements

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#818]
### Contact Details

jurre@shelf.nu

### What happened?

Some bugs related to bookings.

### What is the expected behaviour?

- [x] When you click or paste in the link (in the notification mail) that opens the booking page it should redirect you to the page with the correct workspace active
https://github.com/Shelf-nu/shelf.nu/assets/76112272/78fa90cc-1df0-4262-ba3f-7d04306b9317

- [x] The breadcrumbs is showing 'Edit' throughout the whole journey of the booking. It should just show the booking name once filled
https://github.com/Shelf-nu/shelf.nu/assets/76112272/6cda8b01-1849-4104-8071-3d8c80c6dd0e

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Safari

**Comment by DonKoko** [comment]
@jurrejansen this is solved. Can be tested
