### ISSUE TITLE
[Feature request]: Replace magic link with OTP

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#820]
### Is your feature request related to a problem? Please describe?

Currently we do email confirmation as well as login and sign up with a confirmation url. This causes a lot of issues due to the URLs and their one use tokens getting consumed by anti spam systems.

### Describe the solution you'd like

Basically we are having a lot of issues with magic link so we want to completely replace all clickable links in registration rpcodess with OTP.
That includes:
- Sign up using OTP
- Log in using OTP
- Verify email address via OTP ( this is the default sign up with username/pwd)

So basically we need to add a new view, and make sure that when any of those actions are executed, instead of sending a link, we send a OTP and we sign in the user using the otp, rather than the email.
So for example the /oauth/callback route will basically be gone, and we will have a new route /otp that will just have 1 field and in the action we will perform the sign up, sign in or confirming of email
Supabase already supports that: 
https://supabase.com/docs/guides/auth/passwordless-login/auth-email-otp

and the best part is it works basically almost the same as with magic link, we would just need to change the actual email in the settings of supabase to this. So instead of confirmationUrl we send a TOKEN which is a otp

![image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/86860bb1-e143-4d73-8b44-6449ea5a5dce)
![image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/051d5dcd-1717-4be0-8f07-d07c4d5a1064)

![image](https://github.com/Shelf-nu/shelf.nu/assets/7840007/756c632c-57b2-499b-b6c2-8592d10b5d8e)
Email looks something like this

I already made a branch for this and made a bit of progress, just because I was testing some stuff: https://github.com/Shelf-nu/shelf.nu/tree/replace-magic-link-with-otp

The design of the OTP page will be very simple.
@jurrejansen will provide it in a bit, however we can already start with the backend.

**Comment by jurrejansen** [comment]
@DonKoko here are the scenarios, let me know if we're missing something.

Log in via OTP: https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=3597-79982&mode=design
Sign up via OTP: https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=4068-132354&mode=design
Email confirmation via OTP: https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=4068-133057&mode=design

**Comment by DonKoko** [comment]
Testing scenarios:

- [ ] Sign up using OTP
- [ ] Login using OTP
- [ ] Signup with email and pwd and confirm email via OTP
- [ ] Login without having email confirmed, should trigger OTP email confirmation

**Comment by DonKoko** [comment]
Found an example from Amazon how their OTP emails look. We should do something similar:

```
To authenticate, please use the following One Time Password (OTP):
110531
Don't share this OTP with anyone. Our customer service team will never ask you for your password, OTP, credit card, or banking info.
We hope to see you again soon.
```
<img width="586" alt="Screenshot 2024-03-06 at 11 42 06" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/f2a21466-8185-4cef-80bb-7b867b17ae3e">

**Comment by DonKoko** [comment]
Before we release this, we should clean up and remove all references to the old way of doing it with magic link.

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira this is done and being deployed to test app. Here are the test scenarios:
- [ ]  Sign up using OTP
- [ ] Login using OTP
- [ ] Signup with email and pwd and confirm email via OTP
- [ ] Login without having email confirmed, should trigger OTP email confirmation
- [ ] Resend OTP function

**Comment by jurrejansen** [comment]
@DonKoko "Login without having email confirmed, should trigger OTP email confirmation"

Basically works, but it triggers the "Fill your code" view and not the "Confirm email" view. so nothing major.
