### ISSUE TITLE
[Bug]: All "other" sessions of user should be destroyed when password is changed

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#825]
### What happened?

1- login From two browser at a time [ From Chrome browser and From Mozilla
Firefox ]
2- Change password in setting from chrome browser
3- Now Check Mozilla Firefox
4- Your Session Got Updated in place of expiration

### What is the expected behaviour?

All all sessions from that user in supabase need to be destroyed expired/destroyed.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by rockingrohit9639** [comment]
I can work on this issue @DonKoko

**Comment by rajeshj11** [comment]
@DonKoko can you please assign it to me?
