### ISSUE TITLE
[Feature request]: Add 'Location' filter for asset index

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#841]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

It would be nice to have a Location filter for the asset index.

### Describe the solution you'd like

Hi @rockingrohit9639 

@carlosvirreira and myself were wondering how complex it would be to add this Location filter now we have the new dropdown component. It would behave pretty much the same as the Category and Tag filters.

![Screenshot 2024-03-12 at 16 06 39](https://github.com/Shelf-nu/shelf.nu/assets/76112272/b1b71987-6af1-4859-b0e1-8de9fff07f07)

**Comment by rockingrohit9639** [comment]
Hi @jurrejansen I think it will not take too much time because we have implemented dropdowns to work smoothly with any other models. 
Is there any scenario ready for this filter ? I can give it a shot.

**Comment by jurrejansen** [comment]
Hi @rockingrohit9639 that's great!

Well it should basically work exactly the same as the Category and tag filters. Using the Locations model obviously. However, if you would like me to do a scenario for it I could make one.

Let me know and thanks in advance :)

**Comment by jurrejansen** [comment]
@rockingrohit9639 here's a scenario: https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=4417-11771&mode=design

**Comment by rockingrohit9639** [comment]
Thank you @jurrejansen

**Comment by jurrejansen** [comment]
@rockingrohit9639 there's actually already a Location dropdown being used in the Create asset view. Maybe that's helpful. I also forgot we're using thumbnails for the menu items, so I added those to the design / scenario.


https://github.com/Shelf-nu/shelf.nu/assets/76112272/ff65f353-3957-42aa-9044-3279ea22d485



Also, for the filter used on the asset index you leave out 'Create new location' for now. Just like the Category and Tag filters don't have this on the asset index. Thanks!

**Comment by rockingrohit9639** [comment]
Hnn I know that, That's why I was asking for the scenario @jurrejansen Sorry for not mentioning it earlier.

**Comment by rockingrohit9639** [comment]
Hi @jurrejansen I have created this PR #842 
Please review it once and let if know if any changes are required.

**Comment by carlosvirreira** [comment]
Thank you @rockingrohit9639 !

**Comment by DonKoko** [comment]
@carlosvirreira @jurrejansen its deployed to our staging app.
@rockingrohit9639 I made a review of the PR with one small comment/question

**Comment by jurrejansen** [comment]
Hi @rockingrohit9639 I am re-opening this issue because we're still having problems with dropdown component not showing results after using the search function.

It is the same issue as before that when after you search, it only shows 6 or 3 results and the 'Show all' button doesn't do anything anymore. This was tested on the LIVE branch after it was pushed this morning.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/a7e97dd7-ac08-492b-965c-78be77ca6c5b

**Comment by jurrejansen** [comment]
Hi @rockingrohit9639 thanks for the fix regarding the issue I described in my previous comment. This is working great now.

I was doing some more testing and I found something else which we can hopefully address. The environment in the screen recording has locations called Classroom A up until Classroom J. However if i search on the query 'Classroom' it only gives up to 6 results maximum. (A to F) I can add 'G' for example and it will show Classroom G.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/e6d35243-7e21-4cdf-9e3b-2c4a64e83931

I would expect it to show all locations with 'Classroom' in it. Currently search results are maxed at 6 results. Any reason for this? And would it be possible to show more than 6 results when relevant?

**Comment by rockingrohit9639** [comment]
Hi @jurrejansen 
This is happening because we have a limit of `6` items to be returned from a search query. This can be easily fixed. We can either increase the limit or we can show all the items for a search.

**Comment by jurrejansen** [comment]
Hi @rockingrohit9639 that's good news! I think we should show all relevant results if a search query is active. Do you think this could have major performance issues or not really.

**Comment by rockingrohit9639** [comment]
@jurrejansen I should work fine until user have thousands of items which is not an ideal case. So yeah we can show all relevant results.

**Comment by rockingrohit9639** [comment]
Ok @jurrejansen I will update it.

**Comment by jurrejansen** [comment]
Thanks @rockingrohit9639 works like a charm
