### ISSUE TITLE
[Bug]: Documentation missing for running database migration in Docker

### ISSUE THREAD

**Issue by DASPRiD** [Shelf-nu/shelf.nu#845]
### What happened?

Steps to reproduce:

1. Install via documented Docker method
2. Try to log in
3. Sentry reports that tables are missing, so apparently the schema never got applied

### What is the expected behaviour?

Either the documentation should state on how to apply the database schema, or the start.sh script should run the migrations.

I tried to run `npm run setup:db` in the container, but that fails because there are no schema files in the container.

### Version

Self-hosted

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
PrismaClientKnownRequestError: 
Invalid `prisma.organization.findFirstOrThrow()` invocation:
The table `public.Organization` does not exist in the current database.
```

**Comment by anatolinicolae** [comment]
I think I've seen the same behaviour on my side. I'll get back with a fix for this 👍

**Comment by casef007** [comment]
Any new information on that? I am facing the same issue.

**Comment by anatolinicolae** [comment]
#866 is merged. @DASPRiD & @casef007 give the latest version a try, it should automatically take care of migrations 👍

**Comment by DonKoko** [comment]
Thanks @anatolinicolae. I am closing this issue for now. 
@DASPRiD @casef007 let us know if there is further feedback about this.

**Comment by capriciousduck** [comment]
Can I not run my own Postgres database and use it with my shelf container? Is supabase strictly necessary?

**Comment by DonKoko** [comment]
hey @capriciousduck . Supabase is not only used for DB but also for auth. At this moment it is required to use supabase with shelf. If you choose to, you can always self host supabase via their docker image.
