### ISSUE TITLE
[Improvements request]:  Improve mobile responsiveness of dropdown component

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#848]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

The dropdown component used for filters and select fields isn't always working that great on mobile screen sizes. The dropdown components frequently clips out of the screen, sometimes hiding the component header + search bar. This is mainly because the component is affected by UI elements of device (e.g. keyboard).

https://github.com/Shelf-nu/shelf.nu/assets/76112272/726b7062-a757-4272-8c8b-6e79b488d8db

I've made this issue specifically focusing on improving the mobile responsiveness of the dropdown component.

### Describe the solution you'd like

I've been mentioning the "Github" approach, really like how their filter component behaves. But we can always look at other approaches together. I made a scenario specifically describing the bahaviour of the component on mobile screens.

GITHUB APPROACH
https://github.com/Shelf-nu/shelf.nu/assets/76112272/f0489902-3252-4807-abcb-e339eb6f9dcb

SCENARIO
https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=4477-11784&mode=design

**Comment by jurrejansen** [comment]
@DonKoko in the scenario annotation I'm mentioning the 'Close' icon in the component header. However we're using this area for the 'Clear filter' button currently. I am not entirely sure what would be a good decision here. Maybe we can discuss when u come around to this and have read the annotations etc.

**Comment by DonKoko** [comment]
This is resolved already.
