### ISSUE TITLE
Item notes

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#85]
Create a model for storing notes related to the item as well as build the ui for submitting new notes to an item.

**Comment by jurrejansen** [comment]
Hi @DonKoko 

![Screenshot 2023-05-01 at 16 34 25](https://user-images.githubusercontent.com/76112272/235468807-4794686e-bd8b-4249-8601-7758c943b7ea.jpg)

Seems to be working nicely for the most part. What I noticed:

- [ ] Can we underline links and change font color to primary orange on hover?
- [ ] Looks like clicking on links currently causes Application error

https://user-images.githubusercontent.com/76112272/235469289-07575f3a-49e4-4f29-ae32-0f8cb0942c4b.mov

Currently there's no styling for Block Quote and Code Block markdown syntaxes. But I don't think it's really necessary at the moment. Let me know if I should provide design or we skip.

- [ ] Maybe we can give the headings and paragraphs default top and bottom margins, or at least the headings. This way when a user uses this it looks better

Something like this maybe

Paragraphs (margin-bottom: 16px;)
Heading 1 (margin-bottom: 16px;) 
Heading 2 (margin-bottom: 16px;) (margin-top: 24px;)
Heading 3 (margin-bottom: 16px;) (margin-top: 24px;)

![Screenshot 2023-05-01 at 16 43 59](https://user-images.githubusercontent.com/76112272/235470523-e7668f98-5897-44de-8a03-e9772dfd9708.jpg)

**Comment by DonKoko** [comment]
@jurrejansen man, amazing testing. I will check everything.

**Comment by carlosvirreira** [comment]
This guy @jurrejansen is the master tester

**Comment by DonKoko** [comment]
> Seems to be working nicely for the most part. What I noticed:
> 
>     Can we underline links and change font color to primary orange on hover?
>     Looks like clicking on links currently causes Application error
> 

Done

> Currently there's no styling for Block Quote and Code Block markdown syntaxes. But I don't think it's really necessary at the moment. Let me know if I should provide design or we skip.
> 
>     Maybe we can give the headings and paragraphs default top and bottom margins, or at least the headings. This way when a user uses this it looks better

Both are done. I did it a bit different with the spacings but it works better now.


![Image](https://user-images.githubusercontent.com/7840007/236135806-ba9fdd3f-9ed0-49c4-ad74-7e8a0b399982.png)

**Comment by jurrejansen** [comment]
@DonKoko noice one, a couple of other things I notice

- [ ] Clicking a link still ends with application error

- [ ] By adding the spacing we introduced whitespace that makes the text content in the note container to not be in the center. Not a big deal and kinda nitpicky but maybe there's an easy way to disable the spacing when it's the last line of a note post.

![Screenshot 2023-05-04 at 10 26 23](https://user-images.githubusercontent.com/76112272/236151257-5f46d6ec-059a-42ba-9075-7500d632e311.jpg)

Not sure what was decided on images in notes for MVP but this is what I found

- [ ] Dragging in an image currently only places the 'path' to an image and does not apply the proper syntax for adding an image

- [ ] When adding an image with the proper markdown syntax the image does not show

![Screenshot 2023-05-04 at 10 22 24](https://user-images.githubusercontent.com/76112272/236152617-61fdde0d-10e2-4169-8a82-3e58bb464468.jpg)

**Comment by DonKoko** [comment]
> Clicking a link still ends with application error

Link was not formatted properly. Still it should give a 404 not application error. This will be handled in #37 

>  Dragging in an image currently only places the 'path' to an image and does not apply the proper syntax for adding an image

Not doing this in MVP

>  When adding an image with the proper markdown syntax the image does not show

Should be like this: 
`![Image alt text](http://streamertactics.com/wp-content/uploads/2022/07/widepeepophappy-emote-300x200.png)`

**Comment by DonKoko** [comment]
@jurrejansen would be nice to add some default styling for tables as they look like this atm:
<img width="1034" alt="Screenshot 2023-05-15 at 17 11 54" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/7080257f-d9e4-4d10-a02a-ede566bc8488">

My suggestions: 
- Add borders(maybe some light gray)
- Add some more spacing to the cells?
- Add a background color to the head row
- Add alternating bg colors of the table body rows

Could you do a quick design so I can implement it? Thanks.

**Comment by jurrejansen** [comment]
@DonKoko made a design based on the item index table, but a bit compacter. It's on the "View Item" page in Figma

![Screenshot 2023-05-15 at 17 39 17](https://github.com/Shelf-nu/shelf.nu/assets/76112272/aadf971a-f10b-436b-9b10-abb9f40bc767)

**Comment by DonKoko** [comment]
Deployed the table. CLosing this issue for now.
