### ISSUE TITLE
[Bug]: Invitations don't work

### ISSUE THREAD

**Issue by apvlv** [Shelf-nu/shelf.nu#870]
### Contact Details

andrej@twinbrothers.film

### What happened?

Steps to reproduce:

Invite a user to workspace

### What is the expected behaviour?

get an invite code for the user to sign up

### Version

Self-hosted

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
run/router/dist/router.cjs.js:3422:18)\n    at async handleDataRequestRR (/myapp/node_modules/@remix-run/server-runtime/dist/server.js:119:20)\n    at async requestHandler (/myapp/node_modules/@remix-run/server-runtime/dist/server.js:91:18)"},"label":"Invite","additionalData":{"payload":{"organizationId":"cltv96xjf0000dgkftwq4151d","inviteeEmail":"andrej@twinbrothers.film","inviterId":"2564d02e-87b7-42bc-820b-eb9579715fa7","roles":["ADMIN"],"teamMemberName":"andrej","userId":"2564d02e-87b7-42bc-820b-eb9579715fa7"}},"shouldBeCaptured":true,"status":500,"traceId":"uqivyrl60t8m3sy40zbgq4mh","name":"ShelfError","message":"Something went wrong with creating your invite. Please try again. If the problem persists, please contact support","stack":"ShelfError: Something went wrong with creating your invite. Please try again. If the problem persists, please contact support\n    at makeShelfError (/myapp/build/index.js:18757:36)\n    at action41 (/myapp/build/index.js:42773:18)\n    at async Object.callRouteActionRR (/myapp/node_modules/@remix-run/server-runtime/dist/data.js:35:16)\n    at async callLoaderOrAction (/myapp/node_modules/@remix-run/router/dist/router.cjs.js:4136:16)\n    at async submit (/myapp/node_modules/@remix-run/router/dist/router.cjs.js:3495:16)\n    at async queryImpl (/myapp/node_modules/@remix-run/router/dist/router.cjs.js:3453:22)\n    at async Object.queryRoute (/myapp/node_modules/@remix-run/router/dist/router.cjs.js:3422:18)\n    at async handleDataRequestRR (/myapp/node_modules/@remix-run/server-runtime/dist/server.js:119:20)\n    at async requestHandler (/myapp/node_modules/@remix-run/server-runtime/dist/server.js:91:18)\n    at async /myapp/build/index.js:49065:12"},"msg":"Something went wrong with creating your invite. Please try again. If the problem persists, please contact support"}
shelf  |   --> POST /settings/team/invite-user?_data=routes%2F_layout%2B%2Fsetting
```

**Comment by DonKoko** [comment]
From what I can see from the error, this fails on the sending of the invite, right? So when you add the user email and submit?

**Comment by apvlv** [comment]
Yes, right after clicking invite. The user gets created in the ui despite the error but it is useless, as no invitation is generated

**Comment by DonKoko** [comment]
hey @apvlv, in one of the last updates we released a completely reworked and updated version of how our errors are managed. No matter what the error is, you should be able to see in the terminal what is happening. 
Could you please test this again with the latest version of shelf and let me know what error you see in server logs?

**Comment by apvlv** [comment]
Hey @DonKoko, with the latest 1.7.2 I get the same error as before: 

**Error: secretOrPrivateKey must have a value  at module.exports [as sign]** 

`shelf  |   <-- POST /settings/team/invite-user?_data=routes%2F_layout%2B%2Fsettings.team.invite-user
shelf  | {"level":50,"time":1712588164616,"pid":19,"hostname":"93e653ebc386","err":{"cause":{"stack":"Error: secretOrPrivateKey must have a value\n    at module.exports [as sign] (/src/node_modules/jsonwebtoken/sign.js:111:20)\n    at createInvite (/src/build/index.js:26492:45)\n    at async action41 (/src/build/index.js:43025:12)\n    at async Object.callRouteActionRR (/src/node_modules/@remix-run/server-runtime/dist/data.js:35:16)\n    at async callLoaderOrAction (/src/node_modules/@remix-run/router/dist/router.cjs.js:4136:16)\n    at async submit (/src/node_modules/@remix-run/router/dist/router.cjs.js:3495:16)\n    at async queryImpl (/src/node_modules/@remix-run/router/dist/router.cjs.js:3453:22)\n    at async Object.queryRoute (/src/node_modules/@remix-run/router/dist/router.cjs.js:3422:18)\n    at async handleDataRequestRR (/src/node_modules/@remix-run/server-runtime/dist/server.js:119:20)\n    at async requestHandler (/src/node_modules/@remix-run/server-runtime/dist/server.js:91:18)"},"label":"Invite","additionalData":{"payload":{"organizationId":"cltv96xjf0000dgkftwq4151d","inviteeEmail":"andrej@twinbrothers.film","inviterId":"2564d02e-87b7-42bc-820b-eb9579715fa7","roles":["ADMIN"],"teamMemberName":"andrej","userId":"2564d02e-87b7-42bc-820b-eb9579715fa7"}},"shouldBeCaptured":true,"status":500,"traceId":"d2ddfkretawm2lesp4laxbaw","name":"ShelfError","message":"Something went wrong with creating your invite. Please try again. If the problem persists, please contact support","stack":"ShelfError: Something went wrong with creating your invite. Please try again. If the problem persists, please contact support\n    at makeShelfError (/src/build/index.js:18761:36)\n    at action41 (/src/build/index.js:43040:18)\n    at async Object.callRouteActionRR (/src/node_modules/@remix-run/server-runtime/dist/data.js:35:16)\n    at async callLoaderOrAction (/src/node_modules/@remix-run/router/dist/router.cjs.js:4136:16)\n    at async submit (/src/node_modules/@remix-run/router/dist/router.cjs.js:3495:16)\n    at async queryImpl (/src/node_modules/@remix-run/router/dist/router.cjs.js:3453:22)\n    at async Object.queryRoute (/src/node_modules/@remix-run/router/dist/router.cjs.js:3422:18)\n    at async handleDataRequestRR (/src/node_modules/@remix-run/server-runtime/dist/server.js:119:20)\n    at async requestHandler (/src/node_modules/@remix-run/server-runtime/dist/server.js:91:18)\n    at async /src/build/index.js:49753:12"},"msg":"Something went wrong with creating your invite. Please try again. If the problem persists, please contact support"}
shelf  |   --> POST /settings/team/invite-user?_data=routes%2F_layout%2B%2Fsettings.team.invite-user 500 308ms`

**Comment by apvlv** [comment]
Hey @DonKoko, you are right, it was this issue! Now it is working. Maybe you could update the docker documentation :)

**Comment by Insomniacnomis** [comment]
I am having the same issue, but I cannot find where this invite token is defined. Is it from Supabase?

**Comment by DonKoko** [comment]
hey @Insomniacnomis, if you are using docker, you need to add it on your start command  variables. If you dont use docker, just add it to your .env file. For the value you can just generate any uuid and it should work.

**Comment by mrgparys** [comment]
I'm having the same issue with a slightly different error message. While sending mails typically work, sending an invitation shows the following error:

`2024/09/09 11:02AM 50 pid=67 hostname=04c8622cf5d4 err={"cause":{"cause":{"code":"EDNS","syscall":"queryA","hostname":"no-reply@*****.de","command":"CONN","stack":"Error: queryA EBADNAME no-reply@*****.de`
   
`at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/callback_resolver:45:19 undefined)"},"label":"Email","additionalData":{"to":"*****@*****.de","subject":"You have been invited to vibin"},"shouldBeCaptured":true,"status":500,"traceId":"e8cczcw4ek4uu93t6u89da3l","name":"ShelfError","message":"Unable to send email","stack":"ShelfError: Unable to send email`   

[...]

`at async queryImpl .async queryImpl (/src/node_modules/@remix-run/router/dist/router.cjs.js:3890:22 undefined)"} msg=Something went wrong with creating your invite. Please try again. If the problem persists, please contact support`

The user is created but no mail is sent.

Any help or hint is much appreciated.
