### ISSUE TITLE
[Enhancement request]: Change date picker on custom field

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#894]
### Is your feature request related to a problem? Please describe?

I sometimes spend too much time clicking around with the current date modal for custom fields (date) to select the purchase date of my assets. 

Some of my assets are 10 years old. Lots of clicking around.

### Describe the solution you'd like

Can we use a date picker similar to the one we have in Bookings? Without the time field. Just date. Or just let me input a date in text.

**Comment by DonKoko** [comment]
@Bhavyajain21 I would like you to work on this when you are done with your current issue. Lets discuss it.

**Comment by DonKoko** [comment]
@Bhavyajain21 yes, it needs to be just a normal html date input, the same as with bookings but without the time. That means we dont need the popover or anything like this as that comes native in the browser.

/bounty 10

**Comment by DonKoko** [comment]
@carlosvirreira this has been adjusted and released to live. We replaced the date picker with had with a native browser date picker which works smoother on all devices. We also included the button to clear it for the case when its a not required field and the user might want to do that. Would be great if you can inform the users that asked for it.

**Comment by carlosvirreira** [comment]
Doing right now and will be part of the small improvement notes on an upcoming Newsletter.
