### ISSUE TITLE
[Bug]: Docker, the non-dev dependencies breaks seeding the DB (docker exec -it shelf npm run setup:seed), prisma relies on tsx to seed the DB, and it's a dev dependency.

### ISSUE THREAD

**Issue by joran98** [Shelf-nu/shelf.nu#906]
### Contact Details

joran.98@hotmail.com

### What happened?

Not my issue, and I don't understand how to fix it. But as @null-dev stated the non-dev dependencies breaks seeding the DB (docker exec -it shelf npm run setup:seed), prisma relies on tsx to seed the DB, and it's a dev dependency.
https://github.com/Shelf-nu/shelf.nu/pull/866#issuecomment-2028489764

### What is the expected behaviour?

pruning the non-dev dependencies breaks seeding the DB (docker exec -it shelf npm run setup:seed), prisma relies on tsx to seed the DB, and it's a dev dependency.

### Version

Self-hosted

### What browsers are you seeing the problem on?

Safari

**Comment by DonKoko** [comment]
@anatolinicolae tagging you here as I cant assign yet.

**Comment by anatolinicolae** [comment]
Cool cool, will get on the PR as soon as possible! 👍

**Comment by cn-ml** [comment]
Is there any quick workaround to seed the db and continue with the setup? I tried `npm install` to get the dev dependencies, but no luck with that because the prepare command requires husky which is missing (and i assume some other things too)

**Comment by anatolinicolae** [comment]
`npm ci` should do the trick ✅

**Comment by cn-ml** [comment]
both commands (ci and install) give the same output

```
root@shelf:/src# npm ci

> prepare
> husky install

sh: 1: husky: not found
npm ERR! code 127
npm ERR! path /src
npm ERR! command failed
npm ERR! command sh -c husky install

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-04-22T20_26_10_726Z-debug-0.log
```

**Comment by DonKoko** [comment]
Hey @joran98. Due to this and some other issues we were having with seeding we have completely removed this functionality via `tsx seed` and have created some simple sql migrations for creating the same data that the seed was creating.
Release: https://github.com/Shelf-nu/shelf.nu/releases
PR: https://github.com/Shelf-nu/shelf.nu/pull/921

You should not be seeing this issue anymore as there is no seed to run anymore.
