### ISSUE TITLE
[Improvement request]: Send email to all admins instead of asset owner when Contact owner form gets submitted

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#911]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

Asset owner is a legacy concept. After discussion sending the email with form submission to all workspace admins makes more sense.

### Describe the solution you'd like

Send form submission email to all workspace admins instead of asset owner.

**Comment by DroneProf** [comment]
@jurrejansen it seems to function this way now!

**Comment by jurrejansen** [comment]
@DroneProf you're right! thanks for informing :)
