### ISSUE TITLE
[Feature request]: General Bugs and Improvements

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#916]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

Logging small bugs and improvements when found.

### GENERAL

- [ ] The random border line on the right has returned. Shows on basically every view.
![Screenshot 2024-04-19 at 10 29 43](https://github.com/Shelf-nu/shelf.nu/assets/76112272/bfa250c2-fa5b-467c-8ba4-8d0f55528724)

- [x] Border of the Account details element has disappeared
![Screenshot 2024-04-19 at 10 30 05](https://github.com/Shelf-nu/shelf.nu/assets/76112272/0a90589c-ec57-46ab-9ecc-84bbd50be8a0)

- [ ] Remove or hide the header component with the H1 on all index pages, especially the asset index
https://github.com/Shelf-nu/shelf.nu/assets/76112272/c89c171e-de52-41bb-ad0e-7478c85712e6

### ASSET INDEX

Change placeholder copy in search fields of filters
- [x] Search Filter by Category -> Search categories
- [x] Search Filter by Location -> Search locations
- [x] Search Filter by Tags -> Search tags

Request: 
- [ ] Search Filter by Custodian

ASSET PAGE

- [x] Add a default field stating when asset was created
![Screenshot 2024-04-19 at 10 40 10](https://github.com/Shelf-nu/shelf.nu/assets/76112272/d3638ae2-5497-4c37-b8eb-2f62ac09f6ee)

- [x] Log asset creation at the very beginning on Notes
![Screenshot 2024-04-19 at 10 41 07](https://github.com/Shelf-nu/shelf.nu/assets/76112272/4be6dcf4-4538-450d-a5ae-767129f78d83)

### BOOKINGS

- [x] Let administrators change the booking name when booking is in Reserved, Ongoing and Overdue state
- [x] Can we change that a Draft booking gets created once the user clicks Check Asset availability instead of when New booking is clicked
https://github.com/Shelf-nu/shelf.nu/assets/76112272/3d59ec70-90f9-4624-aba1-320d26908495
- [x] I find it a bit annoying that the Name field is already filled when I create a booking (especially on mobile). Takes me a few extra seconds every time I create a booking to remove the filled text in the Name field. If we can have the Untitled booking placeholder text it would be better I think.
https://github.com/Shelf-nu/shelf.nu/assets/76112272/535a609d-a1f1-4abb-9f11-0cbbf8f2954b
- [ ] On a team plan without team members I cannot self assign a booking to me (account owner)
- [x] As Self-service user, after having Reserved a booking I see this tool tip when hovering the Manage assets buttons. Let's fix the spelling: "You're unable to manage assets at this point because the booking is Reserved. Cancel the booking and create another one if you need to make changes."
![Screenshot 2024-04-30 at 10 06 45](https://github.com/Shelf-nu/shelf.nu/assets/76112272/727463bc-8c92-461b-9014-e162c8c8a617)
- [ ] If not too much of a hassle, can we disable tool tips on bookings when the page is loading. Tool tips appear on the buttons that are disabled while page is loading that are not relevant and could confuse the user perhaps.
https://github.com/Shelf-nu/shelf.nu/assets/76112272/fa0c2bac-30c9-4e7a-8b09-d73412a33dc5

### SETTINGS > TEAM

- [ ] Allow sorting of NRMs

**Comment by carlosvirreira** [comment]
1) Can we change that a Draft booking gets created once the user clicks Check Asset availability instead of when New booking is clicked

2)  I find it a bit annoying that the Name field is already filled when I create a booking (especially on mobile). Takes me a few extra seconds every time I create a booking to remove the filled text in the Name field. If we can have the Untitled booking placeholder text it would be better I think.

 
 Pass (Desktop and Mobile) - no problems - can be released imo.
