### ISSUE TITLE
[Improvement request]: Adding filters to Manage bookings modal

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#919]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

Requested by a user. Specifically a category filter was requested. Can imagine this would be very helpful for a lot of users.

### Describe the solution you'd like

Implementing the filters that are in the designs.
![Screenshot 2024-04-22 at 17 17 17](https://github.com/Shelf-nu/shelf.nu/assets/76112272/7b101418-67be-4302-86fa-d6d0231cbc65)
![Screenshot 2024-04-22 at 17 22 31](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a1ee1b43-cd6b-4ef0-ace4-107b397484d6)

**Comment by jurrejansen** [comment]
- [ ] The Location filter specifically is not working like expected
https://github.com/Shelf-nu/shelf.nu/assets/76112272/6200b70c-81cc-482c-86ae-e20d18385f27

**Comment by DonKoko** [comment]
@jurrejansen thanks man. I am working on it now.
