### ISSUE TITLE
[Bug]: Custom fields are not copied when duplicating an asset

### ISSUE THREAD

**Issue by cn-ml** [Shelf-nu/shelf.nu#924]
### What happened?

Steps to reproduce:

1. Go to 'asset page for asset with custom fields'
2. Click on 'actions > duplicate'
3. Go to 'asset page for duplicate'
4. Custom fields are missing

### What is the expected behaviour?

Not entirely sure if this is a bug, could be intended behaviour (i dont know any use case for this). In my opinion it should be expected that all fields are copied (even if they are stored in another table). I just checked the behaviour for tags (which are also stored in a M2M table) and they are indeed copied over.

### Version

Self-hosted

### What browsers are you seeing the problem on?

Chrome

**Comment by carlosvirreira** [comment]
Thank you for the issue @cn-ml - I believe this is indeed expected behavior - we will discuss including this as an improvement. 

Also, super nice you are self hosting shelf - what are you using it for?

**Comment by carlosvirreira** [comment]
Thank you for your words @cn-ml 

What would be the top 3 features you think shelf needs to match your wishes? Can help us with priorities.

**Comment by cn-ml** [comment]
Features that I'd like to have rougly in order of my preference:

1, Being able to have multiple similar assets as a countable sum without having to maintain many equal asset entries manually #912
2. Creating groups of assets that can be used in bookings and bulk update locations and owners
3. Self-hosting without supabase, local postgres and assets serving
4. User-friendly docker setup #906
