### ISSUE TITLE
[Feature request]: Custodian filter for asset index

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#938]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

Custodian is the last column that cannot be filtered on. Also it's the only filter that has not yet been implemented from the designs.

### Describe the solution you'd like

Add Custodian filter using the reworked dropdown component. I have a design that shows an avatar for every menu item but perhaps we can skip this modification in favor of faster release.
![Screenshot 2024-04-29 at 17 46 02](https://github.com/Shelf-nu/shelf.nu/assets/76112272/c7e4c75d-5dd8-44d0-bc25-ebed322781f4)

**Comment by carlosvirreira** [comment]
I thought we had this but on a demo call I recognized that we do not. If low story points would be a nice release.

**Comment by DonKoko** [comment]
@jurrejansen @carlosvirreira small update. We made this work with custodians but we realized its way more complex because it needs to also search via bookings for assets which are part of a booking, as we also show that in the custodian column. 
In general this whole concept is kinda messy that we have 2 separate things(bookings and custody) but we show them both in the same column. Anyways it will take a bit more time as its quite complex to adjust this. Will keep you updated.

**Comment by carlosvirreira** [comment]
Thank you for the update - I understand the complexity. 

@DonKoko

**Comment by jurrejansen** [comment]
> In general this whole concept is kinda messy that we have 2 separate things(bookings and custody) but we show them both in the same column.

@DonKoko Don't think it's messy. Custody is long-term check-out and Booking is time based check-out. The concept of Custodian is just related to both

**Comment by DonKoko** [comment]
@jurrejansen that's fine I agree. But then maybe the long-term checkout should not be called "Assign custody" & "Release custody" it should be just "Check-out" & "Check-in" to make it more consistent and simple. What do you think?

Ooh and the custodian filter is being deployed now. It was a hassle but we solved it: https://github.com/Shelf-nu/shelf.nu/actions/runs/9109997287

**Comment by carlosvirreira** [comment]
Check out and check in is the language that our market uses. I approve this change. We will have to change a lot in the marketing site but I find it ok.
