### ISSUE TITLE
[Feature request]: Incorporate (Team or Professional) selection on user create flow

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#940]
### Is your feature request related to a problem? Please describe?

Right now, when you register to shelf you have a personal account. If your intention was to get on to a team account you have to do some steps. 

You have to basically go to settings > subscription and enable a trial. 

This is something we can streamline from the user create flow by simply knowing if the user wants to use shelf for personal use or for professional use. 

### Describe the solution you'd like

On the sign up flow, make a step in which a user selects his intended end use-case. If professional, we allow the user to directly set up a subscription or start a 14 day trial.

**Comment by jurrejansen** [comment]
@DonKoko @carlosvirreira I made a scenario for it. the idea is to add a second to last slide during onboarding to let the user choose a Personal or Team use case. Depending on their choice the last slide will be:

Personal -> Lets create your first asset
Team -> Lets create your Team workspace (after confirming trial in Stripe)

SCENARIO
https://www.figma.com/file/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?type=design&node-id=4998-24025&mode=design

**Comment by carlosvirreira** [comment]
Thank you it looks great @jurrejansen
