### ISSUE TITLE
[Bug]: Dropdown component used for assigning custody is not loading additional entries when clicking Show all

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#943]
### Contact Details

jurre@shelf.nu

### What happened?

I've noticed this issue happens pretty much every time the dropdown component is implemented at a new place. Maybe it something that can fixed at the core of the component so the issue doesn't return?

Steps to reproduce:

1. Go to 'Asset page' and 'Assign custody'
2. Click on 'Custodian field'
3. Scroll down to 'Show all' and click 'Show all'

https://github.com/Shelf-nu/shelf.nu/assets/76112272/a2a0ec3c-aa7c-430f-8323-8a04d91b52a7

### What is the expected behaviour?

It should load the rest of the Custodian entries.

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
hey @jurrejansen . I am deploying a fix now. I do agree with you we have to figure out some way to resolve this. Its not a component issue but its more about how the component interacts with data from the server.
@rockingrohit9639 shall we think of a way to enforce some types in the component that we make sure the initial data is always correct. Something to think about.

**Comment by DonKoko** [comment]
Solved in #947
