### ISSUE TITLE
Feature: Allow self assign custody over an asset as a TEAM / Personal workspace owner

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#944]
### What happened?

I create a team workspace on test-app - I am the only user. 

I create an asset and want to assign it to me. I do not see myself as a team member.

Jurre on Discord writes "This issue happens every time the dropdown component gets added to a new place" 

### What is the expected behaviour?

Allow me to self-assign assets as the workspace owner.

<img width="959" alt="Screenshot 2024-04-30 at 14 36 19" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/56d893ed-4abc-418e-aed8-a7c1148aaeb0">

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
Currently we only can assign custody via a `teamMember`.  NRMs are team members so are invited users, but the owner doesnt have a team member attached to them.
We would need to adjust the creation of a workspace by creating a teamMember for the owner when the organization is created.
We would also need to update the UI as well.

**Comment by DonKoko** [comment]
hey @rockingrohit9639, can you please look into this. Here are the things we need to handle:

- [ ] When a new workspace(organization) is created, we always need to create a `teamMember` for the owner and connect it to the owner
- [ ] We need to make a migration and write some SQL code, that checks each workspace and if there is no `teamMember` for the owner, we need to create one.
- [ ] We have to make sure that every place where we create an org, we actually use `createOrganization` as that handles all the connected data

**Comment by rockingrohit9639** [comment]
Sure @DonKoko I will look into it.
