### ISSUE TITLE
[Feature request]: Improve error messages

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#945]
### Is your feature request related to a problem? Please describe?

I have made some fields as required for an asset. 

When I try to save, the app seems broken. The reason why I cannot save is due to the fact that there are required fields to fill for me to be able to complete my intended action. 

### Describe the solution you'd like

Maybe we can show the error message above the page instead of below next to each field?

**Comment by DonKoko** [comment]
@carlosvirreira this was resolved. We made a proper solution that if you have an error in a field that is currently not in the viewport, it will scroll you there. Really great and elegant solution we did with @Bhavyajain21. I am quite happy with it.
