### ISSUE TITLE
[Feature request]: General bugs and improvements 3

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#957]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

Logging small bugs and improvements when found.

### GENERAL

- [x] Labels for most of the input fields are set to display:none / not visible on tablet breakpoint
![Screenshot 2024-05-06 at 17 25 44](https://github.com/Shelf-nu/shelf.nu/assets/76112272/0cab424b-76b1-475e-980e-2bc9ea7a17df)

- [ ] The random border line on the right has returned. Shows on basically every view
![image](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a028f1b6-8cc3-4ace-ac12-f993edb9989c)

- [ ] Remove or hide the header component with the H1 on all index pages, especially the asset index
https://github.com/Shelf-nu/shelf.nu/assets/76112272/c89c171e-de52-41bb-ad0e-7478c85712e6

- [x] Shorten username and email in Account profile element when it doesn't fit
![Screenshot 2024-05-06 at 17 02 56](https://github.com/Shelf-nu/shelf.nu/assets/76112272/2233de83-3e21-45a6-a2b3-7ecbd92b8cf2)
![Screenshot 2024-05-06 at 16 59 12](https://github.com/Shelf-nu/shelf.nu/assets/76112272/4b46c275-41c4-4818-b213-7f82e6a0029c)

### BOOKINGS

- [x] If not too much of a hassle, can we disable tool tips on bookings when the page is loading. Tool tips appear on the buttons that are disabled while page is loading that are not relevant and could confuse the user perhaps
https://github.com/Shelf-nu/shelf.nu/assets/76112272/fa0c2bac-30c9-4e7a-8b09-d73412a33dc5

**Comment by DonKoko** [comment]
>  Remove or hide the header component with the H1 on all index pages, especially the asset index

This will be done(or at least some version of it) when we release the bulk actions

>  The random border line on the right has returned. Shows on basically every view

This is the border of the scrollbar of chrome. Its just the same color/width as our borders so it looks confusing
