### ISSUE TITLE
[Bug]: Clearing a category or location from an asset is not possible or hard

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#961]
### Contact Details

jurre@shelf.nu

### What happened?

I think a decision was took to remove the Clear button that was positioned next to certain select fields when the reworked dropdown component was implemented. This resulted in:

- Not being able to clear a category from an asset making it Uncategorized (as far as can see)
- Not being able to easily clear a Location from an asset without going to the location page and doing it there
- Not being able to clear the Custodian field when assigning (not that impactful as you can just cancel or Release custody but still would like to see it there for the sake of consistency)

The Clear button is still present in the Update location modal but it doesn't clear the field.

https://github.com/Shelf-nu/shelf.nu/assets/76112272/61b5390b-e919-405e-8d00-513ab8ed10e1

### What is the expected behaviour?

- Being able to clear the category field with Clear button and Save the asset making it Uncategorized
- Being able to clear the location field (both on Create / Edit view and Update location modal) with Clear button and Save resulting in the asset having no location
- Being able to clear the Custodian field with Clear button in the Assign custody modal

### Version

Hosted (app.shelf.nu)

### What browsers are you seeing the problem on?

Chrome

**Comment by DonKoko** [comment]
@jurrejansen this is fixed and deployed. We updated the dynamic select component so clicking on the item that is currently selected clears it. I think we can improve it by changing the icon on hover in that case so the user knows they can remove by clicking. What do you think?
