### ISSUE TITLE
[Feature request]: Show who created a booking on the booking page

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#969]
### Is your feature request related to a problem? Please describe?

I am on a mobile phone. I open a booking and I see an issue. 

On desktop, when I go to the booking page. I have a column that shows me who created a booking. That way I can get in touch with this person to discuss things around the booking. 

I have no way to do this on mobile. 

### Describe the solution you'd like

Add the booking creator data on the booking page on mobile and desktop.

**Comment by DonKoko** [comment]
@jurrejansen can u make a quick design for this? I want to make a bounty. Lets keep it super simple.

**Comment by carlosvirreira** [comment]
I think the issue here is that, although it looks nice on mobile the information on the booking tab. Is not giving much value. 

I can see 'name' 'status' so it is not really giving me insight on the booking so I can take a quick action.

Things I should be able to answer by going to the booking tab on mobile for 1 asset:

- Can I use this booking on (next week?)
- If it is reserved, who reserved it?
- Can I use this asset for a booking after it's done with the current booking? If so, when does it end?

**Comment by DonKoko** [comment]
OKey based on the issue title i was thinking about something completely different. You are talking about the asset page but based on the original issue i thought you were talking about the booking page. I think this is relevant in both cases. Lets decide which case this issue is for and create a different issue for the other case. Then we can tackle them both at some point.

**Comment by jurrejansen** [comment]
@DonKoko @carlosvirreira Perhaps we should then consider to not use the simplified tables on mobile and implement the horizontal scroll globally for tables. It works better than I expected anyways when I see tables like Custom fields for example. Would be best that only the content and column header are scrollable though.

Perhaps start with the Booking index?

![Screenshot 2024-07-02 at 13 48 35](https://github.com/Shelf-nu/shelf.nu/assets/76112272/c269bee8-7e52-4245-8fe2-d65f8c93bbb0)

https://github.com/Shelf-nu/shelf.nu/assets/76112272/f573d66b-172b-4b0b-b99c-03a009129f03

**Comment by carlosvirreira** [comment]
If we do sidescroll, we have to find a way to make it super clear you can scroll to reveal more. At the moment not sure what/how.

**Comment by jurrejansen** [comment]
I think in most cases it is going to be pretty clear when the cells of a second column in a table are partly off screen. However the underlined approaches I kinda like but they're probably not 'keeping it simple'.

![Screenshot 2024-07-02 at 14 35 12](https://github.com/Shelf-nu/shelf.nu/assets/76112272/c11531b7-aaf1-48d1-82c5-775505399087)

![Screenshot 2024-07-02 at 14 40 38](https://github.com/Shelf-nu/shelf.nu/assets/76112272/a421a716-c501-41be-934c-f8d4688d997c)

**Comment by jurrejansen** [comment]
@DonKoko I've added the scenario in the OP. Let me know if I need to annotate the artboards

**Comment by carlosvirreira** [comment]
I approve and commit to the option picked. Let's proceed.

**Comment by rajeshj11** [comment]
> @jurrejansen good points. I think the sticky first column is too much on mobile. There will be very little space left, but for sure something I would implement on desktop once we start adding more columns and we need more space.
> 
> @carlosvirreira can we agree we do the first option for now for mobile? ![Screenshot 2024-07-12 at 10 12 16](https://private-user-images.githubusercontent.com/7840007/348160328-a287203f-081e-4763-9ca9-1d70a8c2637a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDYxODUsIm5iZiI6MTcyNDI0NTg4NSwicGF0aCI6Ii83ODQwMDA3LzM0ODE2MDMyOC1hMjg3MjAzZi0wODFlLTQ3NjMtOWNhOS0xZDcwYThjMjYzN2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjFUMTMxMTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjY5NmUyOTgzOWMzM2M4NTYwMWNmYWUzN2JlZDhiMjk4NTA3YTBkZGU1YTQzZTIzODczNDM4NDg3YTNmOTAyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3mLvvoW3sG9Q2gRIKOPvIsQZjkVKOf7mX-R8cYucKZI) Then I can make a bounty and assign.

resolved the actions issue.

i am not sure about the calendar. @DonKoko does calendar use List or table.
