### ISSUE TITLE
[Improvement request]: Revamped asset page

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#972]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

The current asset page is outdated, has too little space to accommodate UI elements related to currently existing and/or upcoming features and too focused on the Notes / Activity log.

### Describe the solution you'd like

A new layout that uses tabs in order to categorize the different the information shown on the asset page.
Figma preview link: https://www.figma.com/design/iKu7Cn98DOCHcpBHgPCPCt/Shelf-%7C-UX-Scenarios-(Copy)?m=dev&node-id=107%3A42253&t=K9D3hlXCJuvsk9Z5-1

You can see the preview above. This should be the basic design we have to start with.

Some important things to keep in mind:

- The new design uses tabs. You need to create a route for each tab and we need to adjust the loaders and how data is managed. You can see exactly how to create the different routes and tabs in the settings area of shelf.
- Some specific elements such as the QR area or the Map, might look different than what we have right now. Please ignore them and just use this as a reference for the structure of the page. You should not for example redesign the map component and all its data. It should look as it does now, just positioned differently as based on the new design.
- The activity tab should include the current notes that are on the asset page. No design change, just placed within the activity tab.

**Comment by DonKoko** [comment]
@jurrejansen  A few points to improve in the design so we can pass it on for dev. We need to make it based on feature we have currently not based on what we want to have so the developer knows what to work on.
- [ ] Leave only the relevant tabs. I would say `Overview` and `Activity`. Once we have those we can considering adding the other tabs.
- [ ] QR area - please add only the settings and options we currently have. So remove the color, size file and the 2 switches
<img width="363" alt="Screenshot 2024-05-15 at 15 46 22" src="https://github.com/Shelf-nu/shelf.nu/assets/7840007/ae2f5fe9-c469-4437-a6cb-254351cd28d9">
- [ ] Same for the map/scan info. We are currently showing more info that is all relevant. 
- [ ] I am wondering about the asset image. If I want to see the image in bigger size, how can I do it? 
- [ ] For the activity tab, do we have some big structural changes? I would say we can just display them the same way we have them now, and simply update the cards for each note/update in the future.

**Comment by jurrejansen** [comment]
@DonKoko alrighty clear, I planned to provide some proper scenarios hence the issue is still WIP. It needs a bit more thought because the design was done a while back.

**Comment by DonKoko** [comment]
@jurrejansen agree, thats why I wanted to give some pointers to make it easier on you. Give me a call on discord if you want to discuss this further.

**Comment by DonKoko** [comment]
Hey @Bhavyajain21. I have taken the time to update the asset page design to simplify it and make it easier for you to understand. I have also updated the original issue description, including the link and added some important points. Please take a look.

**Comment by DonKoko** [comment]
@Bhavyajain21 can you do the image thing as well? I can give you a small bonus to the bounty for adding it.
![Screenshot 2024-05-27 at 20 37 18](https://github.com/Shelf-nu/shelf.nu/assets/7840007/48cf3da4-2d90-472a-87b1-558e73e7de91)

To make it work you will need to do a few things:
- [ ] Update the dialog component we have. Currently its made to work only with routes. What we can do is move the current code of dialog inside `contextual-modal.tsx` as this is the only place its used and then in rework the dialog component to not work based on routes but just as a standalone component we can use for example to show an image
- [ ] then you can implement that dialog on the asset page, when clicking the image.

**Comment by jurrejansen** [comment]
@DonKoko @carlosvirreira Adding a few scenarios hoping to clear certain things up.

     ↳ Creating a new asset
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=5575-446834

     ↳ Filling fields of an asset that has nothing filled
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=5563-91754

     ↳ Viewing attached image(s)
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=1529-216039


Adding this one to show where all elements will go and in what order.
     ↳ Asset has all field filled, awaiting signature and is part of kit
https://www.figma.com/design/ykvc0MhPeNLsrJ4tJsKosQ/Shelf-%7C-UX-Scenarios?node-id=5757-56173
