### ISSUE TITLE
Allow for command + enter to post a comment on asset view

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#98]
small improvement, nice for power users

**Comment by DonKoko** [comment]
Deployed.

**Comment by carlosvirreira** [comment]
Tested on Safari, it unfortunately does not work @DonKoko

**Comment by DonKoko** [comment]
Fixed. Deploying now.

**Comment by DonKoko** [comment]
This works now. Confirmed also by carlos via discord. Was a stupid mistake on my side.
