### ISSUE TITLE
[Feature request]: Duplicate should also include custom field values

### ISSUE THREAD

**Issue by DonKoko** [Shelf-nu/shelf.nu#986]
### Is your feature request related to a problem? Please describe?

Currently when you duplicate an asset that has some custom field values, they dont get duplicated.

### Describe the solution you'd like

When you duplicate the asset, the custom field values also get duplicated so your new assets is 1:1 with the source asset.

**Comment by carlosvirreira** [comment]
+ 1 for this!

**Comment by DonKoko** [comment]
@rajeshj11 want to take care of that?

**Comment by rajeshj11** [comment]
> @rajeshj11 want to take care of that?

Yeah sure please assign it to me

**Comment by carlosvirreira** [comment]
> > @rajeshj11 want to take care of that?
> 
> Yeah sure, please assign it to me

You're Awesome Rajesh - Thank you so much.

**Comment by rajeshj11** [comment]
> /attempt #986

Hey, it is already assigned to me.

**Comment by DonKoko** [comment]
@carlosvirreira this is solved and being deployed. But I dont remember who requested this. Anyways, it can be included in the newsletter notes.

**Comment by carlosvirreira** [comment]
Insane speed. This was requested (will DM you) rhymes with maiders
