### ISSUE TITLE
[Feature request]: On asset create - allow user to select if the asset is individually tracked or batch tracked

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#992]
### Is your feature request related to a problem? Please describe?

I need to track certain assets as a batch / with quantities. 

### Describe the solution you'd like

<img width="278" alt="Screenshot 2024-05-23 at 20 45 25" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/c5265f9a-a883-48e3-8276-fd3151e4a884">

**Comment by jurrejansen** [comment]
@carlosvirreira we have an issue for this https://github.com/Shelf-nu/shelf.nu/issues/912

It still needs defining but it's more complex than just simply adding a quantity field. Need to figure out how it interacts with checking out certain amounts of total quantity to multiple different custodians etc.

Think this issue can be closed.

**Comment by jurrejansen** [comment]
Closing this and adding the latest scenarios related to this in https://github.com/Shelf-nu/shelf.nu/issues/912
