### ISSUE TITLE
[Feature request]: Add DKK (Denmark) as optional currency for workspaces

### ISSUE THREAD

**Issue by jurrejansen** [Shelf-nu/shelf.nu#993]
### Contact Details

jurre@shelf.nu

### Is your feature request related to a problem? Please describe?

Was requested by a user.

`Hi, you have SEK, NOK, but not DKK in currency. Why?`

### Describe the solution you'd like

Add it as an option when configuring currency in workspace settings if possible.

**Comment by vardhan0604** [comment]
can I work on this @carlosvirreira ?

**Comment by DonKoko** [comment]
@vardhan0604 yes, of course. Feel free to take care of it and Open a PR.
