### ISSUE TITLE
[Feature request]: Language change

### ISSUE THREAD

**Issue by carlosvirreira** [Shelf-nu/shelf.nu#994]
### Is your feature request related to a problem? Please describe?

On sign up I can create an account using OTP, this is not clear at all by the copy. 

<img width="439" alt="Screenshot 2024-05-24 at 14 59 38" src="https://github.com/Shelf-nu/shelf.nu/assets/12449255/6c5f088a-a2b7-4c32-8478-d01bdb907ef4">

### Describe the solution you'd like

change 'Or send me a signup link'

**Comment by vardhan0604** [comment]
Hey @carlosvirreira , I would like to do this , can you please assign.
This is my first time contributing.

**Comment by vardhan0604** [comment]
@DonKoko should I just change "Or use a One Time Password" to this "Or send me a signup link"??

**Comment by DonKoko** [comment]
@vardhan0604 based on the issue description of Carlos, i think this should be enough, however I am pretty sure that the form for OTP is the same for login and signup, so you need to make it dynamic by checking which route you are on. You can do it via the `mode` param passed to the component.

**Comment by jurrejansen** [comment]
Maybe this is already enough?

Change button text from "Continue with OTP"  to "Sign up with OTP"

**Comment by DonKoko** [comment]
Yeah i like that suggestion as well. I think we can do both.

**Comment by carlosvirreira** [comment]
I did not know what OTP meant until I tried it - would have not assumed that it would create a user with that mail as the account.
